{
  "hash": "4ecc0698dc942c61042a770b8231f493",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"W7-W8. Sets, Maps, Binary Search Trees, AVL Trees, Red-Black Trees\"\nauthor: \"Nikolai Kudasov\"\ndate: \"February 23, 2026\"\nformat: html\nengine: knitr\n---\n\n#### **1. Summary**\n\n##### **1.1 Sets and Maps**\n\n###### **1.1.1 The Set Abstract Data Type**\n\nA **Set** is an abstract data type that represents an *unordered collection of values without duplicates*. Think of it like a mathematical set: $\\{1, 3, 4\\}$ — order does not matter, and every element appears at most once.\n\nWe work with **dynamic sets** that support operations modifying the collection at runtime:\n\n- **add(x):** Add element $x$ to the set. If $x$ is already present, do nothing.\n- **remove(x):** Remove element $x$ from the set.\n- **contains(x):** Return true if $x$ is in the set, false otherwise.\n\n**Example:**\n\n$$\\{1, 3, 4\\} \\xrightarrow{\\text{add}(5)} \\{1, 3, 4, 5\\} \\xrightarrow{\\text{remove}(3)} \\{1, 4, 5\\}$$\n\n###### **1.1.2 The Map Abstract Data Type**\n\nA **Map** (also called a *dictionary*) is an abstract data type that represents an *unordered collection of key–value pairs with no duplicate keys*. Each key maps to exactly one value. Think of a real-world dictionary: each word (key) has exactly one definition (value).\n\n**Example:**\n\n$$\\{\\langle A,1\\rangle, \\langle C,3\\rangle, \\langle B,2\\rangle\\} \\xrightarrow{\\text{add}(5,c)} \\{\\langle A,1\\rangle, \\langle C,3\\rangle, \\langle B,2\\rangle, \\langle 5,c\\rangle\\}$$\n\nThe main Map ADT operations are:\n\n- **put(k, v):** Add the key–value pair $\\langle k, v\\rangle$. If key $k$ already exists, replace the old value with $v$.\n- **get(k):** Return the value associated with key $k$, or null if not found.\n- **remove(k):** Remove the entry with key $k$.\n\n**Important:** A map stores at most one value per key. In Java, a common interface looks like:\n\n```java\npublic interface Map<K, V> {\n    int size();\n    boolean isEmpty();\n    V get(K key);\n    V put(K key, V value);   // returns the old value (or null)\n    V remove(K key);\n    Iterable<K> keySet();\n    Iterable<V> values();\n    Iterable<Entry<K,V>> entrySet();\n}\n```\n\nNote: `keySet()` and `entrySet()` are useful because keys are unique (no ambiguity), while values need not be unique — there is no meaningful \"valueSet\".\n\n###### **1.1.3 Map Implementations and Trade-offs**\n\nThere are several ways to implement a map, each with different trade-offs:\n\n**Unsorted doubly linked list:**\n\nThe map entries are stored as nodes in a doubly linked list. To find a key, we scan the list linearly.\n\n<!-- DIAGRAM HERE -->\n\n- **get(k):** $O(n)$ worst case — must scan all entries\n- **put(k, v):** $O(n)$ worst case (need to check for duplicate key), or $O(1)$ if duplicates are allowed without checking\n- **remove(k):** $O(n)$ worst case; $O(1)$ if given a direct reference to the node (with back-pointers from entries to nodes)\n\n**Array (when keys are small integers):**\n\nIf keys are integers in the range $0$ to $n-1$, we can use an array of size $n$: `array[k] = v`.\n\n- **get(k):** $O(1)$ — direct index\n- **put(k, v):** $O(1)$ — direct assignment\n- **remove(k):** $O(1)$ — set to null\n\nIf the key range is large or keys are not integers, we use **hash functions** to map keys to indices (covered later in the course).\n\n**The fundamental trade-off** when representing an ordered map (sorted by keys):\n\n| Representation | Search | Insert/Delete |\n|:---|:---|:---|\n| Sorted array | $O(\\log n)$ (binary search) | $O(n)$ (shifting) |\n| Linked list | $O(n)$ (linear scan) | $O(1)$ (given reference) |\n| Balanced BST | $O(\\log n)$ | $O(\\log n)$ |\n\nToday's goal is to find data structures that achieve $O(\\log n)$ for all operations — the best of both worlds.\n\n##### **1.2 Trees**\n\n###### **1.2.1 Basic Tree Definitions**\n\nA **tree** is a connected acyclic undirected graph. When we designate one vertex as the **root**, we get a **rooted tree**, which we conventionally draw \"hanging\" from the root with edges directed downward.\n\n<!-- DIAGRAM HERE -->\n\nKey vocabulary for rooted trees:\n\n- **Root:** The unique node with no parent (in-degree zero).\n- **Leaf:** A node with no children (out-degree zero).\n- **Parent of $v$:** The node $u$ such that $u \\to v$ is an edge.\n- **Children of $u$:** All nodes $v$ such that $u \\to v$ is an edge.\n- **Ancestor of $v$:** Any node $u$ on the path from the root to $v$.\n- **Descendant of $u$:** Any node $v$ that $u$ is an ancestor of.\n- **Height of a tree:** The maximum length of a path from the root to any leaf.\n- **Size of a tree:** The total number of nodes.\n\n**Ordered trees:** In an **ordered tree**, the order of children of each node is fixed and significant. Two trees with the same nodes but different child orderings are considered distinct.\n\n**$n$-ary trees:** An **$n$-ary tree** is an ordered rooted tree in which every node has *at most $n$ children*. Special cases:\n\n- $n = 2$: **Binary tree** (most common in this course)\n- $n = 3$: **Ternary tree**\n- $n = 1$: A linear chain (essentially a linked list)\n\n###### **1.2.2 Binary Tree Representations**\n\n**Linked representation:** Each node stores its data plus pointers to its left child, right child, and parent.\n\n<!-- DIAGRAM HERE -->\n\n**Array representation (level-order numbering):** We can map a binary tree to an array by numbering nodes level by level, left to right, starting from the root at index 0:\n\n$$\\text{root} = 0 \\qquad \\text{parent}(i) = \\left\\lfloor \\frac{i-1}{2} \\right\\rfloor \\qquad \\text{left}(i) = 2i+1 \\qquad \\text{right}(i) = 2i+2$$\n\nThis works perfectly for *complete* trees (where all levels are full except possibly the last). For sparse trees, many array slots are wasted. For example, a tree with 8 actual nodes arranged in an unbalanced way might require an array of size much larger than 8.\n\n**Example:** A tree with nodes labeled A through I at indices 0, 1, 2, 3, 5, 6, 7, 8, 11 looks like:\n\n```\nIndex: [ 0 | 1 | 2 | 3 | - | 4 | 5 | 6 | 7 | - | - | 8 | - | - | - ]\nData:  [ A | B | C | D | - | E | F | G | H | - | - | I | - | - | - ]\n```\n\n(Dashes indicate empty slots where tree nodes do not exist.)\n\n###### **1.2.3 Tree Traversal Orders**\n\nTo visit all nodes of a binary tree, we choose an order. Three standard orders exist:\n\n1. **Pre-order:** Visit the current node, then recursively the left subtree, then the right subtree. *(Root → Left → Right)*\n2. **In-order:** Recursively visit the left subtree, then the current node, then the right subtree. *(Left → Root → Right)* — For BSTs, this visits nodes in sorted key order.\n3. **Post-order:** Recursively visit the left subtree, then the right subtree, then the current node. *(Left → Right → Root)*\n\n**Example:** For the tree with root A (left subtree: B→D, B→C→{H,F}; right subtree: E→{G, I→J}):\n\n- **Pre-order:** A, B, D, C, H, F, E, G, I, J\n- **In-order:** D, B, H, C, F, A, G, E, I, J\n- **Post-order:** D, H, F, C, B, G, J, I, E, A\n\n##### **1.3 Binary Search Trees**\n\n###### **1.3.1 The BST Property**\n\nA **Binary Search Tree (BST)** is a binary tree that satisfies the **BST property**:\n\n> For every node $x$: if $y$ is in the *left* subtree of $x$, then $y.\\text{key} \\le x.\\text{key}$; if $z$ is in the *right* subtree of $x$, then $x.\\text{key} \\le z.\\text{key}$.\n\n<!-- DIAGRAM HERE -->\n\nThis property makes BSTs ideal for implementing ordered maps: in-order traversal visits all keys in sorted order.\n\n**Operations supported by a BST:**\n\n- `search(k)` — find the value for key $k$\n- `insert(k, v)` — insert a key–value pair\n- `remove(k)` — remove the entry with key $k$\n- `findMin()` / `findMax()` — find the entry with the smallest/largest key\n\n###### **1.3.2 Search**\n\nTo search for key $k$, start at the root and follow the BST property:\n\n```\nTREE-SEARCH(x, k):\n    if x == NIL or k == x.key\n        return x\n    if k < x.key\n        return TREE-SEARCH(x.left, k)\n    else\n        return TREE-SEARCH(x.right, k)\n```\n\nAn equivalent iterative version avoids recursion:\n\n```\nITERATIVE-TREE-SEARCH(x, k):\n    while x ≠ NIL and k ≠ x.key\n        if k < x.key\n            x = x.left\n        else\n            x = x.right\n    return x\n```\n\n**Time complexity:** $O(h)$ where $h$ is the height of the tree. Best case $O(1)$ (key at root).\n\n###### **1.3.3 Finding Minimum and Maximum**\n\nThe minimum is always at the leftmost node; the maximum at the rightmost:\n\n```\nTREE-MINIMUM(x):           TREE-MAXIMUM(x):\n    while x.left ≠ NIL         while x.right ≠ NIL\n        x = x.left                 x = x.right\n    return x                   return x\n```\n\nBoth run in $O(h)$ time.\n\n###### **1.3.4 Finding the Successor**\n\nThe **in-order successor** of node $x$ is the node with the smallest key greater than $x.\\text{key}$. It is needed during deletion.\n\n```\nTREE-SUCCESSOR(x):\n    if x.right ≠ NIL\n        return TREE-MINIMUM(x.right)   // leftmost in right subtree\n    else\n        y = x.parent\n        while y ≠ NIL and x == y.right\n            x = y\n            y = y.parent\n        return y\n```\n\n**Intuition:** If $x$ has a right subtree, its successor is the minimum of that subtree. Otherwise, we climb the tree until we find an ancestor that is a left child of its parent — that parent is the successor.\n\n###### **1.3.5 Insertion**\n\nTo insert key $k$ with value $v$: search for $k$ to find where it would go, then attach a new node there.\n\n<!-- DIAGRAM HERE -->\n\n**Time complexity:** $O(h)$ — we trace a path from root to the insertion point.\n\n###### **1.3.6 Deletion**\n\nDeletion has three cases depending on the node's children:\n\n1. **Leaf node:** Simply remove it.\n2. **One child:** Replace the node with its single child (splice it out).\n3. **Two children:** Replace the node's key/value with its *in-order successor* (or predecessor), then delete that successor (which has at most one child, since it's the leftmost node of the right subtree).\n\n<!-- DIAGRAM HERE -->\n\n**Time complexity:** $O(h)$ for all cases.\n\n###### **1.3.7 Height and the Problem of Imbalance**\n\nAll BST operations run in $O(h)$. The question is: what is $h$ in practice?\n\n- If keys are inserted in a *random* order (e.g., 5, 3, 8, 1, 6, 9, 2), the resulting tree is roughly balanced with $h \\approx \\log n$.\n- If keys are inserted in *sorted order* (e.g., 1, 2, 3, 4, 5, 6, 7), each new node becomes the rightmost child, creating a chain with $h = n - 1$ (essentially a linked list).\n\nIn the worst case, a BST degrades to $O(n)$ per operation. To fix this, we use **self-balancing BSTs**.\n\n##### **1.4 AVL Trees**\n\n###### **1.4.1 Motivation and Invariant**\n\n**AVL trees** (named after Adelson-Velsky and Landis, 1962) are self-balancing BSTs. They maintain the following **balance invariant**:\n\n> For every node, the heights of its left and right subtrees differ by *at most 1*.\n\nThis invariant guarantees that the height of an AVL tree with $n$ nodes is $O(\\log n)$, so all operations remain $O(\\log n)$.\n\nThe **balance factor** of a node is defined as:\n$$\\text{bf}(x) = h(\\text{left}(x)) - h(\\text{right}(x))$$\n\nAn AVL tree requires $|\\text{bf}(x)| \\le 1$ for every node $x$ (where the height of an empty subtree is $-1$).\n\n###### **1.4.2 Rotations**\n\nWhen an insertion or deletion violates the AVL invariant, we restore it using **rotations**. A rotation is a local restructuring of the tree that changes the height without disturbing the BST property.\n\n**Right rotation at node $y$** (and its inverse, left rotation at $x$):\n\n<!-- DIAGRAM HERE -->\n\n```\nRIGHT-ROTATE(T, y):\n    x = y.left\n    β = x.right\n    x.right = y\n    y.left = β\n    update heights of y, then x\n    return x   // new root of this subtree\n```\n\nA right rotation is used when the left subtree is too tall (balance factor $+2$). A left rotation is the mirror image.\n\n**Height effects of rotations:**\n\nIf subtree heights are $h_\\alpha$, $h_\\beta$, $h_\\gamma$ (left to right):\n\n- Before right rotation: height of $y$'s subtree = $\\max(h_\\alpha, h_\\beta) + 2$\n- After right rotation: height of $x$'s subtree = $\\max(h_\\alpha, h_\\beta) + 1$\n\nThe rotation reduces the height by 1, restoring balance.\n\n###### **1.4.3 The Four Imbalance Cases**\n\nAfter an insertion, at most one node may become unbalanced (the lowest such ancestor of the inserted node). There are four cases:\n\n<!-- DIAGRAM HERE -->\n\n| Case | Condition | Fix |\n|:---|:---|:---|\n| **Left-Left (LL)** | Left child's left subtree is too tall | Single right rotation at the unbalanced node |\n| **Left-Right (LR)** | Left child's right subtree is too tall | Left rotation at left child, then right rotation at node |\n| **Right-Right (RR)** | Right child's right subtree is too tall | Single left rotation at the unbalanced node |\n| **Right-Left (RL)** | Right child's left subtree is too tall | Right rotation at right child, then left rotation at node |\n\n**Insert and rebalance:** Insert as in a regular BST, then walk back up to the root, updating heights and applying rotations where needed.\n\n###### **1.4.4 AVL Tree Height Bound**\n\nLet $n_{\\min}(h)$ = minimum number of nodes in an AVL tree of height $h$. Then:\n\n$$n_{\\min}(h) = n_{\\min}(h-1) + n_{\\min}(h-2) + 1$$\n\nwith $n_{\\min}(-1) = 0$ (empty tree) and $n_{\\min}(0) = 1$ (single node).\n\nThis recurrence resembles Fibonacci numbers: $n_{\\min}(h) \\ge 2 \\cdot n_{\\min}(h-2) + 1$, which gives $n_{\\min}(h) \\ge 2^{h/2}$. Therefore $n \\ge 2^{h/2}$, so $h \\le 2\\log_2 n = O(\\log n)$.\n\n##### **1.5 Red-Black Trees**\n\n###### **1.5.1 Motivation**\n\n**Red-Black trees** are another type of self-balancing BST. Like AVL trees, they guarantee $O(\\log n)$ height, but they achieve balance through a different invariant that requires fewer rotations in practice during insertions and deletions (though not asymptotically fewer).\n\nIn a red-black tree, each node is **colored** either red or black. The coloring encodes height constraints without explicitly storing heights.\n\n###### **1.5.2 Red-Black Tree Invariants**\n\nA valid red-black tree must satisfy *all five* of the following invariants simultaneously:\n\n1. **Color:** Every node is either red or black.\n2. **Root:** The root is black.\n3. **Leaves:** All leaves (NIL sentinels representing empty subtrees) are black.\n4. **Red constraint:** If a node is red, both its children are black. (*No two consecutive red nodes on any path.*)\n5. **Black-height:** For every node, *every path* from that node to any leaf contains the same number of black nodes.\n\n<!-- DIAGRAM HERE -->\n\nThe **black-height** $\\text{bh}(x)$ of a node $x$ is the number of black nodes on any path from $x$ down to a leaf (not counting $x$ itself).\n\n###### **1.5.3 Why Red-Black Trees Have $O(\\log n)$ Height**\n\n**Lemma:** A red-black tree with $n$ internal nodes has height at most $2\\log_2(n+1)$.\n\n**Proof sketch:**\n\n1. First, show that every subtree rooted at $x$ contains at least $2^{\\text{bh}(x)} - 1$ internal nodes. (By induction: a leaf has $2^0 - 1 = 0$ internal nodes; an internal node's two children each have black-height $\\ge \\text{bh}(x) - 1$, so the subtree has $\\ge 2(2^{\\text{bh}(x)-1} - 1) + 1 = 2^{\\text{bh}(x)} - 1$ nodes.)\n2. Invariant 4 (no two consecutive red nodes) means that at least half of the nodes on any root-to-leaf path are black. Therefore $\\text{bh}(\\text{root}) \\ge h/2$.\n3. Combining: $n \\ge 2^{h/2} - 1$, which gives $h \\le 2\\log_2(n+1)$.\n\n###### **1.5.4 Red-Black Tree Insertion**\n\nInsertion proceeds in two phases:\n\n**Phase 1:** Insert as in a regular BST and color the new node **red**.\n\n**Phase 2:** Fix any violation of invariant 4 (a red node with a red parent). There are three cases (shown for the \"left\" orientation; right is symmetric):\n\n- **Case 1 — Uncle is red:** Recolor parent and uncle to black, grandparent to red. Move the violation up to the grandparent.\n- **Case 2 — Uncle is black, node is a right child:** Left-rotate the parent. This reduces to Case 3.\n- **Case 3 — Uncle is black, node is a left child:** Right-rotate the grandparent and swap colors of parent and grandparent.\n\nAfter fixing, re-color the root to black (invariant 2).\n\n###### **1.5.5 Red-Black Tree Deletion**\n\nDeletion is more complex. After removing a node, we may need to restore the black-height property. There are four cases for fixing \"double-black\" violations. We omit the full details here; see Cormen et al. (2022, §13.4) for the complete algorithm.\n\n###### **1.5.6 AVL vs Red-Black Trees**\n\n| Property | AVL Tree | Red-Black Tree |\n|:---|:---|:---|\n| **Height bound** | $\\le 1.44\\log_2(n+1)$ | $\\le 2\\log_2(n+1)$ |\n| **Balance** | Stricter | More relaxed |\n| **Rotations on insert** | $\\le 2$ | $\\le 2$ |\n| **Rotations on delete** | $O(\\log n)$ | $\\le 3$ |\n| **Best for** | Many lookups | Many insertions/deletions |\n\nAVL trees are more strictly balanced (shorter height) so lookups are slightly faster. Red-black trees require fewer rotations during deletions (at most 3 vs $O(\\log n)$), making them preferable when modifications are frequent. Both guarantee $O(\\log n)$ for all operations.\n\n##### **1.6 $d$-ary Trees in Arrays**\n\nFor a **$d$-ary tree** (each node has at most $d$ children) stored in an array using level-order numbering:\n\n$$\\text{parent}_d(i) = \\left\\lfloor \\frac{i-1}{d} \\right\\rfloor \\qquad \\text{child}_{d,k}(i) = d \\cdot i + k \\quad (1 \\le k \\le d)$$\n\n**For binary trees ($d = 2$):** $\\text{parent}(i) = \\lfloor(i-1)/2\\rfloor$, $\\text{left}(i) = 2i+1$, $\\text{right}(i) = 2i+2$. This is the standard heap layout.\n\n**Total nodes in a perfect $d$-ary tree of height $h$:**\n\n$$N(d, h) = \\frac{d^{h+1} - 1}{d - 1} = 1 + d + d^2 + \\cdots + d^h$$\n\n***\n\n#### **2. Definitions**\n\n*   **Set (ADT):** An abstract data type representing an unordered collection of values without duplicates, supporting add, remove, and contains operations.\n*   **Map (ADT):** An abstract data type (also called a dictionary) representing an unordered collection of key–value pairs with no duplicate keys; supports put, get, and remove.\n*   **Tree:** A connected acyclic undirected graph.\n*   **Rooted Tree:** A tree with one designated vertex called the root.\n*   **Ordered Tree:** A rooted tree where the order of children of each node is fixed.\n*   **$n$-ary Tree:** An ordered rooted tree where every node has at most $n$ children.\n*   **Binary Tree:** An $n$-ary tree with $n = 2$.\n*   **Height (of a tree):** The maximum length of a path from the root to any leaf.\n*   **Level-order Numbering:** A way to index tree nodes level by level (left to right), placing the root at index 0, enabling array storage with $O(1)$ parent/child index formulas.\n*   **Pre-order Traversal:** Visit node, then left subtree, then right subtree.\n*   **In-order Traversal:** Visit left subtree, then node, then right subtree. For BSTs, produces keys in sorted order.\n*   **Post-order Traversal:** Visit left subtree, then right subtree, then node.\n*   **Binary Search Tree (BST):** A binary tree satisfying the BST property: for every node $x$, all keys in its left subtree are $\\le x.\\text{key}$ and all keys in its right subtree are $\\ge x.\\text{key}$.\n*   **BST Property:** For every node $x$: $y.\\text{key} \\le x.\\text{key}$ for all $y$ in the left subtree, and $x.\\text{key} \\le z.\\text{key}$ for all $z$ in the right subtree.\n*   **In-order Successor:** The node with the smallest key greater than a given node's key; found as the minimum of the right subtree (or the nearest ancestor for which the given node is in the left subtree).\n*   **AVL Tree:** A self-balancing BST (Adelson-Velsky and Landis) maintaining that for every node, the heights of its two subtrees differ by at most 1.\n*   **Balance Factor:** $\\text{bf}(x) = h(\\text{left}(x)) - h(\\text{right}(x))$; must satisfy $|\\text{bf}(x)| \\le 1$ in an AVL tree.\n*   **Rotation:** A local tree restructuring operation (left or right) that changes the height relationship between a node and its child while preserving the BST property.\n*   **Red-Black Tree:** A self-balancing BST where each node is colored red or black, satisfying five invariants that guarantee height $\\le 2\\log_2(n+1)$.\n*   **Black-height:** The number of black nodes on any path from a node down to a leaf (not counting the node itself); must be the same for all paths in a red-black tree.\n*   **$d$-ary Tree:** An ordered rooted tree where every node has at most $d$ children.\n\n***\n\n#### **3. Formulas**\n\n*   **Level-order (binary tree) — root index:** $\\text{root} = 0$\n*   **Level-order (binary tree) — parent:** $\\text{parent}(i) = \\lfloor(i-1)/2\\rfloor$\n*   **Level-order (binary tree) — left child:** $\\text{left}(i) = 2i + 1$\n*   **Level-order (binary tree) — right child:** $\\text{right}(i) = 2i + 2$\n*   **Level-order ($d$-ary tree) — parent:** $\\text{parent}_d(i) = \\lfloor(i-1)/d\\rfloor$\n*   **Level-order ($d$-ary tree) — $k$-th child:** $\\text{child}_{d,k}(i) = d \\cdot i + k \\quad (1 \\le k \\le d)$\n*   **Total nodes in a perfect $d$-ary tree of height $h$:** $N(d, h) = \\dfrac{d^{h+1} - 1}{d - 1}$\n*   **BST / AVL / Red-Black — all operations:** $O(h)$, where $h$ is the height\n*   **AVL tree height bound:** $h \\le 2\\log_2 n$, i.e., $h = O(\\log n)$\n*   **AVL minimum nodes recurrence:** $n_{\\min}(h) = n_{\\min}(h-1) + n_{\\min}(h-2) + 1$, with $n_{\\min}(-1) = 0$, $n_{\\min}(0) = 1$\n*   **AVL minimum nodes lower bound:** $n_{\\min}(h) \\ge 2^{h/2}$\n*   **Red-Black tree height bound:** $h \\le 2\\log_2(n + 1)$\n*   **Red-Black tree minimum internal nodes:** A subtree rooted at $x$ has $\\ge 2^{\\text{bh}(x)} - 1$ internal nodes\n\n***\n\n#### **4. Examples**\n\n##### **4.1. Build a BST by Insertion** (Lecture 6, Task 1)\n\nInsert the following keys into an initially empty binary search tree in the given order and draw the resulting tree:\n\n$$50, 30, 70, 20, 40, 60, 80$$\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** To insert into a BST, compare the new key to the current node and go left if smaller, right if larger. Insert as a new leaf at the first empty spot.\n\n**Step-by-step insertions:**\n\n1.  **Insert 50:** Tree is empty; 50 becomes the root.\n2.  **Insert 30:** $30 < 50$ → go left. Left of 50 is empty → place 30 there.\n3.  **Insert 70:** $70 > 50$ → go right. Right of 50 is empty → place 70.\n4.  **Insert 20:** $20 < 50$ → left to 30; $20 < 30$ → go left. Empty → place 20.\n5.  **Insert 40:** $40 < 50$ → left to 30; $40 > 30$ → go right. Empty → place 40.\n6.  **Insert 60:** $60 > 50$ → right to 70; $60 < 70$ → go left. Empty → place 60.\n7.  **Insert 80:** $80 > 50$ → right to 70; $80 > 70$ → go right. Empty → place 80.\n\n**Resulting BST:**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'igraph' was built under R version 4.5.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'igraph'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    decompose, spectrum\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:base':\n\n    union\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `graph()` was deprecated in igraph 2.1.0.\nℹ Please use `make_graph()` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](6_files/figure-html/unnamed-chunk-1-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n**Answer:** The root is 50. Its left subtree has root 30 (children 20, 40) and right subtree has root 70 (children 60, 80). The tree is perfectly balanced with height 2.\n\n</details>\n\n\n##### **4.2. Build an AVL Tree by Insertion** (Lecture 6, Task 2)\n\nBuild an AVL tree by inserting the following keys into an initially empty tree in the given order:\n\n$$1, 2, 3, 8, 41, 12, 19, 31, 38$$\n\nShow the tree after each rotation.\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** After each insertion, check the balance factors on the path from the inserted node to the root. Apply single or double rotations to restore $|\\text{bf}| \\le 1$.\n\n**Convention:** $h(\\text{empty}) = -1$, $h(\\text{single node}) = 0$.\n\n**Step 1 — Insert 1:** Tree: just node 1. Balanced.\n\n**Step 2 — Insert 2:** $2 > 1$, goes right of 1. $\\text{bf}(1) = -1$. Still balanced.\n\n**Step 3 — Insert 3:** $3 > 1$ → right; $3 > 2$ → right of 2. $\\text{bf}(1) = -2$ → **RR case**. Apply left rotation at 1:\n\n```\nBefore:  1          After:   2\n          \\                 / \\\n           2               1   3\n            \\\n             3\n```\n\nRotations so far: 1.\n\n**Step 4 — Insert 8:** $8 > 2$ → right to 3; $8 > 3$ → right of 3. $\\text{bf}(3) = -1$, $\\text{bf}(2) = -1$. Balanced.\n\n**Step 5 — Insert 41:** $41 > 2$ → right; $41 > 3$ → right; $41 > 8$ → right of 8. $\\text{bf}(3) = -2$ → **RR case**. Left rotation at 3:\n\n```\nBefore: 2            After:  2\n       / \\                  / \\\n      1   3                1   8\n           \\              / \\\n            8            3  41\n             \\\n             41\n```\n\nRotations so far: 2.\n\n**Step 6 — Insert 12:** $12 > 8$, $12 < 41$ → left of 41. $\\text{bf}(41) = 1$, $\\text{bf}(8) = -1$. Balanced.\n\n**Step 7 — Insert 19:** $19 > 8$, $19 < 41$, $19 > 12$ → right of 12. $\\text{bf}(41) = 2$, $12$ is its left child and $19$ is right child of $12$ → **LR case** (at node 41). First left rotation at 12, then right rotation at 41:\n\n```\nAfter LR at 41:  2\n                / \\\n               1   8\n              / \\\n             3  19\n            / \\\n           12  41\n```\n\nRotations so far: 4.\n\n**Step 8 — Insert 31:** $31 > 19$ → right of 19. Balanced (bf at 19 = -1, others still fine with minor adjustments).\n\n**Step 9 — Insert 38:** Insert 38, which causes another LR rotation, ultimately producing the final balanced AVL tree.\n\n**Final tree shape** (balanced AVL tree, height 3):\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](6_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=576}\n:::\n:::\n\n\n**Total rotations performed:** 4 (two single rotations and one double rotation counted as two).\n\n**Answer:** The insertions require 4 rotations total. The final AVL tree is balanced with height 3.\n\n</details>\n\n##### **4.3. Build a Red-Black Tree by Insertion** (Lecture 6, Task 3)\n\nBuild a red-black tree by inserting the following keys into an initially empty tree in the given order:\n\n$$1, 2, 3, 8, 41, 12, 19, 31, 38$$\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** Each new node is inserted as red. After insertion, fix any red–red violation by applying Case 1 (recolor), Case 2 (rotation to convert to Case 3), or Case 3 (rotation + recolor). Always re-blacken the root.\n\n**Color notation:** B = black, R = red.\n\n**Insert 1:** Node 1 becomes root → color black. Tree: **1(B)**.\n\n**Insert 2:** $2 > 1$, right child of 1. Color red. No red–red violation. Tree: 1(B) → right: 2(R).\n\n**Insert 3:** $3 > 1 > 2$, right child of 2(R). Now 2(R)–3(R) is a violation. Uncle of 3 is NIL (black). This is Case 3 (right-right): left rotation at 1, then recolor.\n\n```\nAfter rotation + recolor:  2(B)\n                          / \\\n                        1(R) 3(R)\n```\n\n**Insert 8:** Right child of 3(R). Uncle of 8 is 1(R) → **Case 1** (both uncle and parent are red): recolor 3 → B, 1 → B (uncle), and 2 → R; then re-blacken root 2 → B.\n\n```\nTree:  2(B)\n      / \\\n   1(B) 3(B)\n          \\\n          8(R)\n```\n\n**Insert 41:** Right child of 8(R). Uncle (3's left child) is NIL (black). **Case 3**: left rotation at 3.\n\n```\nAfter:  2(B)\n       / \\\n     1(B) 8(B)\n          / \\\n        3(R) 41(R)\n```\n\n**Insert 12:** $12 < 41$, left child of 41(R). Uncle of 12 is 3(R) → **Case 1**: recolor 41 → B, 3 → B, 8 → R, then re-blacken 2(B) (2 is root, stays black). Now 2(B)–8(R) is fine since 2 is black.\n\n```\nTree:  2(B)\n      / \\\n    1(B) 8(R)\n         / \\\n       3(B) 41(B)\n            /\n          12(R)\n```\n\n**Insert 19:** Right of 12(R). Uncle of 19 is NIL → **Case 2** (node is right child): left rotate at 12 → converts to Case 3. Then right rotate at 41, recolor.\n\n**Insert 31:** Continue inserting and fixing violations following the same three-case procedure.\n\n**Insert 38:** Final insertion may require rotations and recolorings to maintain all five invariants.\n\n**Final red-black tree** (one valid result after inserting all 9 keys):\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](6_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=768}\n:::\n:::\n\n\n**Answer:** The tree is built by applying recolorings and rotations after each insertion to maintain the five red-black invariants. The resulting tree has height $\\le 4$ for 9 nodes, satisfying the $2\\log_2(10) \\approx 6.6$ bound.\n\n</details>\n\n##### **4.4. Delete from a Red-Black Tree** (Lecture 6, Task 4)\n\nGiven the red-black tree below, delete the keys in order: $8, 12, 19, 31, 38, 41$.\n\nThe initial tree has: root 38 (Black), left child 19 (Red), right child 41 (Black). Node 19 has left child 12 (Black) and right child 31 (Black). Node 12 has left child 8 (Red).\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** Deletion from a red-black tree follows BST deletion, then fixes any \"double-black\" violations using one of four cases. For brevity, we trace the key cases.\n\n**Initial tree:**\n```\n        38(B)\n       /     \\\n     19(R)   41(B)\n    /    \\\n  12(B)  31(B)\n  /\n8(R)\n```\n\n**Delete 8 (red leaf):** Simply remove it. No violation occurs — removing a red node does not change any black-heights.\n```\n        38(B)\n       /     \\\n     19(R)   41(B)\n    /    \\\n  12(B)  31(B)\n```\n\n**Delete 12 (black leaf):** Removing a black node creates a \"double-black\" situation. Node 12's sibling is 31(B) with no red children → **Case 2**: recolor 31 → Red, push double-black up to 19(R).\nSince 19 is red, re-color 19 → Black to absorb the double-black.\n```\n        38(B)\n       /     \\\n     19(B)   41(B)\n        \\\n        31(R)\n```\n\n**Delete 19 (black, one child 31(R)):** Replace 19 with its right child 31, color it black.\n```\n    38(B)\n   /    \\\n 31(B)  41(B)\n```\n\n**Delete 31 (black leaf):** Double-black at 31's position. Sibling is 41(B) with no red children, parent 38(B) → **Case 2**: recolor 41 → Red, push double-black up to 38. Since 38 is the root, simply color root black (double-black absorbed).\n```\n   38(B)\n      \\\n      41(R)\n```\n\n**Delete 38 (black root, right child 41(R)):** Replace 38 with 41, color 41 black.\n```\n   41(B)\n```\n\n**Delete 41:** Last remaining node. Remove it. Tree is empty.\n\n**Answer:** After deleting all six keys in order, the tree becomes empty. Key operations used: leaf removal of red nodes (trivial), double-black fix by recoloring siblings, and replacement of black nodes by their red children.\n\n</details>\n\n##### **4.5. BST Traversals** (Lecture 6, Task 5)\n\nGive the in-order, pre-order, and post-order traversals of the following BST:\n\nRoot: 20. Left child: 10 (with children 5 and 15). Right child: 30 (with children 25 and 35).\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** Apply the traversal definition recursively. For BSTs, in-order always gives sorted order.\n\n**Tree structure:**\n\n```\n        20\n       /  \\\n     10    30\n    /  \\  /  \\\n   5   15 25  35\n```\n\n1.  **In-order (Left → Root → Right):**\n    *   Visit left subtree of 20: [5, 10, 15]\n    *   Visit root: 20\n    *   Visit right subtree of 20: [25, 30, 35]\n    *   **Result:** 5, 10, 15, 20, 25, 30, 35 *(sorted order — always true for BST in-order)*\n2.  **Pre-order (Root → Left → Right):**\n    *   Visit 20, then left subtree [10, 5, 15], then right subtree [30, 25, 35]\n    *   **Result:** 20, 10, 5, 15, 30, 25, 35\n3.  **Post-order (Left → Right → Root):**\n    *   Left subtree [5, 15, 10], right subtree [25, 35, 30], then root\n    *   **Result:** 5, 15, 10, 25, 35, 30, 20\n\n**Answer:**\n\n- In-order: 5, 10, 15, 20, 25, 30, 35\n- Pre-order: 20, 10, 5, 15, 30, 25, 35\n- Post-order: 5, 15, 10, 25, 35, 30, 20\n\n</details>\n\n##### **4.6. Maximum and Minimum Node Count for a Binary Tree of Height $h$** (Lecture 6, Task 6)\n\nWhat is the maximum number of nodes in a binary tree of height $h$? What is the minimum? Justify briefly.\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** Think about what configurations of nodes are most/least efficient.\n\n**Maximum nodes:**\n\nA binary tree of height $h$ is maximized when it is a *perfect binary tree* — every level is completely full. Level $k$ (counting from 0) has $2^k$ nodes. Summing all levels:\n\n$$N_{\\max}(h) = \\sum_{k=0}^{h} 2^k = 2^{h+1} - 1$$\n\nFor example, a perfect binary tree of height 2 has $2^3 - 1 = 7$ nodes.\n\n**Minimum nodes:**\n\nThe minimum occurs when the tree has exactly *one leaf at the deepest level* — a chain or path of length $h$. At each depth from 0 to $h-1$, there is exactly one internal node with one child. At depth $h$, there is one leaf:\n\n$$N_{\\min}(h) = h + 1$$\n\nFor example, the chain $1 \\to 2 \\to 3$ has height 2 and $3 = 2+1$ nodes.\n\n**Answer:**\n\n- Maximum: $2^{h+1} - 1$ nodes (perfect binary tree)\n- Minimum: $h + 1$ nodes (a chain / path)\n\n</details>\n\n##### **4.7. Tree Predecessor Pseudocode** (Lecture 6, Task 7)\n\nWrite pseudocode for `TREE-PREDECESSOR(x)` (the predecessor of $x$ in in-order traversal). What is its time complexity?\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** The predecessor is the mirror image of the successor. Instead of going right, we go left; instead of looking for the minimum, we look for the maximum.\n\nThe **in-order predecessor** of $x$ is the node with the largest key *smaller* than $x.\\text{key}$.\n\n```\nTREE-PREDECESSOR(x):\n    if x.left ≠ NIL\n        return TREE-MAXIMUM(x.left)   // rightmost node in left subtree\n    else\n        // Find the lowest ancestor of x whose right child is an ancestor of x\n        y = x.parent\n        while y ≠ NIL and x == y.left\n            x = y\n            y = y.parent\n        return y\n```\n\n**Explanation of the two cases:**\n\n1. **If $x$ has a left subtree:** The predecessor is the *maximum* of that subtree (rightmost node). This is symmetric to finding the successor's minimum in the right subtree.\n2. **If $x$ has no left subtree:** We climb the tree looking for the first ancestor that we entered from the *right* side. That ancestor has a key smaller than $x.\\text{key}$, and it's the closest such ancestor.\n\n**Time complexity:** $O(h)$, where $h$ is the height of the tree. In the worst case, we walk from a leaf all the way up to the root.\n\n**Answer:** The pseudocode above correctly computes the predecessor. Time complexity is $O(h)$.\n\n</details>\n\n##### **4.8. Prove AVL Tree Height is $O(\\log n)$** (Lecture 6, Task 8)\n\nProve that the height of an AVL tree with $n$ nodes is $O(\\log n)$.\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** Instead of bounding height from above directly, we bound the *minimum number of nodes* needed for a given height from below, then invert.\n\n**Define:** Let $n_{\\min}(h)$ = minimum number of nodes in an AVL tree of height $h$.\n\n**Base cases:**\n\n- $n_{\\min}(-1) = 0$ (empty tree has height $-1$ by convention)\n- $n_{\\min}(0) = 1$ (a single node)\n\n**Recurrence:** An AVL tree of height $h$ must have a root, plus:\n\n- One subtree of height $h-1$ (to achieve height $h$)\n- One subtree of height $\\ge h-2$ (by the AVL balance property, heights can differ by at most 1)\n\nThe *minimum* is achieved when one subtree has height $h-1$ and the other has height $h-2$:\n\n$$n_{\\min}(h) = 1 + n_{\\min}(h-1) + n_{\\min}(h-2)$$\n\n**First few values:**\n\n| $h$ | $n_{\\min}(h)$ |\n|:---:|:---:|\n| -1 | 0 |\n| 0 | 1 |\n| 1 | 2 |\n| 2 | 4 |\n| 3 | 7 |\n| 4 | 12 |\n\n**Lower bound:** We claim $n_{\\min}(h) \\ge 2^{h/2}$. Proof by strong induction:\n\n- Base: $n_{\\min}(0) = 1 \\ge 2^0 = 1$ ✓, $n_{\\min}(1) = 2 \\ge 2^{1/2} \\approx 1.41$ ✓\n- Step: $n_{\\min}(h) = 1 + n_{\\min}(h-1) + n_{\\min}(h-2) \\ge n_{\\min}(h-2) + n_{\\min}(h-2) = 2 \\cdot n_{\\min}(h-2) \\ge 2 \\cdot 2^{(h-2)/2} = 2^{h/2}$.\n\n**Conclusion:** Any AVL tree with $n$ nodes and height $h$ satisfies:\n\n$$n \\ge n_{\\min}(h) \\ge 2^{h/2}$$\n\nTaking logarithms: $h \\le 2\\log_2 n$, so $h = O(\\log n)$.\n\n**Answer:** The height of an AVL tree with $n$ nodes is at most $2\\log_2 n = O(\\log n)$.\n\n</details>\n\n##### **4.9. Prove Red-Black Tree Height is at most $2\\log_2(n+1)$** (Lecture 6, Task 9)\n\nProve that the height of a red-black tree with $n$ internal nodes is at most $2\\log_2(n+1)$ (Cormen et al. 2022, Lemma 13.1).\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** Use the black-height and the constraint on red nodes to derive the bound.\n\n**Lemma:** A subtree rooted at any node $x$ contains at least $2^{\\text{bh}(x)} - 1$ internal nodes.\n\n*Proof by induction on height of $x$:*\n\n- **Base case:** If $x$ is a leaf (NIL), it has 0 internal nodes. $\\text{bh}(\\text{NIL}) = 0$, and $2^0 - 1 = 0$. ✓\n- **Inductive step:** If $x$ is an internal node with children $l$ and $r$:\n  - Each child has black-height $\\ge \\text{bh}(x) - 1$ (they may be red, contributing 0, but the black nodes below them satisfy the black-height of $x$ minus the contribution of $x$ itself if black).\n  - By induction, each child's subtree has $\\ge 2^{\\text{bh}(x)-1} - 1$ internal nodes.\n  - Total for $x$'s subtree: $1 + (2^{\\text{bh}(x)-1} - 1) + (2^{\\text{bh}(x)-1} - 1) = 2^{\\text{bh}(x)} - 1$.\n\n**Applying to the root:**\n\nLet $h$ = height of the tree and $\\text{bh}$ = black-height of the root.\n\nBy invariant 4 (no two consecutive red nodes), at least half of the nodes on any root-to-leaf path are black. Therefore:\n\n$$\\text{bh}(\\text{root}) \\ge h/2$$\n\nFrom the lemma:\n\n$$n \\ge 2^{\\text{bh}(\\text{root})} - 1 \\ge 2^{h/2} - 1$$\n\nSolving for $h$:\n\n$$n + 1 \\ge 2^{h/2} \\implies h/2 \\le \\log_2(n+1) \\implies h \\le 2\\log_2(n+1)$$\n\n**Answer:** The height of a red-black tree with $n$ internal nodes is at most $2\\log_2(n+1) = O(\\log n)$.\n\n</details>\n\n\n##### **4.10. Compare AVL and Red-Black Trees** (Lecture 6, Task 10)\n\nCompare AVL trees and red-black trees: when would you prefer one over the other?\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** Both structures guarantee $O(\\log n)$ operations, but they differ in their height constants and the cost of rebalancing.\n\n**Height comparison:**\n\n- AVL trees: height $\\le 1.44\\log_2(n+1)$ — strictly tighter bound\n- Red-black trees: height $\\le 2\\log_2(n+1)$ — up to ~39% taller\n\n**Rotation cost comparison:**\n\n- **Insert:** Both require $O(1)$ rotations ($\\le 2$ for AVL, $\\le 2$ for red-black)\n- **Delete:** AVL requires up to $O(\\log n)$ rotations; red-black requires at most **3 rotations**\n\n**Practical guidance:**\n\n| Scenario | Preferred structure |\n|:---|:---|\n| **Read-heavy workload** (many lookups, few modifications) | **AVL tree** — lower height means fewer comparisons per lookup |\n| **Write-heavy workload** (frequent insertions and deletions) | **Red-black tree** — fewer rotations on delete, lower overhead |\n| **Mixed workload** | Red-black tree (used in most standard library implementations, e.g., Java `TreeMap`, C++ `std::map`) |\n| **Memory-constrained** | AVL tree (only needs height per node; red-black needs 1-bit color per node) |\n\n**Real-world use:** Most language standard libraries (Java, C++, Linux kernel's interval trees) use red-black trees because writes are common in practice and the simpler deletion fix (at most 3 rotations) outweighs the slightly taller tree.\n\n**Answer:** Prefer **AVL trees** when lookups dominate; prefer **red-black trees** when insertions and deletions are frequent.\n\n</details>\n\n##### **4.11. Red-Black Tree Height — Recurrence for $B(h)$** (Problem Set 6, Task 1)\n\nLet $B(h)$ denote the minimum possible number of internal nodes in a red-black tree of black-height $h$ (black-height is the number of black nodes from root to leaf; empty tree has $\\text{bh} = 0$, singleton has $\\text{bh} = 1$).\n\n1. Derive a recurrence relation for $B(h)$ and compute $B(h)$ for $h = 0, 1, 2, 3, 4, 5, 6, 7, 8$.\n2. Derive a lower bound of the form $B(h) \\ge c \\cdot 2^{h/2}$.\n3. Give a big-$O$ upper bound on the height of a red-black tree as a function of the number of keys $n$.\n4. For $n = 10^6$, estimate the maximal possible height.\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** To minimize internal nodes at a given black-height, maximize the use of red nodes (which contribute to node count without increasing black-height).\n\n**Part 1 — Recurrence:**\n\nA red-black tree of black-height $h$ has a root (black) and two subtrees. To minimize node count, we want the smallest possible subtrees. Each subtree must have black-height $h-1$. To minimize further, we can insert one red node at the top of each subtree (maximizing \"structural efficiency\").\n\nThe minimum is achieved with two children that are themselves minimum red-black trees of black-height $h-1$, optionally with red roots:\n\n$$B(h) = 2B(h-1) + 1$$\n\nwith base case $B(0) = 0$ (empty tree, black-height 0) and considering black-height increments:\n\nMore precisely: a red-black tree of black-height $h \\ge 1$ has a black root, and each child subtree must have black-height $h-1$. But each child may be red (adding one node \"for free\" before black-height increases). The minimum subtree of black-height $h-1$ with a possible red root has $B(h-1)$ nodes (if the root is black) or we can add a red root on top of a $B(h-1)$ tree. The minimum structure:\n\n$$B(h) = 2B(h-1) + 1 \\quad \\text{with } B(0) = 0$$\n\n**Computed values:**\n\n| $h$ | $B(h) = 2B(h-1)+1$ |\n|:---:|:---:|\n| 0 | 0 |\n| 1 | 1 |\n| 2 | 3 |\n| 3 | 7 |\n| 4 | 15 |\n| 5 | 31 |\n| 6 | 63 |\n| 7 | 127 |\n| 8 | 255 |\n\nNote: $B(h) = 2^h - 1$.\n\n**Part 2 — Lower bound:**\n\nFrom the closed form $B(h) = 2^h - 1 \\ge 2^h / 2 = \\frac{1}{2} \\cdot 2^h$. Thus:\n\n$$B(h) \\ge \\frac{1}{2} \\cdot 2^h$$\n\nThis satisfies $B(h) \\ge c \\cdot 2^{h/2}$ as well (since $2^h \\ge 2^{h/2}$ for $h \\ge 0$), with $c = 1/2$.\n\n**Part 3 — Height bound:**\n\nA tree with $n$ internal nodes has black-height $\\text{bh}$ satisfying $n \\ge B(\\text{bh}) = 2^{\\text{bh}} - 1$, so $\\text{bh} \\le \\log_2(n+1)$.\n\nThe total height $h \\le 2 \\cdot \\text{bh}$ (since at most half the nodes on any path are red), giving:\n\n$$h \\le 2\\log_2(n+1) = O(\\log n)$$\n\n**Part 4 — Estimate for $n = 10^6$:**\n\n$$h \\le 2\\log_2(10^6 + 1) \\approx 2 \\times \\log_2(10^6) = 2 \\times 19.93 \\approx \\mathbf{40}$$\n\n**Answer:**\n1. $B(h) = 2B(h-1) + 1$ with $B(0) = 0$; closed form $B(h) = 2^h - 1$.\n2. $B(h) \\ge \\frac{1}{2} \\cdot 2^h$ (equivalently $B(h) \\ge 1 \\cdot 2^{h/2}$ for all $h \\ge 0$ since $2^h \\ge 2^{h/2}$).\n3. $h \\le 2\\log_2(n+1) = O(\\log n)$.\n4. For $n = 10^6$, maximum height $\\approx 40$.\n\n</details>\n\n##### **4.12. Build and Delete from a BST** (Problem Set 6, Task 2)\n\nConsider the BST built by inserting the following keys in that order:\n\n$$7, 3, 5, 10, 4, 2, 6, 8, 9, 12, 1, 11$$\n\n1. Draw the resulting BST.\n2. Delete keys $10, 9, 8, 7, 6$ in that order. For each deletion, state which case applies and draw the tree after each deletion. Specify whether you used the successor or predecessor when deleting a node with two children.\n3. List all possible keys that could be in the root after deleting $10, 9, 8, 7, 6$ in order (considering all choices of successor or predecessor).\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Part 1 — Build the BST:**\n\nInsert each key following BST rules (go left if smaller, right if larger):\n\n- **7:** root\n- **3:** $3 < 7$ → left of 7\n- **5:** $5 < 7$ → left; $5 > 3$ → right of 3\n- **10:** $10 > 7$ → right of 7\n- **4:** $4 < 7$ → left; $4 > 3$ → right; $4 < 5$ → left of 5\n- **2:** $2 < 7$ → left; $2 < 3$ → left of 3\n- **6:** $6 < 7$ → left; $6 > 3$ → right; $6 > 5$ → right of 5\n- **8:** $8 > 7$ → right; $8 < 10$ → left of 10\n- **9:** $9 > 7$ → right; $9 < 10$ → left; $9 > 8$ → right of 8\n- **12:** $12 > 7$ → right; $12 > 10$ → right of 10\n- **1:** ... → left of 2\n- **11:** $11 > 7$ → right; $11 > 10$ → right; $11 < 12$ → left of 12\n\n**Resulting BST:**\n```\n              7\n            /   \\\n           3    10\n          / \\   / \\\n         2   5 8  12\n        /   / \\ \\  /\n       1   4   6 9 11\n```\n\n**Part 2 — Deletions:**\n\n**Delete 10 (two children: 8 and 12):** Case — two children. Use **successor** (smallest in right subtree = 11). Replace 10 with 11; delete 11 from its original position (leaf).\n```\n              7\n            /   \\\n           3    11\n          / \\   / \\\n         2   5 8  12\n        /   / \\ \\\n       1   4   6 9\n```\n\n**Delete 9 (leaf):** Case — leaf. Simply remove.\n```\n              7\n            /   \\\n           3    11\n          / \\   / \\\n         2   5 8  12\n        /   / \\\n       1   4   6\n```\n\n**Delete 8 (leaf):** Case — leaf. Simply remove.\n```\n              7\n            /   \\\n           3    11\n          / \\     \\\n         2   5    12\n        /   / \\\n       1   4   6\n```\n\n**Delete 7 (two children: 3 and 11):** Case — two children. Use **successor** (smallest in right subtree = 11). But 11 has a right child 12. Replace 7's key with 11; remove 11, promoting 12.\n```\n              11\n            /    \\\n           3     12\n          / \\\n         2   5\n        /   / \\\n       1   4   6\n```\n\n**Delete 6 (leaf):** Case — leaf. Simply remove.\n```\n              11\n            /    \\\n           3     12\n          / \\\n         2   5\n        /   /\n       1   4\n```\n\n**Part 3 — All possible roots after the deletions:**\n\nThe only node with two children that required a choice is **7** (deleted in step 4). Its successor is 11 and its predecessor is 6 (but 6 still exists at that point).\n\nIf **successor (11)** is used: root becomes **11** (as shown above).\n\nIf **predecessor (6)** is used when deleting 7: Replace 7 with 6; then we still have 6 in the tree at its original position — but wait, 6 is the predecessor of 7 in the current tree (it's the rightmost node of 7's left subtree, namely right child of 5). Replace 7 with 6, then delete 6 from its position under 5.\n\nIn that case the root becomes **6**.\n\nAlso note: when deleting 10 (the first deletion), the successor of 10 is 11 and predecessor is 9. If we chose predecessor: replace 10 with 9, delete 9 (leaf). This gives a different tree shape going forward, which might change what ends up as root when 7 is deleted. Tracing: after deleting 10→9 (by predecessor), tree has 9 at position where 10 was; 9 has right child 12. Then delete original-9: already gone (used as predecessor). After deleting 8 (leaf), tree: root 7, left 3, right 9 (with right 12). Delete 7: successor of 7 is 8 — but 8 is already deleted! So successor is 9. Root becomes **9**. If predecessor is used: predecessor of 7 (in this tree) is 6. Root becomes **6**.\n\n**All possible keys that can end up as root:** $\\{6, 9, 11\\}$.\n\n**Answer:**\n1. BST as drawn above.\n2. Deletions use cases as described; tree evolves through the shown states.\n3. The possible root values after all deletions are **6, 9, or 11**.\n\n</details>\n\n##### **4.13. $d$-ary Tree in an Array** (Problem Set 6, Task 3)\n\nConsider storing an ordered rooted $d$-ary tree in an array using level-order numbering (root at index 0).\n\n1. For a perfect $d$-ary tree of height $h$, derive a closed-form formula for the total number of nodes $N(d, h)$.\n2. Derive formulas for (a) the index of the parent of node at index $i > 0$, and (b) the index of the $k$-th child ($1 \\le k \\le d$) of the node at index $i$.\n3. For a quaternary tree ($d = 4$) in an array of length $n = 70$, list all children of the node at index $i = 17$ that exist in the array.\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Part 1 — Total nodes in a perfect $d$-ary tree of height $h$:**\n\nLevel 0 (root) has 1 node. Level 1 has $d$ nodes. Level $k$ has $d^k$ nodes. Total:\n\n$$N(d, h) = \\sum_{k=0}^{h} d^k = \\frac{d^{h+1} - 1}{d - 1}$$\n\nFor $d = 2$ (binary): $N(2, h) = 2^{h+1} - 1$. For $d = 4$, $h = 2$: $N = (4^3 - 1)/3 = 63/3 = 21$.\n\n**Part 2 — Index formulas:**\n\n**(a) Parent of node at index $i > 0$:**\n\nThe children of node at index $j$ occupy indices $dj+1$ through $dj+d$. Node $i$ is a child of node $j$ if $dj+1 \\le i \\le dj+d$, i.e., $j = \\lfloor(i-1)/d\\rfloor$.\n\n$$\\text{parent}_d(i) = \\left\\lfloor \\frac{i-1}{d} \\right\\rfloor \\quad (i > 0)$$\n\n**(b) $k$-th child of node at index $i$:**\n\nNode at index $i$ has children at indices $di+1, di+2, \\ldots, di+d$. The $k$-th child ($1 \\le k \\le d$) is at:\n\n$$\\text{child}_{d,k}(i) = d \\cdot i + k$$\n\n**Verification for $d = 2$:** $\\text{child}_{2,1}(i) = 2i+1$ (left), $\\text{child}_{2,2}(i) = 2i+2$ (right). Matches the standard binary tree formulas. ✓\n\n**Part 3 — Children of node at $i = 17$ for $d = 4$, $n = 70$:**\n\n$$\\text{child}_{4,k}(17) = 4 \\times 17 + k = 68 + k$$\n\nSo the children are at indices $68+1=69$, $68+2=70$, $68+3=71$, $68+4=72$.\n\nThe array has indices $0$ to $n-1 = 69$. So:\n\n- Index 69: **exists** (valid, $69 \\le 69$)\n- Index 70: **does not exist** ($70 > 69$)\n- Index 71: does not exist\n- Index 72: does not exist\n\n**Answer:**\n1. $N(d,h) = \\dfrac{d^{h+1}-1}{d-1}$\n2. (a) $\\text{parent}_d(i) = \\lfloor(i-1)/d\\rfloor$; (b) $\\text{child}_{d,k}(i) = d \\cdot i + k$\n3. Only child at index **69** exists in the array.\n\n</details>\n\n##### **4.14. Recurrence Relation and Master Theorem** (Midterm 2025, Question A)\n\nCompute the asymptotic worst-case time complexity of the following `solve` procedure:\n\n```\nsolve(A, n):\n    return helper(A, 0, n - 1)\n\nhelper(A, l, r):\n    if r - l <= 1\n        return 1\n    else\n        k := ceil((r - l + 1) / 9)\n        a = helper(A, l, min(l + 3*k, r))\n        b = helper(A, l + 2*k, min(l + 5*k, r))\n        c = helper(A, l + 4*k, min(l + 7*k, r))\n        d = helper(A, l + 6*k, r)\n        for i from l to r:\n            for j from l to r:\n                if A[i] > A[j]:\n                    exchange A[i] with A[j]\n        return a\n```\n\n1. Express the running time $T(n)$ as a recurrence relation.\n2. Find the asymptotic complexity using the master method.\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** Identify the number of recursive calls, their sizes, and the non-recursive work per call.\n\n**Part 1 — Recurrence:**\n\nThe input size is $n = r - l + 1$. Setting $k = \\lceil n/9 \\rceil \\approx n/9$:\n\n- `helper(A, l, l + 3k)` works on approximately $3k \\approx n/3$ elements\n- `helper(A, l+2k, l+5k)` works on approximately $3k \\approx n/3$ elements\n- `helper(A, l+4k, l+7k)` works on approximately $3k \\approx n/3$ elements\n- `helper(A, l+6k, r)` works on approximately $3k \\approx n/3$ elements\n\nThere are **4 recursive calls**, each of size $\\approx n/3$.\n\nThe double loop runs in $\\Theta(n^2)$ (the range $[l, r]$ has $n$ elements).\n\n$$T(n) = 4T(n/3) + \\Theta(n^2)$$\n\n**Part 2 — Master theorem:**\n\nParameters: $a = 4$, $b = 3$, $f(n) = \\Theta(n^2)$.\n\nCompute $n^{\\log_b a} = n^{\\log_3 4} \\approx n^{1.26}$.\n\nCheck Case 3: $f(n) = n^2 = \\Omega(n^{\\log_3 4 + \\epsilon})$ for $\\epsilon = 2 - \\log_3 4 \\approx 0.74 > 0$. ✓\n\nRegularity: $a \\cdot f(n/b) = 4 \\cdot (n/3)^2 = 4n^2/9 \\le (4/9) \\cdot f(n)$ with $c = 4/9 < 1$. ✓\n\n**Case 3 applies:** $T(n) = \\Theta(f(n)) = \\Theta(n^2)$.\n\n**Answer:** $T(n) = 4T(n/3) + \\Theta(n^2)$. By Master Theorem Case 3, $T(n) = \\Theta(n^2)$.\n\n</details>\n\n##### **4.15. Radix Sort with Different Inner Sorts** (Midterm 2025, Question B)\n\nConsider sorting $p$ phrases using RADIX-SORT, treating each word as a \"digit\":\n\n- Each phrase is a list of at most $w$ words.\n- Each word is a list of at most $s$ symbols.\n- Each symbol comes from an alphabet of size $a$.\n\nWhat is the worst-case time complexity for sorting $p$ phrases if words are sorted using:\n\n1. INSERTION-SORT\n2. COUNTING-SORT\n3. RADIX-SORT (treating each symbol as a digit of the word)\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** RADIX-SORT on phrases makes $w$ passes, one per word-position. Each pass sorts $p$ phrases by one word-digit using a stable sort of words.\n\n**Case 1 — Words sorted by INSERTION-SORT:**\n\nComparing two words takes $O(s)$ (up to $s$ character comparisons). INSERTION-SORT on $p$ items makes $O(p^2)$ comparisons.\n\nOne pass: $O(p^2 \\cdot s)$. Total for $w$ passes: $\\mathbf{O(w \\cdot p^2 \\cdot s)}$.\n\n**Case 2 — Words sorted by COUNTING-SORT:**\n\nMap each word to an integer key in $[0, a^s)$. COUNTING-SORT with range $a^s$ on $p$ items: $O(p + a^s)$.\n\nTotal for $w$ passes: $\\mathbf{O(w \\cdot (p + a^s))}$.\n\n**Case 3 — Words sorted by RADIX-SORT (each symbol as a digit):**\n\nRADIX-SORT on $p$ words of length $s$ from alphabet of size $a$: $s$ passes each costing $O(p + a)$. One word-sort: $O(s(p + a))$.\n\nTotal for $w$ outer passes: $\\mathbf{O(w \\cdot s \\cdot (p + a))}$.\n\n**Answer:**\n1. $O(w \\cdot p^2 \\cdot s)$\n2. $O(w \\cdot (p + a^s))$\n3. $O(w \\cdot s \\cdot (p + a))$\n\n</details>\n\n##### **4.16. List Intersection Complexity** (Midterm 2025, Question C)\n\nConsider the intersection of $k$ non-empty sorted lists of integers with $m$ total elements. For each representation, determine whether an $O(mk)$ algorithm is possible:\n\n1. **Dynamic Array List**\n2. **Singly-Linked List (no tail pointer)**\n3. **Doubly-Linked List**\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** The algorithm compares the fronts of all $k$ lists and advances the minimum-front list. Each step costs $O(k)$ comparisons plus $O(1)$ advancement per element.\n\n**Case 1 — Dynamic Array:** Maintain current index per list; advancing is $O(1)$. Total: $O(mk)$. **YES**.\n\n**Case 2 — Singly-Linked List:** Maintain current-node pointer per list; advancing via `next` is $O(1)$. Total: $O(mk)$. **YES**.\n\n**Case 3 — Doubly-Linked List:** Same as singly-linked; `next` pointer gives $O(1)$ advancement. Total: $O(mk)$. **YES**.\n\n**Answer:** All three representations support an $O(mk)$ intersection algorithm.\n\n1. Dynamic Array: **YES**\n2. Singly-Linked List: **YES**\n3. Doubly-Linked List: **YES**\n\n</details>\n\n##### **4.17. Asymptotic Comparisons Table** (Midterm 2025, Question D)\n\nFor each pair $(A, B)$ below, determine whether $A = O(B)$, $A = o(B)$, $A = \\Omega(B)$, $A = \\omega(B)$, $A = \\Theta(B)$:\n\n| $A$ | $B$ |\n|:---|:---|\n| $n^n$ | $n!$ |\n| $n^{2025/2024}$ | $(2025/2024)^n$ |\n| $\\log^{2025} n$ | $n^{1/2025}$ |\n| $n \\log_2 n$ | $n^2 / \\log_2 n$ |\n| $\\log_2(n^n)$ | $\\log_2(n!)$ |\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Key Concept:** Use growth hierarchies: $\\log^k n \\ll n^\\epsilon \\ll n^c \\ll c^n \\ll n^n$. Apply Stirling's approximation $n! \\approx (n/e)^n \\sqrt{2\\pi n}$.\n\n**Row 1: $n^n$ vs $n!$**\n\nBy Stirling: $n^n / n! \\approx n^n / (n/e)^n = e^n \\to \\infty$. So $n^n = \\omega(n!)$.\n\n$O$: NO, $o$: NO, $\\Omega$: YES, $\\omega$: YES, $\\Theta$: NO.\n\n**Row 2: $n^{2025/2024}$ vs $(2025/2024)^n$**\n\nAny polynomial is $o$ of any exponential: $n^c = o(r^n)$ for $r > 1$.\n\n$O$: YES, $o$: YES, $\\Omega$: NO, $\\omega$: NO, $\\Theta$: NO.\n\n**Row 3: $\\log^{2025} n$ vs $n^{1/2025}$**\n\nAny power of $\\log n$ is $o$ of any positive power of $n$.\n\n$O$: YES, $o$: YES, $\\Omega$: NO, $\\omega$: NO, $\\Theta$: NO.\n\n**Row 4: $n \\log_2 n$ vs $n^2 / \\log_2 n$**\n\nRatio: $(n \\log n) / (n^2/\\log n) = \\log^2 n / n \\to 0$.\n\n$O$: YES, $o$: YES, $\\Omega$: NO, $\\omega$: NO, $\\Theta$: NO.\n\n**Row 5: $\\log_2(n^n)$ vs $\\log_2(n!)$**\n\n$\\log_2(n^n) = n\\log_2 n$. By Stirling: $\\log_2(n!) = n\\log_2 n - n\\log_2 e + O(\\log n) \\sim n\\log_2 n$. So they are $\\Theta$ of each other.\n\n$O$: YES, $o$: NO, $\\Omega$: YES, $\\omega$: NO, $\\Theta$: YES.\n\n**Answer table:**\n\n| $A$ | $B$ | $O$ | $o$ | $\\Omega$ | $\\omega$ | $\\Theta$ |\n|:---|:---|:---:|:---:|:---:|:---:|:---:|\n| $n^n$ | $n!$ | NO | NO | YES | YES | NO |\n| $n^{2025/2024}$ | $(2025/2024)^n$ | YES | YES | NO | NO | NO |\n| $\\log^{2025} n$ | $n^{1/2025}$ | YES | YES | NO | NO | NO |\n| $n \\log_2 n$ | $n^2/\\log_2 n$ | YES | YES | NO | NO | NO |\n| $\\log_2(n^n)$ | $\\log_2(n!)$ | YES | NO | YES | NO | YES |\n\n</details>\n\n##### **4.18. Master Theorem Application** (Midterm 2025, Question E)\n\nConsider the recurrence $T(n) = 64T(n/4) + 7n^3 + 49$. Which applies?\n\n1. $T(n) = \\Theta(n^3 \\log n)$\n2. $T(n) = \\Theta(n^4)$\n3. Master theorem is not applicable\n4. None of the above\n\nJustify your answer.\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Parameters:** $a = 64$, $b = 4$, $f(n) = 7n^3 + 49 = \\Theta(n^3)$.\n\n**Compute $n^{\\log_b a}$:**\n\n$$n^{\\log_4 64} = n^{\\log_4 4^3} = n^3$$\n\n**Compare:** $f(n) = \\Theta(n^3) = \\Theta(n^{\\log_4 64} \\cdot \\log^0 n)$ → **Case 2** with $k = 0$.\n\n$$T(n) = \\Theta(n^3 \\log^{0+1} n) = \\Theta(n^3 \\log n)$$\n\n**Answer:** Option **1**: $T(n) = \\Theta(n^3 \\log n)$. Master Theorem Case 2 applies since $f(n) = \\Theta(n^{\\log_4 64}) = \\Theta(n^3)$.\n\n</details>\n\n##### **4.19. Hash Table with Linear Probing** (Midterm 2025, Question F)\n\nConsider a hash table with 11 slots and $h(k) = (k + 1) \\bmod 11$ with linear probing:\n\n| Index | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |\n|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|\n| Key | — | 23 | — | 35 | 2 | 15 | 5 | 13 | — | — | 9 |\n\nAnswer YES/NO:\n\n1. Could key 9 have been inserted before 23?\n2. Could key 23 have been inserted before 2?\n3. Could key 13 have been inserted before 5?\n4. Could key 15 have been inserted before 35?\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Home positions** (where $h(k)$ maps to):\n\n- $h(9) = 10$ → stored at **10** (home) ✓\n- $h(23) = 24 \\bmod 11 = 2$ → stored at **1** (wrapped past 2,3,...,10,0 → all occupied at insertion time)\n- $h(35) = 36 \\bmod 11 = 3$ → stored at **3** (home) ✓\n- $h(2) = 3 \\bmod 11 = 3$ → stored at **4** (home 3 taken by 35 → probed to 4)\n- $h(15) = 16 \\bmod 11 = 5$ → stored at **5** (home) ✓\n- $h(5) = 6 \\bmod 11 = 6$ → stored at **6** (home) ✓\n- $h(13) = 14 \\bmod 11 = 3$ → stored at **7** (home 3 taken by 35; 4 by 2; 5 by 15; 6 by 5; probed to 7)\n\n**Analysis:**\n\n1. **9 before 23?** Key 9 sits at its home (10). It doesn't block any slot between index 2 and index 0 that 23 needs — it *does* occupy slot 10, which 23 needs to probe through (when wrapping). So 9 at 10 is *required* for 23 to end up at 1. Therefore, 9 **must** have been inserted before 23 (or at minimum was present when 23 was inserted). **YES**.\n2. **23 before 2?** Key 2 needs home 3 to be occupied (by 35). Key 23 lives at slot 1 and has home 2, not 3. Inserting 23 before 2 does not affect whether slot 3 is available for 2; slot 3 must be occupied by 35 regardless. **YES**.\n3. **13 before 5?** Key 13 is at slot 7, home 3. Linear probe: 3→4→5→6→7. For 13 to land at 7, slots 3,4,5,6 must all be occupied at time of 13's insertion. Slot 6 is occupied by key 5 (home 6). So key 5 must be in slot 6 when 13 is inserted, meaning **5 was inserted before 13**. Conclusion: 13 could **not** have been inserted before 5. **NO**.\n4. **15 before 35?** Key 15 has home 5 and sits there. Key 35 has home 3. They don't occupy each other's probing paths. **YES**.\n\n**Answer:** 1. YES, 2. YES, 3. NO, 4. YES.\n\n</details>\n\n##### **4.20. True/False Statements** (Midterm 2025, Questions G–H)\n\nFor each statement, determine TRUE or FALSE:\n\n1. If $\\log(f(n)) = \\Theta(\\log(g(n)))$ then $f(n) = \\Theta(g(n))$.\n2. Incrementing a binary counter takes $\\Theta(1)$ amortized, but $\\Theta(\\log k)$ worst case (where $k$ is the number of digits).\n3. In a stack using dynamic arrays, PUSH has $\\Theta(n)$ worst-case time complexity.\n4. Inserting into a hash table with separate chaining is $O(1 + \\alpha)$ average case.\n5. Finding a value in a hash table with load factor $\\alpha$ is $\\Theta(1)$ worst case as long as $\\text{hash}(k)$ runs in $\\Theta(1)$.\n6. If the master theorem is not applicable, the algorithm can loop indefinitely.\n7. Dynamic Programming is an implementation in a dynamically-typed language.\n8. QUICK-SORT has $\\Theta(n \\log n)$ worst-case time complexity.\n9. Sorting $n$ real numbers uniformly distributed in $[0, k]$ using BUCKET-SORT takes $\\Theta(n)$ average case.\n10. PARTITION (used in QUICK-SORT) has quadratic worst-case time complexity.\n\n<details>\n<summary>Click to see the solution</summary>\n\n**1. FALSE.** Counterexample: $f(n) = n$, $g(n) = n^2$. $\\log f = \\Theta(\\log g)$ (both are $\\Theta(\\log n)$), but $f \\ne \\Theta(g)$.\n\n**2. FALSE.** With $k$ digits, the worst case (all 1s) flips all $k$ bits: $\\Theta(k)$ worst case, not $\\Theta(\\log k)$.\n\n**3. TRUE.** When the array doubles, copying $n$ elements takes $\\Theta(n)$ — this is the worst case for a single PUSH. The *amortized* cost is $\\Theta(1)$.\n\n**4. TRUE.** Average chain length is $\\alpha$; insert requires hashing ($O(1)$) + appending ($O(1)$ or $O(\\alpha)$ if checking duplicates). $O(1 + \\alpha)$ is correct.\n\n**5. FALSE.** Worst case: all $n$ keys collide into one chain. Lookup is $\\Theta(n)$ worst case regardless of hash computation speed.\n\n**6. FALSE.** \"Master theorem not applicable\" means the recurrence doesn't fit the required form; the algorithm still terminates. We simply use another analysis method.\n\n**7. FALSE.** Dynamic Programming is an algorithmic design technique for optimization problems with overlapping subproblems. Language typing is irrelevant.\n\n**8. FALSE.** QUICK-SORT is $\\Theta(n \\log n)$ *average case* and $\\Theta(n^2)$ *worst case* (e.g., sorted input with last-element pivot).\n\n**9. TRUE.** With uniform distribution over $n$ buckets, expected elements per bucket is $O(1)$. Each bucket is sorted in $O(1)$ expected time. Total: $\\Theta(n)$ average case.\n\n**10. FALSE.** PARTITION runs in $\\Theta(n)$ time — it makes one linear scan. It is QUICK-SORT as a whole that has $\\Theta(n^2)$ worst case.\n\n**Answer summary:**\n\n| # | Truth |\n|:---:|:---:|\n| 1 | FALSE |\n| 2 | FALSE |\n| 3 | TRUE |\n| 4 | TRUE |\n| 5 | FALSE |\n| 6 | FALSE |\n| 7 | FALSE |\n| 8 | FALSE |\n| 9 | TRUE |\n| 10 | FALSE |\n\n</details>\n\n##### **4.21. Rod Cutting with DP** (Midterm 2025, Question H)\n\nAnswer the following about the Rod Cutting problem:\n\n1. Using DP with *tabulation*, what is the worst-case time complexity of finding the maximum revenue for a rod of length $n$?\n2. Using DP with *memoization* (finding both maximum revenue and cut positions), what is the worst-case time complexity?\n3. Find the maximum revenue for a rod of length 10 with prices:\n\n| Length $i$ | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |\n|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|\n| Price $p_i$ | 2 | 3 | 9 | 12 | 13 | 13 | 14 | 24 | 25 | 28 |\n\n4. *(+1% extra credit)* Consider Rod Cutting with at most $k$ cuts. Give an $O(nk)$ pseudocode algorithm.\n\n<details>\n<summary>Click to see the solution</summary>\n\n**Part 1 — Tabulation time complexity:**\n\nFill array $r[0..n]$; for each $j$ from 1 to $n$, try all $i$ from 1 to $j$ cuts: $\\sum_{j=1}^{n} j = n(n+1)/2 = \\Theta(n^2)$.\n\n**Answer:** $\\Theta(n^2)$.\n\n**Part 2 — Memoization time complexity:**\n\nSame subproblems, same recurrence: $\\Theta(n^2)$.\n\n**Answer:** $\\Theta(n^2)$.\n\n**Part 3 — Maximum revenue for $n = 10$:**\n\nRecurrence: $r[j] = \\max_{1 \\le i \\le j}(p[i] + r[j-i])$, $r[0] = 0$.\n\n| $j$ | Calculation | $r[j]$ | Best cut |\n|:---:|:---|:---:|:---:|\n| 1 | $p[1] + r[0] = 2$ | **2** | cut 1 |\n| 2 | $\\max(2+2, 3+0) = \\max(4, 3)$ | **4** | cut 1+1 |\n| 3 | $\\max(2+4, 3+2, 9+0) = \\max(6,5,9)$ | **9** | cut 3 |\n| 4 | $\\max(2+9, 3+4, 9+2, 12+0) = \\max(11,7,11,12)$ | **12** | cut 4 |\n| 5 | $\\max(2+12, 3+9, 9+4, 12+2, 13+0) = \\max(14,12,13,14,13)$ | **14** | cut 1+4 or 2+... |\n| 6 | $\\max(2+14, 3+12, 9+9, 12+4, 13+2, 13+0) = \\max(16,15,18,16,15,13)$ | **18** | cut 3+3 |\n| 7 | $\\max(2+18,3+14,9+12,12+9,13+4,13+2,14+0) = \\max(20,17,21,21,17,15,14)$ | **21** | cut 3+4 or 4+3 |\n| 8 | $\\max(2+21,3+18,9+14,12+12,13+9,13+4,...,24+0) = \\max(23,21,23,24,22,...,24)$ | **24** | cut 4+4 or 8 |\n| 9 | $\\max(2+24,3+21,...,9+12,12+9,...,25+0)$. Check $p[3]+r[6]=9+18=27$, $p[3]+r[6]=27$, $p[6]+r[3]=13+9=22$. Also $p[9]=25$. Best: $\\max(26,25,27,23,...,25)$ | **27** | cut 3+3+3 |\n| 10 | $\\max(p[3]+r[7], p[4]+r[6], \\ldots) = \\max(9{+}21, 12{+}18, \\ldots) = 30$ | **30** | cut 3+7 or 4+6 |\n\n**Part 4 — At most $k$ cuts:**\n\nDefine $dp[j][c]$ = maximum revenue from a rod of length $j$ with at most $c$ cuts allowed.\n\n$$dp[j][c] = \\max\\left(p[j],\\ \\max_{1 \\le i < j}(p[i] + dp[j-i][c-1])\\right)$$\n\nBase cases: $dp[0][c] = 0$ for all $c$; $dp[j][0] = p[j]$ (no cuts allowed → sell the whole piece).\n\n```\nfunction ROD-CUTTING-K(p, n, k):\n    dp[0..n][0..k] ← 0\n    for j ← 1 to n:\n        dp[j][0] ← p[j]           // no cuts: sell as length j\n    for c ← 1 to k:\n        for j ← 1 to n:\n            dp[j][c] ← p[j]       // option: no cut\n            for i ← 1 to j-1:\n                dp[j][c] ← max(dp[j][c], p[i] + dp[j-i][c-1])\n    return dp[n][k]\n```\n\n**Complexity:** Three nested loops: $k \\times n \\times n = O(n^2 k)$. To achieve $O(nk)$, observe that we can reformulate: instead of \"which first cut to make,\" use a different DP where $dp[j][c]$ = max revenue from rod of length $j$ making *exactly* $c$ cuts (then take max over $c' \\le k$). But the standard $O(n^2 k)$ version is more natural. An $O(nk)$ version requires a different subproblem formulation or convex hull trick.\n\n**Answer:**\n1. $\\Theta(n^2)$\n2. $\\Theta(n^2)$\n3. Maximum revenue = **30** (e.g., cut into 3+7 or 4+6)\n4. DP defined above runs in $O(n^2 k)$; an $O(nk)$ solution requires advanced techniques.\n\n</details>\n\n##### **4.22. Asymptotic Complexity of SOLVE** (Midterm 2026, Question A)\n\nCompute the asymptotic worst-case time complexity of the SOLVE procedure:\n\n```\nSolve(A, n):\n  return Helper(A, 1, n)\n\nHelper(A, l, r):\n  if r - l <= 100\n    return l\n  else\n    k := ⌈(r - l + 1) / 6⌉\n    a = Helper(A, l, l + 2*k) + Helper(A, l + k, l + 3*k)\n    b = Helper(A, l + 2*k, l + 4*k) + Helper(A, l + 3*k, l + 5*k)\n    c = Helper(A, l + 4*k, r)\n    low := l; high := r\n    while low < high:\n      mid := ⌊(low + high) / 2⌋\n      count := 0\n      for i from l to r:\n        if A[i] > A[mid]: count := count + 1\n      if count > (r - l + 1) / 2 then high := mid else low := mid + 1\n    return low\n```\n\n1. Express the running time $T(n)$ as a recurrence relation.\n2. Find the asymptotic complexity using the Master Method, specifying which case applies.\n\n<details><summary>Click to see the solution</summary>\n\n**Step 1: Set up the recurrence.**\n\nLet $n = r - l + 1$ be the size of the subarray. When $n \\le 101$, the function returns immediately: $T(n) = \\Theta(1)$.\n\nFor larger $n$, set $k = \\lceil n/6 \\rceil \\approx n/6$.\n\nCount the recursive calls:\n\n- `Helper(A, l, l + 2*k)` — subarray of size $2k + 1 \\approx n/3$\n- `Helper(A, l + k, l + 3*k)` — subarray of size $2k + 1 \\approx n/3$\n- `Helper(A, l + 2*k, l + 4*k)` — subarray of size $2k + 1 \\approx n/3$\n- `Helper(A, l + 3*k, l + 5*k)` — subarray of size $2k + 1 \\approx n/3$\n- `Helper(A, l + 4*k, r)` — subarray of size $\\approx n - 4k \\approx n/3$\n\nSo there are **5 recursive calls**, each on a subarray of size $\\approx n/3$.\n\nThe non-recursive work: the `while` loop runs at most $O(\\log n)$ iterations (binary search on a range of size $n$). Each iteration runs the inner `for` loop over all $n$ elements: $\\Theta(n)$ per iteration, so total non-recursive work is $\\Theta(n \\log n)$.\n\n**Recurrence:**\n\n$$T(n) = 5T(n/3) + \\Theta(n \\log n)$$\n\n**Step 2: Apply the Master Theorem.**\n\nThe Master Theorem for $T(n) = aT(n/b) + f(n)$:\n\n- $a = 5$, $b = 3$, so $n^{\\log_b a} = n^{\\log_3 5}$.\n- $\\log_3 5 \\approx 1.465$.\n- $f(n) = \\Theta(n \\log n) = \\Theta(n^1 \\log n)$.\n\nCompare $f(n)$ with $n^{\\log_3 5} \\approx n^{1.465}$:\n\nSince $n \\log n = o(n^{1.465})$ (polynomial beats polylog), we have $f(n) = O(n^{\\log_3 5 - \\varepsilon})$ for $\\varepsilon \\approx 0.465 > 0$.\n\n**Case 1 of the Master Theorem applies.**\n\n$$\\boxed{T(n) = \\Theta(n^{\\log_3 5})}$$\n\n</details>\n\n---\n\n##### **4.23. Asymptotic Comparison Table** (Midterm 2026, Question B)\n\nUse the most precise asymptotic notation ($O$, $\\Theta$, $\\Omega$) or $\\times$ if none applies, to express the relationship $f(n) = [?](g(n))$:\n\n| # | $f(n)$ | $g(n)$ |\n|---|--------|--------|\n| 1 | $2026^n$ | $(n+2026)!$ |\n| 2 | $(2026/2025)^n$ | $n^{2026/2025}$ |\n| 3 | $(\\log_2 n)^{2026}$ | $\\sqrt[2026]{n}$ |\n| 4 | $n \\log_2 n$ | $n^2 / \\log_2 n$ |\n| 5 | $\\log_2(n^n)$ | $\\log_2(n!)$ |\n| 6 | $\\sqrt{n \\log_2 n}$ | $\\sqrt{n} \\cdot \\log_2 \\sqrt{n}$ |\n| 7 | $(1 + 1/n)^n$ | $n$ |\n| 8 | $2^n + 2^n$ | $4^n$ |\n\n<details><summary>Click to see the solution</summary>\n\n**1. $2026^n$ vs $(n+2026)!$**\n\n$(n+2026)!$ grows much faster than any exponential $c^n$. For large $n$, $(n+2026)! \\gg 2026^n$.\n\n**Answer:** $f(n) = O(g(n))$\n\n---\n\n**2. $(2026/2025)^n$ vs $n^{2026/2025}$**\n\n$(2026/2025)^n$ is exponential (base $> 1$), while $n^{2026/2025}$ is polynomial. Exponential grows faster.\n\n**Answer:** $f(n) = \\Omega(g(n))$\n\n---\n\n**3. $(\\log_2 n)^{2026}$ vs $\\sqrt[2026]{n} = n^{1/2026}$**\n\nAny positive power of $n$ grows faster than any power of $\\log n$: $(\\log n)^k = o(n^\\varepsilon)$ for any $\\varepsilon > 0$.\n\nHere $\\varepsilon = 1/2026 > 0$, so $(\\log_2 n)^{2026} = o(n^{1/2026})$.\n\n**Answer:** $f(n) = O(g(n))$\n\n---\n\n**4. $n \\log_2 n$ vs $n^2 / \\log_2 n$**\n\n$\\frac{g(n)}{f(n)} = \\frac{n^2/\\log n}{n \\log n} = \\frac{n}{\\log^2 n} \\to \\infty$.\n\nSo $f(n) = o(g(n))$.\n\n**Answer:** $f(n) = O(g(n))$\n\n---\n\n**5. $\\log_2(n^n)$ vs $\\log_2(n!)$**\n\n$\\log_2(n^n) = n \\log_2 n$.\n\nBy Stirling's approximation: $\\log_2(n!) = \\Theta(n \\log n)$.\n\nMore precisely, $n \\log n - n/\\ln 2 \\le \\log_2(n!) \\le n \\log n$, so both are $\\Theta(n \\log n)$.\n\n**Answer:** $f(n) = \\Theta(g(n))$\n\n---\n\n**6. $\\sqrt{n \\log_2 n}$ vs $\\sqrt{n} \\cdot \\log_2 \\sqrt{n}$**\n\n$\\sqrt{n \\log_2 n} = \\sqrt{n} \\cdot \\sqrt{\\log_2 n}$.\n\n$\\sqrt{n} \\cdot \\log_2 \\sqrt{n} = \\sqrt{n} \\cdot \\frac{1}{2}\\log_2 n$.\n\nRatio: $\\frac{\\sqrt{n} \\cdot \\sqrt{\\log n}}{\\sqrt{n} \\cdot \\frac{1}{2}\\log n} = \\frac{\\sqrt{\\log n}}{\\frac{1}{2}\\log n} = \\frac{2}{\\sqrt{\\log n}} \\to 0$.\n\nSo $f(n) = o(g(n))$.\n\n**Answer:** $f(n) = O(g(n))$\n\n---\n\n**7. $(1 + 1/n)^n$ vs $n$**\n\n$(1 + 1/n)^n \\to e \\approx 2.718$ as $n \\to \\infty$ (converges to a constant). Meanwhile $g(n) = n \\to \\infty$.\n\n**Answer:** $f(n) = O(g(n))$\n\n---\n\n**8. $2^n + 2^n$ vs $4^n$**\n\n$2^n + 2^n = 2 \\cdot 2^n = 2^{n+1}$.\n\n$4^n = (2^2)^n = 2^{2n}$.\n\n$\\frac{2^{2n}}{2^{n+1}} = 2^{n-1} \\to \\infty$, so $f(n) = o(g(n))$.\n\n**Answer:** $f(n) = O(g(n))$\n\n</details>\n\n---\n\n##### **4.24. Master Theorem Application** (Midterm 2026, Question C)\n\nConsider $T(n) = 8T(n/3) + 5n^2 + 10$. Which of the following is correct?\n\n1. $T(n) = \\Theta(n^2 \\log n)$\n2. $T(n) = \\Theta(n^3)$\n3. Master theorem not applicable\n4. None of the above\n\nAnswer and justify.\n\n<details><summary>Click to see the solution</summary>\n\n**Answer: Option 4 — None of the above.**\n\nApply the Master Theorem with $a = 8$, $b = 3$, $f(n) = 5n^2 + 10 = \\Theta(n^2)$.\n\nCompute $n^{\\log_b a} = n^{\\log_3 8}$.\n\n$\\log_3 8 = \\frac{\\ln 8}{\\ln 3} = \\frac{3\\ln 2}{\\ln 3} \\approx \\frac{3 \\times 0.693}{1.099} \\approx 1.893$.\n\nSo $n^{\\log_3 8} \\approx n^{1.893}$.\n\nCompare $f(n) = \\Theta(n^2)$ with $n^{1.893}$:\n\nSince $n^2 = \\Omega(n^{1.893 + \\varepsilon})$ for $\\varepsilon \\approx 0.107 > 0$, **Case 3** of the Master Theorem applies — provided the regularity condition holds.\n\nRegularity condition: $af(n/b) \\le cf(n)$ for some $c < 1$.\n\n$8 \\cdot f(n/3) = 8 \\cdot 5(n/3)^2 = 8 \\cdot \\frac{5n^2}{9} = \\frac{40n^2}{9} \\approx 4.44 \\cdot n^2/1 \\le c \\cdot 5n^2$ requires $c \\ge 8/9 < 1$. ✓\n\nSo **Case 3 applies** and:\n\n$$T(n) = \\Theta(f(n)) = \\Theta(n^2)$$\n\nNone of the listed options (1), (2), (3) is correct — the correct answer is $T(n) = \\Theta(n^2)$, which is option **(4) None of the above**.\n\n</details>\n\n---\n\n##### **4.25. Data Structure Complexity Table** (Midterm 2026, Question D)\n\nCollection $A$ of $n$ columns, each column $C_i$ has $n$ elements. Extend $A$ with column $C_{n+1}$ consisting of the diagonal elements $C_1[1], C_2[2], \\ldots, C_n[n]$.\n\nFill the table of asymptotic worst-case time complexity for creating $C_{n+1}$ and appending it to $A$:\n\n| Representation of $A$ | Representation of $C_i$ | Time to build $C_{n+1}$ and append |\n|-----------------------|------------------------|--------------------------------------|\n| Array List | Array List | ? |\n| Array List | Singly-Linked (no tail) | ? |\n| Array List | Singly-Linked (with tail) | ? |\n| Singly-Linked (no tail) | Array List | ? |\n| Singly-Linked (no tail) | Singly-Linked (no tail) | ? |\n| Singly-Linked (no tail) | Singly-Linked (with tail) | ? |\n| Singly-Linked (with tail) | Array List | ? |\n| Singly-Linked (with tail) | Singly-Linked (no tail) | ? |\n| Singly-Linked (with tail) | Singly-Linked (with tail) | ? |\n\n<details><summary>Click to see the solution</summary>\n\n**Key operations:**\n\n1. **Access $C_i$ (the $i$-th column of $A$):** $O(1)$ for Array List, $O(i)$ for Singly-Linked (no tail) — must traverse to position $i$.\n2. **Access $C_i[i]$ (the $i$-th element of $C_i$):** $O(1)$ for Array List, $O(i)$ for Singly-Linked (any) — must traverse to position $i$.\n3. **Append $C_{n+1}$ to $A$:** $O(1)$ amortized for Array List (or $O(n)$ worst case resize), $O(n)$ for Singly-Linked (no tail) — must traverse to end, $O(1)$ for Singly-Linked (with tail).\n4. **Building $C_{n+1}$:** We retrieve elements $C_1[1], C_2[2], \\ldots, C_n[n]$. For each $i$, we access column $C_i$ then element $[i]$.\n\n**Cost of collecting all $n$ diagonal elements:**\n\n- If $A$ is an **Array List**: accessing $C_i$ is $O(1)$, so cost of accessing all $C_i$ is $O(n)$ total.\n- If $A$ is a **Singly-Linked (no tail)**: accessing $C_i$ costs $O(i)$, total $\\sum_{i=1}^n O(i) = O(n^2)$.\n- If $A$ is a **Singly-Linked (with tail)**: same as no-tail for random access — $O(i)$ per access, total $O(n^2)$.\n\nWithin each $C_i$, accessing element at position $i$:\n\n- **Array List**: $O(1)$ per element, $O(n)$ total over all $i$.\n- **Singly-Linked (no tail or with tail)**: $O(i)$ per element, $\\sum_{i=1}^n O(i) = O(n^2)$ total.\n\n**Appending $C_{n+1}$ to $A$** (building $C_{n+1}$ itself as a list of $n$ elements):\n\n- The new column must be built by inserting $n$ elements. Cost $O(n)$ regardless of representation.\n- Appending the column pointer to $A$: $O(1)$ Array List (amortized), $O(n)$ Singly-Linked no tail, $O(1)$ Singly-Linked with tail.\n\n**Combined complexities (dominant term):**\n\n| $A$ | $C_i$ | Total |\n|-----|--------|-------|\n| Array List | Array List | $O(n)$ |\n| Array List | Singly-Linked (no tail) | $O(n^2)$ |\n| Array List | Singly-Linked (with tail) | $O(n^2)$ |\n| Singly-Linked (no tail) | Array List | $O(n^2)$ (accessing $A$) + $O(n)$ append = $O(n^2)$ |\n| Singly-Linked (no tail) | Singly-Linked (no tail) | $O(n^2)$ |\n| Singly-Linked (no tail) | Singly-Linked (with tail) | $O(n^2)$ |\n| Singly-Linked (with tail) | Array List | $O(n^2)$ (accessing $A$) + $O(1)$ append = $O(n^2)$ |\n| Singly-Linked (with tail) | Singly-Linked (no tail) | $O(n^2)$ |\n| Singly-Linked (with tail) | Singly-Linked (with tail) | $O(n^2)$ |\n\n**Answer:** Only when both $A$ and $C_i$ are Array Lists is the total $O(n)$; all other combinations are $O(n^2)$.\n\n</details>\n\n---\n\n##### **4.26. RADIX-SORT for Phrases** (Midterm 2026, Question E)\n\n$p$ phrases are sorted using RADIX-SORT, treating each word as a \"digit\":\n\n- Each phrase has at most $w$ words\n- Each word has at most $s$ symbols\n- Each symbol is from an alphabet of size $a$\n- Comparing two symbols takes $\\Theta(1)$\n\nFind the worst-case time complexity for sorting $p$ phrases when the stable sort for words uses:\n\n1. INSERTION-SORT\n2. COUNTING-SORT\n3. QUICK-SORT\n\n<details><summary>Click to see the solution</summary>\n\n**Setup:**\n\nRADIX-SORT processes $w$ digit positions (one per word position in a phrase). At each position, we stably sort $p$ phrases by the word at that position.\n\nComparing two words of at most $s$ symbols costs $O(s)$ (compare symbol by symbol, each $\\Theta(1)$).\n\n**1. INSERTION-SORT for sorting words:**\n\n- Comparing two words: $O(s)$.\n- INSERTION-SORT on $p$ items: $O(p^2)$ comparisons worst case.\n- Cost per RADIX-SORT pass: $O(p^2 \\cdot s)$.\n- Total for $w$ passes: $O(w \\cdot p^2 \\cdot s)$.\n\n$$\\boxed{O(w \\cdot s \\cdot p^2)}$$\n\n**2. COUNTING-SORT for sorting words:**\n\nCOUNTING-SORT treats each word as a key. However, words are strings — to use COUNTING-SORT, we'd need to sort by the full word as a key. With alphabet size $a$ and word length $s$, there are $a^s$ possible words — the counting array would be huge.\n\nAlternatively, COUNTING-SORT on words using the word as a composite key requires $\\Theta(p + a^s)$ per pass.\n\nTotal for $w$ passes: $O(w \\cdot (p + a^s))$.\n\n$$\\boxed{O(w \\cdot (p + a^s))}$$\n\n**3. QUICK-SORT for sorting words:**\n\nQUICK-SORT is **not stable**, so using it directly inside RADIX-SORT breaks the algorithm's correctness. Assuming we use a stable variant or accept the instability issue:\n\n- QUICK-SORT on $p$ items: $O(p^2)$ worst case.\n- Each comparison: $O(s)$.\n- Cost per pass: $O(p^2 \\cdot s)$.\n- Total: $O(w \\cdot s \\cdot p^2)$.\n\nNote: Since QUICK-SORT is not stable, RADIX-SORT with QUICK-SORT does not correctly sort in general. This is a fundamental issue.\n\n$$\\boxed{O(w \\cdot s \\cdot p^2)}$$\n\n</details>\n\n---\n\n##### **4.27. COUNTING-SORT Application** (Midterm 2026, Question F)\n\nApply COUNTING-SORT to the following array:\n\n| key  | 3 | 1 | 2 | 0 | 2 | 1 | 4 | 0 | 2 | 1 | 0 | 3 |\n|------|---|---|---|---|---|---|---|---|---|---|---|---|\n| data | I | E | D | R | S | A | E | I | H | N | S | N |\n\n1. Give the auxiliary array $C$ after the cumulative (prefix-sum) step for $k \\in \\{0,1,2,3,4\\}$.\n2. Give the output array (sorted).\n\n<details><summary>Click to see the solution</summary>\n\n**Step 1: Count occurrences.**\n\nScan the key array: keys are $3,1,2,0,2,1,4,0,2,1,0,3$.\n\n| key $k$ | 0 | 1 | 2 | 3 | 4 |\n|---------|---|---|---|---|---|\n| count   | 3 | 3 | 3 | 2 | 1 |\n\n**Step 2: Cumulative sum (prefix sum).**\n\n$C[k] = \\sum_{j=0}^{k} \\text{count}[j]$\n\n| $k$    | 0 | 1 | 2 | 3  | 4  |\n|--------|---|---|---|----|----|\n| $C[k]$ | 3 | 6 | 9 | 11 | 12 |\n\n**Answer to part 1:** $C = [3, 6, 9, 11, 12]$\n\n**Step 3: Build output array (process input right to left for stability).**\n\nOutput array of size 12, 1-indexed positions.\n\nProcess input from right to left:\n\n| Step | key | data | $C[key]$ | place at | new $C[key]$ |\n|------|-----|------|----------|----------|--------------|\n| 12 | 3 | N | 11 | pos 11 | 10 |\n| 11 | 0 | S | 3  | pos 3  | 2  |\n| 10 | 1 | N | 6  | pos 6  | 5  |\n| 9  | 2 | H | 9  | pos 9  | 8  |\n| 8  | 0 | I | 2  | pos 2  | 1  |\n| 7  | 4 | E | 12 | pos 12 | 11 |\n| 6  | 1 | A | 5  | pos 5  | 4  |\n| 5  | 2 | S | 8  | pos 8  | 7  |\nInput (1-indexed):\n\n| pos | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |\n|-----|---|---|---|---|---|---|---|---|---|----|----|----|\n| key | 3 | 1 | 2 | 0 | 2 | 1 | 4 | 0 | 2 | 1  | 0  | 3  |\n| dat | I | E | D | R | S | A | E | I | H | N  | S  | N  |\n\n$C$ after cumulative step: $C[0]=3, C[1]=6, C[2]=9, C[3]=11, C[4]=12$.\n\nProcess right to left (positions 12 down to 1):\n\n- pos=12: key=3, data=N → output[C[3]]=output[11]=N, C[3]=10\n- pos=11: key=0, data=S → output[C[0]]=output[3]=S, C[0]=2\n- pos=10: key=1, data=N → output[C[1]]=output[6]=N, C[1]=5\n- pos=9:  key=2, data=H → output[C[2]]=output[9]=H, C[2]=8\n- pos=8:  key=0, data=I → output[C[0]]=output[2]=I, C[0]=1\n- pos=7:  key=4, data=E → output[C[4]]=output[12]=E, C[4]=11\n- pos=6:  key=1, data=A → output[C[1]]=output[5]=A, C[1]=4\n- pos=5:  key=2, data=S → output[C[2]]=output[8]=S, C[2]=7\n- pos=4:  key=0, data=R → output[C[0]]=output[1]=R, C[0]=0\n- pos=3:  key=2, data=D → output[C[2]]=output[7]=D, C[2]=6\n- pos=2:  key=1, data=E → output[C[1]]=output[4]=E, C[1]=3\n- pos=1:  key=3, data=I → output[C[3]]=output[10]=I, C[3]=9\n\n**Output array:**\n\n| pos | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |\n|-----|---|---|---|---|---|---|---|---|---|----|----|----|\n| key | 0 | 0 | 0 | 1 | 1 | 1 | 2 | 2 | 2 | 3  | 3  | 4  |\n| dat | R | I | S | E | A | N | D | S | H | I  | N  | E  |\n\n**Answer to part 2:** The sorted array is: $R, I, S, E, A, N, D, S, H, I, N, E$ (keys: $0,0,0,1,1,1,2,2,2,3,3,4$).\n\nNote: Reading the data in sorted order spells out **RISE AND SHINE** — a cute exam easter egg!\n\n</details>\n\n---\n\n##### **4.28. True or False** (Midterm 2026, Question G)\n\nDetermine TRUE or FALSE for each statement:\n\n1. If $\\log(f(n)) = \\Theta(\\log(g(n)))$ then $f(n) = \\Theta(g(n))$\n2. Incrementing a binary counter takes $\\Theta(\\log k)$ worst-case time where $k$ is the number of digits\n3. In ARRAYSTACK, PUSH(x) has $\\Theta(n)$ worst-case time complexity\n4. MERGE-SORT has $\\Theta(n \\log n)$ worst-case time complexity\n5. COUNTING-SORT sorts $n$ integers in $[0, n^2]$ in $\\Theta(n)$ worst-case time\n6. If the master theorem doesn't apply, the algorithm may loop indefinitely\n7. Dynamic Programming involves a dynamically-typed programming language (e.g., Python)\n8. QUICK-SORT has $\\Theta(n \\log n)$ worst-case time complexity\n9. In a BST, the node with minimum key cannot have a right child\n10. Height of a red-black tree with $n$ internal nodes is $\\Theta(\\log n)$\n\n<details><summary>Click to see the solution</summary>\n\n**1. FALSE.**\n\nCounterexample: $f(n) = n^2$, $g(n) = n^3$. Then $\\log f(n) = 2\\log n$, $\\log g(n) = 3\\log n$, so $\\log f(n) = \\Theta(\\log g(n))$. But $f(n) = O(g(n))$, not $\\Theta(g(n))$.\n\n---\n\n**2. TRUE.**\n\nIn the worst case, incrementing a $k$-bit binary counter flips all $k$ bits (e.g., $0111\\ldots1 \\to 1000\\ldots0$), which takes $\\Theta(k)$ time. So worst case is $\\Theta(k)$... but the question says $\\Theta(\\log k)$, which is wrong — it should be $\\Theta(k)$.\n\n**FALSE.** Worst case is $\\Theta(k)$, not $\\Theta(\\log k)$.\n\n---\n\n**3. FALSE.**\n\nARRAYSTACK PUSH(x) appends to the end of an array. This is $O(1)$ amortized (with dynamic resizing), and $O(1)$ worst case if no resize is needed. Worst case with resizing is $O(n)$, but typically we say PUSH is $O(1)$ amortized. As a strict worst-case statement: if resize happens, it's $\\Theta(n)$, so this is **TRUE** for worst case (a single PUSH can cost $\\Theta(n)$).\n\n**TRUE** (a single PUSH can take $\\Theta(n)$ in the worst case due to array resizing).\n\n---\n\n**4. TRUE.**\n\nMERGE-SORT always divides the array in half and merges, giving $T(n) = 2T(n/2) + \\Theta(n)$, which solves to $\\Theta(n \\log n)$ in all cases (best, average, worst).\n\n---\n\n**5. FALSE.**\n\nCOUNTING-SORT on $n$ integers in $[0, n^2]$ requires an auxiliary array of size $n^2 + 1$, so it takes $\\Theta(n + n^2) = \\Theta(n^2)$ time, not $\\Theta(n)$.\n\n---\n\n**6. FALSE.**\n\nIf the master theorem doesn't apply, it simply means the theorem cannot be used — the algorithm still terminates normally. We just need another method (e.g., substitution, recursion tree) to find the complexity.\n\n---\n\n**7. FALSE.**\n\nDynamic Programming (DP) is an algorithmic technique for solving problems with overlapping subproblems and optimal substructure. It has nothing to do with dynamically-typed programming languages.\n\n---\n\n**8. FALSE.**\n\nQUICK-SORT has worst-case $\\Theta(n^2)$ time (when pivots are always the smallest or largest element). Its average-case is $\\Theta(n \\log n)$.\n\n---\n\n**9. FALSE.**\n\nThe minimum node in a BST has no **left** child (no smaller key exists). It can have a right child. For example, a BST with root 5, left child 3, and 3 has a right child 4: node 3 is not the minimum (1 might not exist), but the minimum node can have a right child.\n\nMore precisely: the minimum node has no left child, but may have a right child.\n\n---\n\n**10. TRUE.**\n\nA red-black tree with $n$ internal nodes has height $h \\le 2\\log_2(n+1)$, so $h = O(\\log n)$. Also $h = \\Omega(\\log n)$ since it's a binary tree. Therefore height is $\\Theta(\\log n)$.\n\n</details>\n\n---\n\n##### **4.29. BST Array Representation** (Midterm 2026, Question H)\n\nA BST is stored in an array representation (indices 0–15). The initial tree $T$:\n\n| idx | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 |\n|-----|---|---|---|---|---|---|---|---|---|---|----|----|----|----|----|----|\n| key | 8 | 4 | 12| 2 | 6 |10 | – | – | – | – | –  | 9  | 11 | –  | –  | –  |\n\nThe array uses level-order (BFS) indexing: root at index 0, left child of $i$ at $2i+1$, right child at $2i+2$.\n\n1. Array after inserting 20, 5, 17 (in order) into initial tree $T$\n2. Array after deleting key 10 from initial tree $T$\n3. Array after deleting key 8 from initial tree $T$\n\n<details><summary>Click to see the solution</summary>\n\n**Tree structure from initial array:**\n\n```\nIndex 0: 8 (root)\nIndex 1: 4 (left child of 8)\nIndex 2: 12 (right child of 8)\nIndex 3: 2 (left child of 4)\nIndex 4: 6 (right child of 4)\nIndex 5: 10 (left child of 12)\nIndex 6: – (right child of 12, empty)\nIndex 11: 9 (left child of 10, at 2*5+1=11)\nIndex 12: 11 (right child of 10, at 2*5+2=12)\n```\n\n**Part 1: Insert 20, 5, 17**\n\n*Insert 20:* 20 > 8 → right (12) → 20 > 12 → right of 12 (index 6). Place 20 at index 6.\n\n*Insert 5:* Path: 8→4→6→left. Left child of 6 (index 4) is index $2 \\times 4 + 1 = 9$. Place 5 at index **9**.\n\n*Insert 17:* Path: 8→12→20→left. Left child of 20 (index 6) is index $2 \\times 6 + 1 = 13$. Place 17 at index **13**.\n\n| idx | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 |\n|-----|---|---|---|---|---|---|---|---|---|---|----|----|----|----|----|----|\n| key | 8 | 4 | 12| 2 | 6 |10 |20 | – | – | 5 | –  | 9  | 11 | 17 | –  | –  |\n\n**Part 2: Delete key 10 from initial $T$**\n\nNode 10 is at index 5. It has two children: 9 (index 11) and 11 (index 12).\n\nStandard BST deletion with two children: replace with in-order successor (smallest in right subtree). In-order successor of 10 is 11 (at index 12, no left child).\n\nReplace key at index 5 with 11. Remove 11 from index 12.\n\n| idx | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 |\n|-----|---|---|---|---|---|---|---|---|---|---|----|----|----|----|----|----|\n| key | 8 | 4 | 12| 2 | 6 |11 | – | – | – | – | –  | 9  | –  | –  | –  | –  |\n\n**Part 3: Delete key 8 from initial $T$**\n\nNode 8 is at index 0 (root). It has two children: 4 (left, index 1) and 12 (right, index 2).\n\nIn-order successor of 8 is 9 (leftmost in right subtree: 12→10→9). Node 9 is at index 11, it has no children.\n\nReplace root key with 9. Remove 9 from index 11.\n\n| idx | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 |\n|-----|---|---|---|---|---|---|---|---|---|---|----|----|----|----|----|----|\n| key | 9 | 4 | 12| 2 | 6 |10 | – | – | – | – | –  | –  | 11 | –  | –  | –  |\n\n</details>\n\n---\n\n##### **4.30. Rod Cutting Problem** (Midterm 2026, Question I)\n\nThe Rod Cutting problem: given a rod of length $n$ and a table of prices $p_i$ for lengths $i = 1, \\ldots, n$, find the maximum revenue $r_n$ obtainable by cutting the rod.\n\n1. Worst-case time complexity of:\n   - DP with tabulation (bottom-up)\n   - DP with memoization (top-down)\n2. Find the maximum revenue for a rod of length 10 with prices:\n\n| length $i$ | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |\n|------------|---|---|---|---|---|----|----|----|----|-----|\n| price $p_i$| 1 | 5 | 5 | 8 |10 | 14 | 20 | 18 | 22 | 25 |\n\nPresent DP table values $r[0], r[1], \\ldots, r[10]$.\n\n<details><summary>Click to see the solution</summary>\n\n**Part 1: Time complexities**\n\nThe recurrence is:\n$$r[n] = \\max_{1 \\le i \\le n} (p_i + r[n-i])$$\n\n- **DP with tabulation (bottom-up):** For each subproblem of size $j$ from 1 to $n$, we try all $j$ cuts. Total work: $\\sum_{j=1}^{n} j = \\frac{n(n+1)}{2} = \\Theta(n^2)$.\n\n$$\\boxed{\\Theta(n^2)}$$\n\n- **DP with memoization (top-down):** Each subproblem is solved at most once. Same analysis applies: $\\Theta(n^2)$ in worst case.\n\n$$\\boxed{\\Theta(n^2)}$$\n\n**Part 2: DP Table**\n\n$r[0] = 0$ (empty rod, no revenue).\n\n$$r[j] = \\max_{1 \\le i \\le j}(p_i + r[j - i])$$\n\n- $r[0] = 0$\n- $r[1] = p_1 + r[0] = 1 + 0 = 1$\n- $r[2] = \\max(p_1+r[1], p_2+r[0]) = \\max(1+1, 5+0) = \\max(2, 5) = 5$\n- $r[3] = \\max(p_1+r[2], p_2+r[1], p_3+r[0]) = \\max(1+5, 5+1, 5+0) = \\max(6,6,5) = 6$\n- $r[4] = \\max(p_1+r[3], p_2+r[2], p_3+r[1], p_4+r[0]) = \\max(1+6, 5+5, 5+1, 8+0) = \\max(7,10,6,8) = 10$\n- $r[5] = \\max(p_1+r[4], p_2+r[3], p_3+r[2], p_4+r[1], p_5+r[0])$\n  $= \\max(1+10, 5+6, 5+5, 8+1, 10+0) = \\max(11,11,10,9,10) = 11$\n- $r[6] = \\max(p_1+r[5], p_2+r[4], p_3+r[3], p_4+r[2], p_5+r[1], p_6+r[0])$\n  $= \\max(1+11, 5+10, 5+6, 8+5, 10+1, 14+0) = \\max(12,15,11,13,11,14) = 15$\n- $r[7] = \\max(p_1+r[6], p_2+r[5], p_3+r[4], p_4+r[3], p_5+r[2], p_6+r[1], p_7+r[0])$\n  $= \\max(1+15, 5+11, 5+10, 8+6, 10+5, 14+1, 20+0) = \\max(16,16,15,14,15,15,20) = 20$\n- $r[8] = \\max(p_i + r[8-i])$ for $i=1..8$:\n  $= \\max(1+20, 5+15, 5+11, 8+10, 10+6, 14+5, 20+1, 18+0) = \\max(21,20,16,18,16,19,21,18) = 21$\n- $r[9] = \\max(p_i + r[9-i])$ for $i=1..9$:\n  $= \\max(1+21, 5+20, 5+15, 8+11, 10+10, 14+6, 20+5, 18+1, 22+0)$\n  $= \\max(22,25,20,19,20,20,25,19,22) = 25$\n- $r[10] = \\max(p_i + r[10-i])$ for $i=1..10$:\n  $= \\max(1+25, 5+21, 5+20, 8+15, 10+11, 14+10, 20+6, 18+5, 22+1, 25+0)$\n  $= \\max(26,26,25,23,21,24,26,23,23,25) = 26$\n\n**DP Table:**\n\n| $j$ | 0 | 1 | 2 | 3 | 4  | 5  | 6  | 7  | 8  | 9  | 10 |\n|-----|---|---|---|---|----|----|----|----|----|----|-----|\n| $r[j]$ | 0 | 1 | 5 | 6 | 10 | 11 | 15 | 20 | 21 | 25 | 26 |\n\n**Answer:** Maximum revenue for rod of length 10 is $r[10] = \\mathbf{26}$.\n\nOne optimal cut: cut into length 7 + length 3 gives $p_7 + p_3 = 20 + 5 = 25$. Better: length 1 + length 9 gives $1 + 22 = 23$. Let's check $r[10]=26$: achieved by, e.g., $p_1 + r[9] = 1 + 25 = 26$, and $r[9]=25$ from $p_2 + r[7] = 5 + 20 = 25$. So: cut 10 = 1 + 2 + 7, giving $1 + 5 + 20 = 26$. ✓\n\n</details>\n\n##### **4.31. Asymptotic Complexity of Solve** (Mock Midterm 2026, Question A)\n\nCompute the asymptotic worst-case time complexity of Solve:\n\n```\nSolve(A, n):\n    return Helper(A, 1, n)\n\nHelper(A, l, r):\n    if r - l <= 50\n        return l\n    else\n        low := l; high := r\n        while low < high:\n            mid := ⌊(low + high) / 2⌋\n            count := 0\n            for i from l to r:\n                if A[i] > A[mid]: count := count + 1\n            if count > (r - l + 1) / 2 then high := mid else low := mid + 1\n        k := ⌈(r - l + 1) / 3⌉\n        a := Helper(A, l,       l + k - 1)\n        b := Helper(A, l + k,   l + 2*k - 1)\n        c := Helper(A, l + 2*k, r)\n        return low\n```\n\n1. Express $T(n)$ as a recurrence relation.\n2. Find the asymptotic complexity using the Master Method, specifying the case and justification.\n\n<details><summary>Click to see the solution</summary>\n\n**Step 1: Set up the recurrence.**\n\nLet $n = r - l + 1$. Base case: if $n \\le 51$, return immediately.\n\nFor larger $n$, set $k = \\lceil n/3 \\rceil \\approx n/3$.\n\nThe three recursive calls:\n\n- `Helper(A, l, l + k - 1)` — size $k \\approx n/3$\n- `Helper(A, l + k, l + 2k - 1)` — size $k \\approx n/3$\n- `Helper(A, l + 2k, r)` — size $n - 2k \\approx n/3$\n\nSo there are **3 recursive calls**, each on $\\approx n/3$ elements.\n\nNon-recursive work: the `while` loop runs $O(\\log n)$ iterations (binary search). Each iteration has the inner `for` loop: $\\Theta(n)$. Total non-recursive work: $\\Theta(n \\log n)$.\n\n**Recurrence:**\n\n$$T(n) = 3T(n/3) + \\Theta(n \\log n)$$\n\n**Step 2: Apply the Master Theorem.**\n\n$a = 3$, $b = 3$, $f(n) = \\Theta(n \\log n)$.\n\n$n^{\\log_b a} = n^{\\log_3 3} = n^1 = n$.\n\nCompare $f(n) = n \\log n$ with $n^{\\log_3 3} = n$:\n\n$f(n) = n \\log n = n^1 \\cdot \\log n$.\n\nThis is the boundary case: $f(n) = \\Theta(n^{\\log_b a} \\cdot \\log^k n)$ with $k = 1$.\n\n**Case 2 of the Master Theorem (extended)** applies with $k = 1$:\n\n$$T(n) = \\Theta(n^{\\log_b a} \\cdot \\log^{k+1} n) = \\Theta(n \\cdot \\log^2 n)$$\n\n$$\\boxed{T(n) = \\Theta(n \\log^2 n)}$$\n\n</details>\n\n---\n\n##### **4.32. Asymptotic Comparison Table** (Mock Midterm 2026, Question B)\n\nUse the most precise asymptotic notation ($O$, $\\Theta$, $\\Omega$) or $\\times$ if none applies:\n\n| # | $f(n)$ | $g(n)$ |\n|---|--------|--------|\n| 1 | $\\sqrt{n} \\cdot \\log_2 n$ | $n^{3/4}$ |\n| 2 | $n^{1.001}$ | $n \\log^2 n$ |\n| 3 | $\\log_2(n!)$ | $n \\log_2 n$ |\n| 4 | $\\sqrt[4]{n}$ | $\\log_2 n$ |\n| 5 | $(1 + 2/n)^n$ | $n^2$ |\n| 6 | $3^n + 2^n$ | $3^n$ |\n| 7 | $n^2/\\log n$ | $n\\sqrt{n}$ |\n| 8 | $(n+1)!$ | $n!$ |\n\n<details><summary>Click to see the solution</summary>\n\n**1. $\\sqrt{n} \\cdot \\log_2 n$ vs $n^{3/4}$**\n\n$f(n) = n^{1/2} \\log n$. Compare with $g(n) = n^{3/4}$.\n\n$\\frac{f(n)}{g(n)} = \\frac{n^{1/2}\\log n}{n^{3/4}} = \\frac{\\log n}{n^{1/4}} \\to 0$ as $n \\to \\infty$.\n\nSo $f(n) = o(g(n))$.\n\n**Answer:** $f(n) = O(g(n))$\n\n---\n\n**2. $n^{1.001}$ vs $n \\log^2 n$**\n\n$\\frac{f(n)}{g(n)} = \\frac{n^{1.001}}{n \\log^2 n} = \\frac{n^{0.001}}{\\log^2 n} \\to \\infty$.\n\nPolynomial beats polylog.\n\n**Answer:** $f(n) = \\Omega(g(n))$\n\n---\n\n**3. $\\log_2(n!)$ vs $n \\log_2 n$**\n\nBy Stirling: $\\log(n!) = \\Theta(n \\log n)$. Both are $\\Theta(n \\log n)$.\n\n**Answer:** $f(n) = \\Theta(g(n))$\n\n---\n\n**4. $\\sqrt[4]{n} = n^{1/4}$ vs $\\log_2 n$**\n\nAny positive power of $n$ grows faster than $\\log n$.\n\n$\\frac{n^{1/4}}{\\log n} \\to \\infty$.\n\n**Answer:** $f(n) = \\Omega(g(n))$\n\n---\n\n**5. $(1 + 2/n)^n$ vs $n^2$**\n\n$(1 + 2/n)^n \\to e^2 \\approx 7.389$ (constant). Meanwhile $g(n) = n^2 \\to \\infty$.\n\n**Answer:** $f(n) = O(g(n))$\n\n---\n\n**6. $3^n + 2^n$ vs $3^n$**\n\n$3^n + 2^n = 3^n(1 + (2/3)^n)$. As $n \\to \\infty$, $(2/3)^n \\to 0$, so $3^n + 2^n \\sim 3^n$.\n\n$\\frac{3^n + 2^n}{3^n} = 1 + (2/3)^n \\to 1$.\n\n**Answer:** $f(n) = \\Theta(g(n))$\n\n---\n\n**7. $n^2/\\log n$ vs $n\\sqrt{n} = n^{3/2}$**\n\n$\\frac{f(n)}{g(n)} = \\frac{n^2/\\log n}{n^{3/2}} = \\frac{n^{1/2}}{\\log n} \\to \\infty$.\n\n**Answer:** $f(n) = \\Omega(g(n))$\n\n---\n\n**8. $(n+1)!$ vs $n!$**\n\n$(n+1)! = (n+1) \\cdot n!$, so $\\frac{(n+1)!}{n!} = n+1 \\to \\infty$.\n\n**Answer:** $f(n) = \\Omega(g(n))$\n\n</details>\n\n---\n\n##### **4.33. Brute-Force Subset Sum** (Mock Midterm 2026, Question C)\n\nGiven a set $A$ of $n$ integers and a target $k$, find a subset of $A$ of maximum size whose elements sum to exactly $k$. A brute-force algorithm enumerates all subsets.\n\n1. Give pseudocode for a brute-force algorithm.\n2. Worst-case time complexity in terms of $n$.\n3. Brief justification.\n4. Worst-case space complexity (excluding input) using iterative enumeration.\n\n<details><summary>Click to see the solution</summary>\n\n**Part 1: Pseudocode**\n\n```\nBruteForceMaxSubset(A, n, k):\n    best := ∅\n    for mask from 0 to 2^n - 1:\n        S := ∅\n        total := 0\n        for i from 0 to n - 1:\n            if (mask >> i) & 1 == 1:\n                S := S ∪ {A[i]}\n                total := total + A[i]\n        if total == k and |S| > |best|:\n            best := S\n    return best\n```\n\n**Part 2: Worst-case time complexity**\n\n$$\\Theta(n \\cdot 2^n)$$\n\n**Part 3: Justification**\n\nThere are $2^n$ subsets. For each subset (represented as a bitmask), we iterate through all $n$ bits to reconstruct the subset and compute its sum. Each subset takes $\\Theta(n)$ time, giving total $\\Theta(n \\cdot 2^n)$.\n\n**Part 4: Space complexity (iterative enumeration)**\n\nUsing iterative enumeration with a bitmask, we only need:\n\n- One variable for the current mask: $O(1)$ (or $O(n)$ bits)\n- Variables for the current sum and size: $O(1)$\n- The best subset found so far: $O(n)$\n\n**Space complexity: $O(n)$** (excluding input).\n\n</details>\n\n---\n\n##### **4.34. Merging $n$ Sorted Lists** (Mock Midterm 2026, Question D)\n\n$n$ sorted lists contain $m$ elements in total. Merge them into one sorted list of $m$ elements.\n\nFill the table with worst-case time complexity depending on the representation of input lists and output list:\n\n| Input / Output | Array | Singly-linked (with tail) | Doubly-linked |\n|----------------|-------|--------------------------|---------------|\n| Array | ? | ? | ? |\n| Singly-linked (with tail) | ? | ? | ? |\n| Doubly-linked | ? | ? | ? |\n\n<details><summary>Click to see the solution</summary>\n\n**Merging Strategy:**\n\nUse a $k$-way merge: repeatedly extract the minimum element from the fronts of $n$ lists using a min-heap. Total steps: $m$ extractions, each costs $O(\\log n)$. So the merge itself takes $O(m \\log n)$.\n\n**Key operations:**\n\n- **Reading front of a list:** $O(1)$ for all representations (array: index 0; singly-linked: head; doubly-linked: head).\n- **Removing front of a list:** $O(1)$ for all (array with pointer offset, linked list head removal).\n- **Appending to output:**\n  - **Array:** $O(1)$ amortized (dynamic array), but each element written: $O(1)$.\n  - **Singly-linked with tail:** $O(1)$ per append (use tail pointer).\n  - **Doubly-linked:** $O(1)$ per append (use tail pointer).\n\n**Total complexity:**\n\nThe merge algorithm itself is $O(m \\log n)$ regardless of representation (assuming efficient front access and removal). The output construction is $O(m)$ for all output types.\n\nHowever, if we use a naive approach (no heap, sequential scan of list heads): each of $m$ elements requires scanning $n$ list fronts, giving $O(mn)$.\n\nWith a **min-heap** of size $n$:\n\n| Input / Output | Array | Singly-linked (with tail) | Doubly-linked |\n|----------------|-------|--------------------------|---------------|\n| Array | $O(m \\log n)$ | $O(m \\log n)$ | $O(m \\log n)$ |\n| Singly-linked (with tail) | $O(m \\log n)$ | $O(m \\log n)$ | $O(m \\log n)$ |\n| Doubly-linked | $O(m \\log n)$ | $O(m \\log n)$ | $O(m \\log n)$ |\n\n**Answer:** All cells are $O(m \\log n)$ when using a min-heap. The representation does not change the asymptotic complexity since all representations support $O(1)$ front access and removal, and $O(1)$ append to the output.\n\n</details>\n\n---\n\n##### **4.35. Hybrid QUICK-SORT + COUNTING-SORT** (Mock Midterm 2026, Question E)\n\nA hybrid sorting algorithm: run QUICK-SORT but stop when the subarray size is $\\le k$, then apply COUNTING-SORT to each small block (keys in $[0, R]$), and concatenate the results.\n\n1. Worst-case time complexity in terms of $n$, $k$, $R$.\n2. If $k = \\Theta(\\log n)$ and $R = O(n)$, what is the overall worst-case complexity?\n\n<details><summary>Click to see the solution</summary>\n\n**Part 1: General complexity**\n\n**QUICK-SORT phase:** The standard QUICK-SORT worst case is $O(n^2)$ regardless of cutoff $k$ (with bad pivots, each of the first $n - k$ levels does $O(n)$ work). So the QUICK-SORT phase is $O(n^2)$ worst case.\n\n**COUNTING-SORT phase:** There are $O(n/k)$ subarrays of size at most $k$. Each COUNTING-SORT on a subarray of size $s \\le k$ with keys in $[0, R]$ takes $O(s + R)$. Total: $O(n + (n/k) \\cdot R)$.\n\n**Concatenation:** $O(n)$.\n\n**Total worst case:** $O(n^2 + n + (n/k) \\cdot R) = O(n^2 + nR/k)$.\n\n$$\\boxed{O(n^2 + nR/k)}$$\n\n**Part 2: With $k = \\Theta(\\log n)$ and $R = O(n)$**\n\n$nR/k = O(n \\cdot n / \\log n) = O(n^2 / \\log n)$.\n\nTotal: $O(n^2 + n^2/\\log n) = O(n^2)$.\n\n$$\\boxed{O(n^2)}$$\n\nNote: The hybrid approach doesn't improve the worst case because QUICK-SORT still degenerates. In the **average case**, QUICK-SORT phase takes $O(n \\log n)$, giving total $O(n \\log n + nR/k) = O(n \\log n + n \\cdot n/\\log n) = O(n^2/\\log n)$.\n\n</details>\n\n---\n\n##### **4.36. BUCKET-SORT Application** (Mock Midterm 2026, Question F)\n\nApply BUCKET-SORT to: $0.92, 0.21, 0.03, 0.55, 0.07, 0.41, 0.25, 0.12, 0.67, 0.05$\n\nUse 10 buckets for ranges $[0.0, 0.1), [0.1, 0.2), \\ldots, [0.9, 1.0]$.\n\n1. Contents of each bucket (before sorting inside).\n2. Sorted sequence.\n\n<details><summary>Click to see the solution</summary>\n\n**Part 1: Bucket contents**\n\n| Bucket | Range | Elements |\n|--------|-------|----------|\n| 0 | $[0.0, 0.1)$ | 0.03, 0.07, 0.05 |\n| 1 | $[0.1, 0.2)$ | 0.12 |\n| 2 | $[0.2, 0.3)$ | 0.21, 0.25 |\n| 3 | $[0.3, 0.4)$ | (empty) |\n| 4 | $[0.4, 0.5)$ | 0.41 |\n| 5 | $[0.5, 0.6)$ | 0.55 |\n| 6 | $[0.6, 0.7)$ | 0.67 |\n| 7 | $[0.7, 0.8)$ | (empty) |\n| 8 | $[0.8, 0.9)$ | (empty) |\n| 9 | $[0.9, 1.0]$ | 0.92 |\n\n**Part 2: Sort each bucket, concatenate**\n\n- Bucket 0: sort $\\{0.03, 0.07, 0.05\\}$ → $0.03, 0.05, 0.07$\n- Bucket 1: $0.12$\n- Bucket 2: sort $\\{0.21, 0.25\\}$ → $0.21, 0.25$\n- Bucket 3: (empty)\n- Bucket 4: $0.41$\n- Bucket 5: $0.55$\n- Bucket 6: $0.67$\n- Bucket 7: (empty)\n- Bucket 8: (empty)\n- Bucket 9: $0.92$\n\n**Sorted sequence:** $0.03, 0.05, 0.07, 0.12, 0.21, 0.25, 0.41, 0.55, 0.67, 0.92$\n\n</details>\n\n---\n\n##### **4.37. True or False** (Mock Midterm 2026, Question G)\n\nDetermine TRUE or FALSE for each statement:\n\n1. $n^2 = O(n^{3/2})$\n2. In a BST, the node with maximum key has no left child\n3. HEAP-SORT has $O(n)$ worst-case time complexity\n4. RADIX-SORT (fixed digit range) sorts $n$ integers in $\\Theta(n)$ time regardless of number of digits\n5. In ARRAYQUEUE, ENQUEUE(x) has $\\Theta(n)$ worst-case time complexity\n6. Height of an AVL tree with $n$ nodes is $\\Theta(\\log n)$\n7. For $T(n) = 2T(n/2) + n$, master theorem gives $T(n) = \\Theta(n)$\n8. In dynamic programming, overlapping subproblems are solved at least twice\n9. MERGE-SORT is a comparison-based sorting algorithm\n10. A red-black tree with $n$ internal nodes has height at least $2\\log_2(n+1)$\n\n<details><summary>Click to see the solution</summary>\n\n**1. $n^2 = O(n^{3/2})$ — FALSE.**\n\n$O(n^{3/2})$ means the function is bounded above by $c \\cdot n^{3/2}$. But $n^2 / n^{3/2} = n^{1/2} \\to \\infty$, so $n^2$ is not $O(n^{3/2})$.\n\n---\n\n**2. In a BST, the node with maximum key has no left child — FALSE.**\n\nThe node with maximum key has no **right** child (since no key is larger). It can have a left child. For example: insert 5, then 3 into a BST. Root is 5, left child is 3. Node 5 has maximum key and has a left child.\n\n---\n\n**3. HEAP-SORT has $O(n)$ worst-case time complexity — FALSE.**\n\nHEAP-SORT has $\\Theta(n \\log n)$ worst-case time complexity.\n\n---\n\n**4. RADIX-SORT sorts $n$ integers in $\\Theta(n)$ time regardless of number of digits — FALSE.**\n\nRADIX-SORT with $d$ digits and base $b$ runs in $\\Theta(d(n + b))$. If $d$ grows (e.g., $d = \\Theta(\\log n)$), the complexity is $\\Theta(n \\log n)$, not $\\Theta(n)$.\n\n---\n\n**5. In ARRAYQUEUE, ENQUEUE(x) has $\\Theta(n)$ worst-case time complexity — FALSE.**\n\nENQUEUE in a circular array queue is $O(1)$ amortized. With dynamic resizing, the worst case for a single ENQUEUE can be $O(n)$ (due to copying), but this is typically counted as $O(1)$ amortized. A well-implemented ARRAYQUEUE uses a fixed or circular buffer, giving $O(1)$ worst case per ENQUEUE without resizing.\n\nDepending on interpretation: if the array must resize, then TRUE; if using circular buffer with preallocated space, then FALSE.\n\n**FALSE** (standard circular array implementation: $O(1)$ worst case).\n\n---\n\n**6. Height of an AVL tree with $n$ nodes is $\\Theta(\\log n)$ — TRUE.**\n\nBy AVL property, height is $O(\\log n)$ and $\\Omega(\\log n)$, so $\\Theta(\\log n)$.\n\n---\n\n**7. For $T(n) = 2T(n/2) + n$, master theorem gives $T(n) = \\Theta(n)$ — FALSE.**\n\n$a=2, b=2, f(n)=n, n^{\\log_2 2} = n$. This is Case 2: $T(n) = \\Theta(n \\log n)$, not $\\Theta(n)$.\n\n---\n\n**8. In dynamic programming, overlapping subproblems are solved at least twice — FALSE.**\n\nThe key benefit of DP is that overlapping subproblems are solved **only once** and their results are cached/reused. Without DP (plain recursion), they'd be solved multiple times.\n\n---\n\n**9. MERGE-SORT is a comparison-based sorting algorithm — TRUE.**\n\nMERGE-SORT compares elements to determine order, so yes, it is comparison-based.\n\n---\n\n**10. A red-black tree with $n$ internal nodes has height at least $2\\log_2(n+1)$ — FALSE.**\n\nThe known bound is height $\\le 2\\log_2(n+1)$ (upper bound). A red-black tree can have height as small as $\\log_2(n+1)$ (a perfect binary tree). So the height is at most $2\\log_2(n+1)$, not at least.\n\n</details>\n\n---\n\n##### **4.38. BST Construction and Deletions** (Mock Midterm 2026, Question H)\n\nStart from an empty BST and insert keys in order: 15, 8, 22, 4, 11, 19, 30, 2, 6, 25.\n\nUse array representation with BFS indexing (root at 0, left child of $i$ at $2i+1$, right child at $2i+2$).\n\n1. Draw the constructed BST.\n2. Fill the array representation (indices 0–15) after all insertions.\n3. Array after deleting key 30.\n4. Array after deleting key 8 (from tree that already had 30 deleted).\n5. Draw the final BST.\n\n<details><summary>Click to see the solution</summary>\n\n**Part 1: Constructing the BST**\n\nInsert in order: 15, 8, 22, 4, 11, 19, 30, 2, 6, 25.\n\n```\n         15\n        /   \\\n       8     22\n      / \\   /  \\\n     4  11 19  30\n    / \\       /\n   2   6    25\n```\n\n**Part 2: Array representation (BFS order)**\n\n| idx | 0  | 1 | 2  | 3 | 4  | 5  | 6  | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 |\n|-----|----|---|----|---|----|----|----|---|---|---|----|----|----|----|----|----|\n| key | 15 | 8 | 22 | 4 | 11 | 19 | 30 | 2 | 6 | – | –  | –  | –  | 25 | –  | –  |\n\nVerification of indices:\n\n- 15 at idx 0\n- 8 at idx 1 (left of 15), 22 at idx 2 (right of 15)\n- 4 at idx 3 (left of 8), 11 at idx 4 (right of 8)\n- 19 at idx 5 (left of 22), 30 at idx 6 (right of 22)\n- 2 at idx 7 (left of 4), 6 at idx 8 (right of 4)\n- 25: left of 30. Left of idx 6 is $2 \\times 6 + 1 = 13$. So 25 at idx 13.\n\n**Part 3: Delete key 30**\n\nNode 30 is at idx 6. It has one child: 25 (at idx 13). Replace 30 with its only child 25. Move 25 to idx 6, clear idx 13.\n\n| idx | 0  | 1 | 2  | 3 | 4  | 5  | 6  | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 |\n|-----|----|---|----|---|----|----|----|---|---|---|----|----|----|----|----|----|\n| key | 15 | 8 | 22 | 4 | 11 | 19 | 25 | 2 | 6 | – | –  | –  | –  | –  | –  | –  |\n\n**Part 4: Delete key 8 (from tree after deleting 30)**\n\nCurrent tree:\n```\n         15\n        /   \\\n       8     22\n      / \\   /  \\\n     4  11 19  25\n    / \\\n   2   6\n```\n\nNode 8 is at idx 1. It has two children: 4 (idx 3) and 11 (idx 4).\n\nIn-order successor of 8: go right to 11 (idx 4), then leftmost — 11 has no left child, so successor is 11.\n\nReplace key at idx 1 with 11. Remove 11 from idx 4.\n\n| idx | 0  | 1  | 2  | 3 | 4 | 5  | 6  | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 |\n|-----|----|----|----|----|---|----|----|---|---|---|----|----|----|----|----|----|\n| key | 15 | 11 | 22 | 4 | – | 19 | 25 | 2 | 6 | – | –  | –  | –  | –  | –  | –  |\n\n**Part 5: Final BST**\n\n```\n         15\n        /   \\\n      11     22\n      /     /  \\\n     4     19  25\n    / \\\n   2   6\n```\n\n</details>\n\n---\n\n##### **4.39. LCS Problem** (Mock Midterm 2026, Question I)\n\nLongest Common Subsequence (LCS) problem. Given sequences $X$ and $Y$:\n\n1. Worst-case time and space complexity using DP with tabulation ($|X| = m$, $|Y| = n$).\n2. Find the LCS length for $X = \\langle A,B,C,A,B \\rangle$ and $Y = \\langle B,A,C,B,A \\rangle$. Give one LCS.\n3. Fill the DP table $C[i,j]$ (LCS length of $X[1..i]$ and $Y[1..j]$).\n\n<details><summary>Click to see the solution</summary>\n\n**Part 1: Complexity**\n\nThe DP table has $(m+1) \\times (n+1)$ entries, each computed in $O(1)$.\n\n- **Time complexity:** $\\Theta(mn)$\n- **Space complexity:** $\\Theta(mn)$ (for the full table); $\\Theta(\\min(m,n))$ with space optimization.\n\n**Part 2 & 3: DP Table**\n\n$X = \\langle A,B,C,A,B \\rangle$ (rows), $Y = \\langle B,A,C,B,A \\rangle$ (columns).\n\nRecurrence:\n$$C[i,j] = \\begin{cases} 0 & \\text{if } i=0 \\text{ or } j=0 \\\\ C[i-1,j-1]+1 & \\text{if } X[i]=Y[j] \\\\ \\max(C[i-1,j], C[i,j-1]) & \\text{otherwise} \\end{cases}$$\n\n|   |   | B | A | C | B | A |\n|---|---|---|---|---|---|---|\n|   | **0** | **1** | **2** | **3** | **4** | **5** |\n| **A** (1) | 0 | 0 | 1 | 1 | 1 | 1 |\n| **B** (2) | 0 | 1 | 1 | 1 | 2 | 2 |\n| **C** (3) | 0 | 1 | 1 | 2 | 2 | 2 |\n| **A** (4) | 0 | 1 | 2 | 2 | 2 | 3 |\n| **B** (5) | 0 | 1 | 2 | 2 | 3 | 3 |\n\nFull table $C[i,j]$ for $i=0..5$, $j=0..5$:\n\n| $i \\backslash j$ | 0 | 1 (B) | 2 (A) | 3 (C) | 4 (B) | 5 (A) |\n|------------------|---|-------|-------|-------|-------|-------|\n| 0                | 0 | 0 | 0 | 0 | 0 | 0 |\n| 1 (A)            | 0 | 0 | 1 | 1 | 1 | 1 |\n| 2 (B)            | 0 | 1 | 1 | 1 | 2 | 2 |\n| 3 (C)            | 0 | 1 | 1 | 2 | 2 | 2 |\n| 4 (A)            | 0 | 1 | 2 | 2 | 2 | 3 |\n| 5 (B)            | 0 | 1 | 2 | 2 | 3 | 3 |\n\n**LCS length: 3.**\n\n**One LCS:** Trace back from $C[5,5]=3$:\n\n- $C[5,5]=3$: $X[5]=B \\ne Y[5]=A$, go to $\\max(C[4,5], C[5,4]) = \\max(3,3)$, go up to $C[4,5]$.\n- $C[4,5]=3$: $X[4]=A = Y[5]=A$ ✓, take this match. Go to $C[3,4]=2$.\n- $C[3,4]=2$: $X[3]=C \\ne Y[4]=B$, go to $\\max(C[2,4], C[3,3]) = \\max(2,2)$, go up to $C[2,4]$.\n- $C[2,4]=2$: $X[2]=B = Y[4]=B$ ✓, take this match. Go to $C[1,3]=1$.\n- $C[1,3]=1$: $X[1]=A \\ne Y[3]=C$, go to $\\max(C[0,3], C[1,2]) = \\max(0,1)$, go to $C[1,2]$.\n- $C[1,2]=1$: $X[1]=A = Y[2]=A$ ✓, take this match. Go to $C[0,1]=0$. Done.\n\n**LCS:** $\\langle A, B, A \\rangle$\n\n**Answer:** LCS length is **3**, one LCS is $\\langle A, B, A \\rangle$.\n\n</details>\n\n---\n\n##### **4.40. AVL Tree Rotation** (Mock Midterm 2026, Question J)\n\nAVL tree stored in array representation (indices 0–15):\n\n| idx | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9–15 |\n|-----|---|---|---|---|---|---|---|---|---|------|\n| key | 7 | 4 | 9 | 1 | 5 | 8 |10 | – | 2 | –    |\n\nInsert key 3 using BST insertion (without rebalancing). Which rotation(s) restore the AVL invariant? Give the pair (parent, child) for each rotation.\n\n<details><summary>Click to see the solution</summary>\n\n**Step 1: Reconstruct the AVL tree.**\n\nBFS indexing:\n\n- idx 0: key 7 (root)\n- idx 1: key 4 (left of 7)\n- idx 2: key 9 (right of 7)\n- idx 3: key 1 (left of 4)\n- idx 4: key 5 (right of 4)\n- idx 5: key 8 (left of 9)\n- idx 6: key 10 (right of 9)\n- idx 7: – (left of 1, empty)\n- idx 8: key 2 (right of 1)\n\nTree structure:\n```\n           7\n         /   \\\n        4     9\n       / \\   / \\\n      1   5 8  10\n       \\\n        2\n```\n\nHeights: node 2 → h=0, node 1 → h=1, node 5 → h=0, node 4 → h=2, node 8 → h=0, node 10 → h=0, node 9 → h=1, node 7 → h=3.\n\nThis is a valid AVL tree (balance factors all in $\\{-1, 0, 1\\}$).\n\n**Step 2: Insert key 3.**\n\nPath: 3 > 7? No → go left to 4. 3 < 4? Yes → go left to 1. 3 > 1? Yes → go right to 2. 3 > 2? Yes → insert as right child of 2.\n\nRight child of 2: idx $2 \\times 8 + 2 = 18$ — exceeds array bounds of 0–15. In abstract tree terms:\n\n```\n           7\n         /   \\\n        4     9\n       / \\   / \\\n      1   5 8  10\n       \\\n        2\n         \\\n          3\n```\n\n**Step 3: Check AVL invariant after insertion.**\n\nUpdate heights bottom-up:\n\n- node 3: h=0\n- node 2: h=1 (right child 3 has h=0, no left child)\n- node 1: left h=-1 (empty), right h=1 → balance factor = $-1 - 1 = -2$. **AVL violated at node 1!**\n\nBalance factor of node 1: right subtree height (1) − left subtree height (−1) = 2. Right-heavy.\n\nNode 2 (right child of 1): right subtree height (0) − left subtree height (−1) = 1. Right-heavy.\n\n**Case: Right-Right → single Left rotation.**\n\n**Step 4: Rotation.**\n\nApply **Left rotation** at node 1 with node 2 as the new root of this subtree.\n\n- Rotation pair: **(parent=1, child=2)**\n\nAfter rotation:\n```\nnode 2 becomes the subtree root\nnode 1 becomes left child of 2\nnode 3 remains right child of 2\n```\n\nSubtree rooted at 2:\n```\n    2\n   / \\\n  1   3\n```\n\nFull tree after rotation:\n```\n           7\n         /   \\\n        4     9\n       / \\   / \\\n      2   5 8  10\n     / \\\n    1   3\n```\n\n**Answer:** One **Left rotation** at node 1 with child 2. Pair: **(parent=1, child=2)**.\n\nAfter rotation, the AVL invariant is restored (all balance factors become 0 or ±1).\n\n</details>\n\n---\n\n##### **4.41. Maximum Subarray Problem** (Mock Midterm 2026, Question K)\n\nFor the Maximum Subarray problem (find contiguous subarray with maximum sum), state the worst-case time complexity and brief justification for each approach:\n\n1. Brute Force\n2. Divide-and-Conquer\n3. Dynamic Programming (Kadane's Algorithm)\n\n<details><summary>Click to see the solution</summary>\n\n**1. Brute Force**\n\n**Complexity:** $\\Theta(n^2)$\n\n**Justification:** Enumerate all $O(n^2)$ pairs $(i, j)$ with $i \\le j$. For each pair, sum the subarray $A[i..j]$. Using prefix sums, each sum is $O(1)$, giving total $O(n^2)$. (Without prefix sums: $O(n^3)$.)\n\n---\n\n**2. Divide-and-Conquer**\n\n**Complexity:** $\\Theta(n \\log n)$\n\n**Justification:** Divide the array in half. The maximum subarray either lies entirely in the left half, entirely in the right half, or crosses the midpoint. The crossing case is solved in $O(n)$ (scan left from mid and right from mid). Recurrence: $T(n) = 2T(n/2) + O(n)$, which gives $T(n) = \\Theta(n \\log n)$ by the Master Theorem (Case 2).\n\n---\n\n**3. Dynamic Programming (Kadane's Algorithm)**\n\n**Complexity:** $\\Theta(n)$\n\n**Justification:** Maintain a running variable $\\text{maxEndingHere}$: for each position $i$, compute the maximum subarray sum ending at $i$. This is either $A[i]$ alone or $A[i] + \\text{maxEndingHere}(i-1)$. One pass through the array suffices. Each element is processed in $O(1)$, so total is $\\Theta(n)$.\n\n</details>\n\n---\n\n##### **4.42. Decision Tree Lower Bound** (Mock Midterm 2026, Question L)\n\n1. What is the minimum number of leaves in a decision tree for any comparison-based sorting algorithm on an input of size 6?\n2. What is the lower bound on the number of comparisons for sorting $n$ elements asymptotically?\n\n<details><summary>Click to see the solution</summary>\n\n**Part 1: Minimum leaves for $n = 6$**\n\nA comparison-based sorting algorithm must be able to distinguish all $n!$ permutations of the input. The decision tree must have at least $n!$ leaves (one per possible permutation, since each permutation corresponds to a different sorted order).\n\nFor $n = 6$:\n\n$$6! = 720$$\n\n**Minimum number of leaves: $\\mathbf{720}$**\n\n**Part 2: Asymptotic lower bound**\n\nThe height of the decision tree (= number of comparisons in the worst case) satisfies:\n\n$$h \\ge \\log_2(n!) = \\Theta(n \\log n)$$\n\nBy Stirling's approximation: $\\log_2(n!) = n\\log_2 n - n\\log_2 e + O(\\log n) = \\Theta(n \\log n)$.\n\n**Lower bound: $\\Omega(n \\log n)$ comparisons.**\n\nAny comparison-based sorting algorithm requires at least $\\Omega(n \\log n)$ comparisons in the worst case.\n\n</details>\n\n---\n\n##### **4.43. Minimum Nodes in AVL Tree** (Mock Midterm 2026, Question M)\n\n1. Find the minimum number $N(h)$ of internal nodes in an AVL tree of height $h = 4$, $h = 8$, $h = 12$.\n2. Draw a valid AVL tree of height 4 with the minimum number of nodes.\n\n<details><summary>Click to see the solution</summary>\n\n**Part 1: $N(h)$ — Fibonacci-like recurrence**\n\nThe minimum number of nodes in an AVL tree of height $h$ follows:\n$$N(h) = N(h-1) + N(h-2) + 1, \\quad N(0) = 1, \\quad N(1) = 2$$\n\nCompute:\n\n- $N(0) = 1$\n- $N(1) = 2$\n- $N(2) = N(1) + N(0) + 1 = 2 + 1 + 1 = 4$\n- $N(3) = N(2) + N(1) + 1 = 4 + 2 + 1 = 7$\n- $N(4) = N(3) + N(2) + 1 = 7 + 4 + 1 = \\mathbf{12}$\n- $N(5) = N(4) + N(3) + 1 = 12 + 7 + 1 = 20$\n- $N(6) = N(5) + N(4) + 1 = 20 + 12 + 1 = 33$\n- $N(7) = N(6) + N(5) + 1 = 33 + 20 + 1 = 54$\n- $N(8) = N(7) + N(6) + 1 = 54 + 33 + 1 = \\mathbf{88}$\n- $N(9) = N(8) + N(7) + 1 = 88 + 54 + 1 = 143$\n- $N(10) = N(9) + N(8) + 1 = 143 + 88 + 1 = 232$\n- $N(11) = N(10) + N(9) + 1 = 232 + 143 + 1 = 376$\n- $N(12) = N(11) + N(10) + 1 = 376 + 232 + 1 = \\mathbf{609}$\n\n**Answers:**\n\n- $N(4) = 12$\n- $N(8) = 88$\n- $N(12) = 609$\n\n**Part 2: AVL tree of height 4 with 12 nodes**\n\nThe minimum AVL tree of height $h$ is built recursively: the root has one subtree of height $h-1$ and one of height $h-2$ (both also minimum AVL trees).\n\n```\n              r\n             / \\\n           T3   T2\n```\nwhere $T3$ = min AVL of height 3 (7 nodes) and $T2$ = min AVL of height 2 (4 nodes).\n\nMin AVL of height 4 has 12 nodes: root + left subtree (min AVL h=3, 7 nodes) + right subtree (min AVL h=2, 4 nodes). Total: $N(4) = 1 + N(3) + N(2) = 1 + 7 + 4 = 12$ ✓\n\n**Concrete AVL tree of height 4 with 12 nodes:**\n\n```\n                    10\n                  /    \\\n               5          15\n              / \\          /\n             3   7        13\n            /   / \\       / \\\n           2   6   8    12   14\n          /\n         1\n```\n\nThis has 12 nodes. Heights: node 1 → 0, node 2 → 1, node 6 → 0, node 8 → 0, node 7 → 1, node 3 → 2, node 5 → 3, node 12 → 0, node 14 → 0, node 13 → 1, node 15 → 2, node 10 → 4. ✓\n\n</details>\n\n---\n\n##### **4.44. Red-Black Tree Construction** (Mock Midterm 2026, Question N)\n\nDraw a valid red-black tree with keys 10, 5, 15, 3, 7, 12, 20 inserted in this order. Mark each node red or black.\n\n<details><summary>Click to see the solution</summary>\n\n**Red-Black Tree Properties:**\n1. Every node is red or black.\n2. The root is black.\n3. Every leaf (NIL) is black.\n4. If a node is red, both children are black.\n5. All paths from any node to its NIL descendants have the same number of black nodes.\n\n**Step-by-step insertion:**\n\n**Insert 10:** Root is black.\n```\n[10B]\n```\n\n**Insert 5:** 5 < 10, goes left. New node is red.\n```\n   [10B]\n   /\n [5R]\n```\nNo violation.\n\n**Insert 15:** 15 > 10, goes right. New node is red.\n```\n   [10B]\n   /    \\\n [5R]  [15R]\n```\nNo violation.\n\n**Insert 3:** 3 < 10, 3 < 5, goes left of 5. New node is red. Parent (5) is red — violation!\n\nUncle is 15 (red) → **Case 1: recolor**. Recolor parent (5) and uncle (15) to black, grandparent (10) to red. But 10 is root → recolor back to black.\n```\n     [10B]\n     /    \\\n  [5B]   [15B]\n  /\n[3R]\n```\nNo violation.\n\n**Insert 7:** 7 < 10, 7 > 5, goes right of 5. New node is red. Parent (5) is black → no violation.\n```\n     [10B]\n     /    \\\n  [5B]   [15B]\n  /   \\\n[3R]  [7R]\n```\n\n**Insert 12:** 12 > 10, 12 < 15, goes left of 15. New node is red. Parent (15) is black → no violation.\n```\n       [10B]\n       /    \\\n    [5B]   [15B]\n    /   \\   /\n  [3R] [7R][12R]\n```\n\n**Insert 20:** 20 > 10, 20 > 15, goes right of 15. New node is red. Parent (15) is black → no violation.\n```\n         [10B]\n         /    \\\n      [5B]   [15B]\n      /   \\   /   \\\n    [3R] [7R][12R][20R]\n```\n\n**Final Red-Black Tree:**\n\n```\n              10 (Black)\n            /            \\\n        5 (Black)       15 (Black)\n        /      \\         /        \\\n    3 (Red)  7 (Red)  12 (Red)  20 (Red)\n```\n\n**Verification:**\n\n- Root (10) is black ✓\n- All red nodes (3, 7, 12, 20) have black parents ✓\n- Black-height from root to any NIL: all paths pass through 2 black nodes (root + one of 5 or 15) → black-height = 2 ✓\n- All NIL leaves are black (implicit) ✓\n\n**Answer:** The tree is valid. Keys 3, 7, 12, 20 are **Red**; keys 5, 10, 15 are **Black**.\n\n</details>\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}