project:
  type: website
  title: "InnoNotes"
  
website:
  google-analytics: G-H1WYLNDN76
  favicon: logo.svg
  page-footer: "🤘"
  sidebar:
    search: true
    tools:
      - icon: telegram
        href: https://t.me/p0dyakov
      - icon: github
        href: https://github.com/p0dyakov/inno_notes
    style: "docked"
    contents:
      - section: "Data Structures and Algorithms"
        contents:
          - file: "Data Structures and Algorithms/1.qmd"
          - file: "Data Structures and Algorithms/2.qmd"
          - file: "Data Structures and Algorithms/3.qmd"
      - section: "Analytical Geometry and Linear Algebra II"
        contents:
          - file: "Analytical Geometry and Linear Algebra II/0.qmd"
          - file: "Analytical Geometry and Linear Algebra II/1.qmd"
          - file: "Analytical Geometry and Linear Algebra II/2.qmd"
      - section: "Mathematical Analysis II"
        contents:
          - file: "Mathematical Analysis II/0.qmd"
          - file: "Mathematical Analysis II/1.qmd"
      - section: "Software Systems Analysis and Design"
        contents:
          - file: "Software Systems Analysis and Design/1.qmd"
          - file: "Software Systems Analysis and Design/2.qmd"
          - file: "Software Systems Analysis and Design/3.qmd"
      - section: "Theoretical Computer Science"
        contents:
          - file: "Theoretical Computer Science/1.qmd"
          - file: "Theoretical Computer Science/2.qmd"
      - section: "Analytical Geometry and Linear Algebra I"
        contents:
          - file: "Analytical Geometry and Linear Algebra I/0.qmd"
          - file: "Analytical Geometry and Linear Algebra I/1.qmd"
          - file: "Analytical Geometry and Linear Algebra I/2.qmd"
          - file: "Analytical Geometry and Linear Algebra I/3.qmd"
          - file: "Analytical Geometry and Linear Algebra I/4.qmd"
          - file: "Analytical Geometry and Linear Algebra I/5.qmd"
          - file: "Analytical Geometry and Linear Algebra I/6.qmd"
          - file: "Analytical Geometry and Linear Algebra I/7.qmd"
          - file: "Analytical Geometry and Linear Algebra I/8.qmd"
          - file: "Analytical Geometry and Linear Algebra I/9.qmd"
          - file: "Analytical Geometry and Linear Algebra I/10.qmd"
          - file: "Analytical Geometry and Linear Algebra I/11.qmd"
      - section: "Mathematical Analysis I"
        contents:
          - file: "Mathematical Analysis I/0.qmd"
          - file: "Mathematical Analysis I/1.qmd"
          - file: "Mathematical Analysis I/2.qmd"
          - file: "Mathematical Analysis I/3.qmd"
          - file: "Mathematical Analysis I/4.qmd"
          - file: "Mathematical Analysis I/5.qmd"
          - file: "Mathematical Analysis I/6.qmd"
      - section: "Introduction to Programming"
        contents:
          - file: "Introduction to Programming/0.qmd"
          - file: "Introduction to Programming/1.qmd"
          - file: "Introduction to Programming/2.qmd"
          - file: "Introduction to Programming/3.qmd"
          - file: "Introduction to Programming/4.qmd"
          - file: "Introduction to Programming/5.qmd"
          - file: "Introduction to Programming/6.qmd"
          - file: "Introduction to Programming/7.qmd"
          - file: "Introduction to Programming/8.qmd"
          - file: "Introduction to Programming/9.qmd"
          - file: "Introduction to Programming/10.qmd"
          - file: "Introduction to Programming/11.qmd"
          - file: "Introduction to Programming/12.qmd"
          - file: "Introduction to Programming/13.qmd"
      - section: "Computer Architecture"
        contents:
          - file: "Computer Architecture/1.qmd"
          - file: "Computer Architecture/2.qmd"
          - file: "Computer Architecture/3.qmd"
          - file: "Computer Architecture/4.qmd"
          - file: "Computer Architecture/5.qmd"
          - file: "Computer Architecture/6.qmd"
          - file: "Computer Architecture/7.qmd"
          - file: "Computer Architecture/8.qmd"
          - file: "Computer Architecture/9.qmd"
          - file: "Computer Architecture/10.qmd"
          - file: "Computer Architecture/11.qmd"
          - file: "Computer Architecture/12.qmd"
      - section: "Academic Writing and Argumentation I"
        contents:
          - file: "Academic Writing and Argumentation I/1.qmd"
          - file: "Academic Writing and Argumentation I/2.qmd"
          - file: "Academic Writing and Argumentation I/3.qmd"
          - file: "Academic Writing and Argumentation I/4.qmd"
          - file: "Academic Writing and Argumentation I/5.qmd"
          - file: "Academic Writing and Argumentation I/6.qmd"
          - file: "Academic Writing and Argumentation I/7.qmd"
          - file: "Academic Writing and Argumentation I/8.qmd"
          - file: "Academic Writing and Argumentation I/9.qmd"
          - file: "Academic Writing and Argumentation I/10.qmd"
          - file: "Academic Writing and Argumentation I/11.qmd"
          - file: "Academic Writing and Argumentation I/12.qmd"
          - file: "Academic Writing and Argumentation I/13.qmd"
          - file: "Academic Writing and Argumentation I/14.qmd"
          - file: "Academic Writing and Argumentation I/15.qmd"
          - file: "Academic Writing and Argumentation I/16.qmd"
          - file: "Academic Writing and Argumentation I/17.qmd"
          - file: "Academic Writing and Argumentation I/18.qmd"
          - file: "Academic Writing and Argumentation I/19.qmd"
      - section: "Discrete Mathematics"
        contents:
          - file: "Discrete Mathematics/0.qmd"
          - file: "Discrete Mathematics/1.qmd"
          - file: "Discrete Mathematics/2.qmd"
          - file: "Discrete Mathematics/3.qmd"
          - file: "Discrete Mathematics/4.qmd"
          - file: "Discrete Mathematics/5.qmd"
          - file: "Discrete Mathematics/6.qmd"
          - file: "Discrete Mathematics/7.qmd"
          - file: "Discrete Mathematics/8.qmd"
          - file: "Discrete Mathematics/9.qmd"
          - file: "Discrete Mathematics/10.qmd"
          - file: "Discrete Mathematics/11.qmd"
          - file: "Discrete Mathematics/12.qmd"
filters:
  - auto-dark

format:
  html:
    css:
      - styles/sf-pro.css
    include-after-body: _includes/index.html
