project:
  type: website
  title: "InnoNotes"
  
website:
  google-analytics: G-H1WYLNDN76
  favicon: logo.svg
  page-footer: "🤘"
  sidebar:
    search: true
    tools:
      - icon: telegram
        href: https://t.me/p0dyakov
      - icon: github
        href: https://github.com/p0dyakov/inno_notes
    style: "docked"
    contents:
      - section: "Analytical Geometry and Linear Algebra I"
        contents: "Analytical Geometry and Linear Algebra I/**"
      - section: "Mathematical Analysis I"
        contents: "Mathematical Analysis I/**"
      - section: "Introduction to Programming"
        contents: "Introduction to Programming/**"
      - section: "Computer Architecture"
        contents: "Computer Architecture/**"
      - section: "Academic Writing and Argumentation I"
        contents:
          - text: ""
            file: "Academic Writing and Argumentation I/1.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/2.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/3.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/4.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/5.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/6.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/7.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/8.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/9.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/10.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/11.qmd"
          - text: ""
            file: "Academic Writing and Argumentation I/12.qmd"
      - section: "Discrete Mathematics"
        contents: "Discrete Mathematics/**"
filters:
  - auto-dark

theme:
  light: cosmo 

format:
  html:
    include-after-body: _includes/index.html
