project:
  type: website
  title: "InnoNotes"
  
website:
  google-analytics: G-H1WYLNDN76
  sidebar:
    search: true
    tools:
      - icon: telegram
        href: https://t.me/p0dyakov
      - icon: github
        href: https://github.com/p0dyakov/inno_notes
    style: "docked"
    contents: auto
  page-footer: "Innopolis Mafia 🤘" 
