project:
  type: website
  title: "InnoNotes"
  
website:
  google-analytics: G-H1WYLNDN76
  favicon: logo.svg
  sidebar:
    search: true
    tools:
      - icon: telegram
        href: https://t.me/p0dyakov
      - icon: github
        href: https://github.com/p0dyakov/inno_notes
    style: "docked"
    contents:
      - section: "Analytical Geometry and Linear Algebra I"
        contents: "Analytical Geometry and Linear Algebra I/**"
      - section: "Mathematical Analysis I"
        contents: "Mathematical Analysis I/**"
      - section: "Introduction to Programming"
        contents: "Introduction to Programming/**"
      - section: "Computer Architecture"
        contents: "Computer Architecture/**"
      - section: "Academic Writing and Argumentation"
        contents: "Academic Writing and Argumentation/**"
      - section: "Discrete Mathematics"
        contents: "Discrete Mathematics/**"
      - section: "Essence of linear algebra"
        contents:
          - text: "1. Vectors, Vector Addition, Scalar Multiplication"
            file: "Essence of linear algebra/vid_1.qmd"
          - text: "2. Linear Combinations, Span, and Basis Vectors"
            file: "Essence of linear algebra/vid_2.qmd"
          - text: "3. Linear Transformations, Matrices"
            file: "Essence of linear algebra/vid_3.qmd"
          - text: "4. Matrix Multiplication, Composition of Linear Transformations"
            file: "Essence of linear algebra/vid_4.qmd"
          - text: "5. Linear Transformations, Matrices, 3D Space"
            file: "Essence of linear algebra/vid_5.qmd"
          - text: "6. Determinant, Linear Transformations"
            file: "Essence of linear algebra/vid_6.qmd"
          - text: "7. Inverse Matrices, Column Space, Rank, Null Space"
            file: "Essence of linear algebra/vid_7.qmd"
          - text: "8. Non-square Matrices"
            file: "Essence of linear algebra/vid_8.qmd"
          - text: "9. Dot Product, Duality"
            file: "Essence of linear algebra/vid_9.qmd"
          - text: "10. Cross Product, Duality, Determinants, Linear Transformations"
            file: "Essence of linear algebra/vid_10.qmd"
          - text: "11. Cross Product, Duality, Determinants"
            file: "Essence of linear algebra/vid_11.qmd"
          - text: "12. Linear Systems, Cramer's Rule, Determinants"
            file: "Essence of linear algebra/vid_12.qmd"
          - text: "13. Change of Basis, Coordinate Systems"
            file: "Essence of linear algebra/vid_13.qmd"
          - text: "14. Eigenvectors and Eigenvalues"
            file: "Essence of linear algebra/vid_14.qmd"
          - text: "15. Eigenvalues, Eigenvectors, Linear Algebra"
            file: "Essence of linear algebra/vid_15.qmd"
          - text: "16. Vector Spaces, Axioms, Linearity, and Transformations"
            file: "Essence of linear algebra/vid_16.qmd"
  page-footer: "Innopolis Mafia 🤘"

filters:
  - auto-dark

theme:
  light: cosmo 

format:
  html:
    include-after-body: _includes/index.html
