project:
  type: website
  title: "InnoNotes"

website:
  google-analytics: G-H1WYLNDN76
  favicon: logo.svg
  page-footer: "🤘"
  sidebar:
    search: true
    tools:
      - icon: telegram
        href: https://t.me/p0dyakov
      - icon: github
        href: https://github.com/p0dyakov/inno_notes
    style: "docked"
    contents:
      - file: index.qmd
        text: "Home"
      - section: "2 Semester"
        contents:
        - section: "Data Structures and Algorithms"
          contents:
            - file: "Data Structures and Algorithms/1.qmd"
            - file: "Data Structures and Algorithms/2.qmd"
            - file: "Data Structures and Algorithms/3.qmd"
            - file: "Data Structures and Algorithms/4.qmd"
            - file: "Data Structures and Algorithms/5.qmd"
            - file: "Data Structures and Algorithms/6.qmd"
            - file: "Data Structures and Algorithms/7.qmd"
        - section: "Analytical Geometry and Linear Algebra II"
          contents:
            - file: "Analytical Geometry and Linear Algebra II/0.qmd"
            - file: "Analytical Geometry and Linear Algebra II/1.qmd"
            - file: "Analytical Geometry and Linear Algebra II/2.qmd"
            - file: "Analytical Geometry and Linear Algebra II/3.qmd"
            - file: "Analytical Geometry and Linear Algebra II/4.qmd"
            - file: "Analytical Geometry and Linear Algebra II/5.qmd"
            - file: "Analytical Geometry and Linear Algebra II/6.qmd"
        - section: "Mathematical Analysis II"
          contents:
            - file: "Mathematical Analysis II/0.qmd"
            - file: "Mathematical Analysis II/1.qmd"
            - file: "Mathematical Analysis II/2.qmd"
        - section: "Software Systems Analysis and Design"
          contents:
            - file: "Software Systems Analysis and Design/1.qmd"
            - file: "Software Systems Analysis and Design/2.qmd"
            - file: "Software Systems Analysis and Design/3.qmd"
            - file: "Software Systems Analysis and Design/4.qmd"
            - file: "Software Systems Analysis and Design/5.qmd"
            - file: "Software Systems Analysis and Design/6.qmd"
            - file: "Software Systems Analysis and Design/7.qmd"
            - file: "Software Systems Analysis and Design/8.qmd"
        - section: "Theoretical Computer Science"
          contents:
            - file: "Theoretical Computer Science/1.qmd"
            - file: "Theoretical Computer Science/2.qmd"
            - file: "Theoretical Computer Science/3.qmd"
            - file: "Theoretical Computer Science/4.qmd"
            - file: "Theoretical Computer Science/5.qmd"
            - file: "Theoretical Computer Science/6.qmd"
            - file: "Theoretical Computer Science/7.qmd"
        - section: "Academic Writing and Argumentation II"
          contents:
            - file: "Academic Writing and Argumentation II/1A.qmd"
            - file: "Academic Writing and Argumentation II/1B.qmd"
            - file: "Academic Writing and Argumentation II/2A.qmd"
            - file: "Academic Writing and Argumentation II/2B.qmd"
            - file: "Academic Writing and Argumentation II/3A.qmd"
            - file: "Academic Writing and Argumentation II/3B.qmd"
            - file: "Academic Writing and Argumentation II/4A.qmd"
            - file: "Academic Writing and Argumentation II/4B.qmd"
            - file: "Academic Writing and Argumentation II/5A.qmd"
            - file: "Academic Writing and Argumentation II/5B.qmd"
            - file: "Academic Writing and Argumentation II/6A.qmd"
            - file: "Academic Writing and Argumentation II/6B.qmd"
            - file: "Academic Writing and Argumentation II/8B.qmd"
            - file: "Academic Writing and Argumentation II/9A.qmd"
      - section: "1 Semester"
        contents:
        - section: "Analytical Geometry and Linear Algebra I"
          contents:
            - file: "Analytical Geometry and Linear Algebra I/0.qmd"
            - file: "Analytical Geometry and Linear Algebra I/1.qmd"
            - file: "Analytical Geometry and Linear Algebra I/2.qmd"
            - file: "Analytical Geometry and Linear Algebra I/3.qmd"
            - file: "Analytical Geometry and Linear Algebra I/4.qmd"
            - file: "Analytical Geometry and Linear Algebra I/5.qmd"
            - file: "Analytical Geometry and Linear Algebra I/6.qmd"
            - file: "Analytical Geometry and Linear Algebra I/7.qmd"
            - file: "Analytical Geometry and Linear Algebra I/8.qmd"
            - file: "Analytical Geometry and Linear Algebra I/9.qmd"
            - file: "Analytical Geometry and Linear Algebra I/10.qmd"
            - file: "Analytical Geometry and Linear Algebra I/11.qmd"
        - section: "Mathematical Analysis I"
          contents:
            - file: "Mathematical Analysis I/0.qmd"
            - file: "Mathematical Analysis I/1.qmd"
            - file: "Mathematical Analysis I/2.qmd"
            - file: "Mathematical Analysis I/3.qmd"
            - file: "Mathematical Analysis I/4.qmd"
            - file: "Mathematical Analysis I/5.qmd"
            - file: "Mathematical Analysis I/6.qmd"
        - section: "Introduction to Programming"
          contents:
            - file: "Introduction to Programming/1.qmd"
            - file: "Introduction to Programming/2.qmd"
            - file: "Introduction to Programming/3.qmd"
            - file: "Introduction to Programming/4.qmd"
            - file: "Introduction to Programming/5.qmd"
            - file: "Introduction to Programming/6.qmd"
            - file: "Introduction to Programming/7.qmd"
            - file: "Introduction to Programming/8.qmd"
            - file: "Introduction to Programming/9.qmd"
            - file: "Introduction to Programming/10.qmd"
            - file: "Introduction to Programming/11.qmd"
            - file: "Introduction to Programming/12.qmd"
            - file: "Introduction to Programming/13.qmd"
        - section: "Computer Architecture"
          contents:
            - file: "Computer Architecture/1.qmd"
            - file: "Computer Architecture/2.qmd"
            - file: "Computer Architecture/3.qmd"
            - file: "Computer Architecture/4.qmd"
            - file: "Computer Architecture/5.qmd"
            - file: "Computer Architecture/6.qmd"
            - file: "Computer Architecture/7.qmd"
            - file: "Computer Architecture/8.qmd"
            - file: "Computer Architecture/9.qmd"
            - file: "Computer Architecture/10.qmd"
            - file: "Computer Architecture/11.qmd"
            - file: "Computer Architecture/12.qmd"
        - section: "Academic Writing and Argumentation I"
          contents:
            - file: "Academic Writing and Argumentation I/1A.qmd"
            - file: "Academic Writing and Argumentation I/1B.qmd"
            - file: "Academic Writing and Argumentation I/2A.qmd"
            - file: "Academic Writing and Argumentation I/2B.qmd"
            - file: "Academic Writing and Argumentation I/3A.qmd"
            - file: "Academic Writing and Argumentation I/3B.qmd"
            - file: "Academic Writing and Argumentation I/4B.qmd"
            - file: "Academic Writing and Argumentation I/5B.qmd"
            - file: "Academic Writing and Argumentation I/7B.qmd"
            - file: "Academic Writing and Argumentation I/8A.qmd"
            - file: "Academic Writing and Argumentation I/9A.qmd"
            - file: "Academic Writing and Argumentation I/9B.qmd"
            - file: "Academic Writing and Argumentation I/10A.qmd"
            - file: "Academic Writing and Argumentation I/10B.qmd"
            - file: "Academic Writing and Argumentation I/11A.qmd"
            - file: "Academic Writing and Argumentation I/12A.qmd"
            - file: "Academic Writing and Argumentation I/12B.qmd"
            - file: "Academic Writing and Argumentation I/13A.qmd"
            - file: "Academic Writing and Argumentation I/13B.qmd"
        - section: "Logic and Discrete Mathematics"
          contents:
            - file: "Logic and Discrete Mathematics/0.qmd"
            - file: "Logic and Discrete Mathematics/1.qmd"
            - file: "Logic and Discrete Mathematics/2.qmd"
            - file: "Logic and Discrete Mathematics/3.qmd"
            - file: "Logic and Discrete Mathematics/4.qmd"
            - file: "Logic and Discrete Mathematics/5.qmd"
            - file: "Logic and Discrete Mathematics/6.qmd"
            - file: "Logic and Discrete Mathematics/7.qmd"
            - file: "Logic and Discrete Mathematics/8.qmd"
            - file: "Logic and Discrete Mathematics/9.qmd"
            - file: "Logic and Discrete Mathematics/10.qmd"
            - file: "Logic and Discrete Mathematics/11.qmd"
            - file: "Logic and Discrete Mathematics/12.qmd"
filters:
  - auto-dark

format:
  html:
    css:
      - styles/sf-pro.css
    include-after-body: _includes/index.html
