<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Artem Burmyakov">
<meta name="dcterms.date" content="2025-11-28">

<title>W13. Floating-Point Instructions, High-Level Program Translation, Single-Cycle Processor Implementation – InnoNotes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<link href="../../logo.svg" rel="icon" type="image/svg+xml">
<link href="../../site_libs/quarto-contrib/quarto-auto-dark-mode-1.0.0/auto-dark-mode.css" rel="stylesheet">
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-H1WYLNDN76"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-H1WYLNDN76', { 'anonymize_ip': true});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles/sf-pro.css">
</head>

<body>


<header id="title-block-header">
<h1 class="title">W13. Floating-Point Instructions, High-Level Program Translation, Single-Cycle Processor Implementation</h1>
<p class="author">Artem Burmyakov</p>

<p class="date">2025-11-28</p>
</header>


<h4 id="summary"><strong>1. Summary</strong></h4>
<h5 id="floating-point-instructions-in-risc-v"><strong>1.1 Floating-Point Instructions in RISC-V</strong></h5>
<p>RISC-V extends its instruction set architecture with dedicated support for <strong>floating-point operations</strong>. This is essential for scientific computing, graphics, signal processing, and any application requiring real numbers with decimal precision. Unlike integers, floating-point numbers can represent very large or very small values using the IEEE 754 standard.</p>
<h6 id="floating-point-registers"><strong>1.1.1 Floating-Point Registers</strong></h6>
<p>RISC-V provides <strong>32 dedicated floating-point registers</strong>, separate from the integer registers. These are named <code>f0</code> through <code>f31</code>. Each floating-point register can hold either a <strong>single-precision</strong> (32-bit) or <strong>double-precision</strong> (64-bit) floating-point number.</p>
<p>The floating-point registers have <strong>ABI (Application Binary Interface) names</strong> that indicate their conventional usage:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Register</th>
<th style="text-align: left;">ABI Name</th>
<th style="text-align: left;">Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">f0-f7</td>
<td style="text-align: left;">ft0-ft7</td>
<td style="text-align: left;">Temporary registers (caller-saved)</td>
</tr>
<tr class="even">
<td style="text-align: left;">f8-f9</td>
<td style="text-align: left;">fs0-fs1</td>
<td style="text-align: left;">Saved registers (callee-saved)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">f10-f11</td>
<td style="text-align: left;">fa0-fa1</td>
<td style="text-align: left;">Function arguments / return values</td>
</tr>
<tr class="even">
<td style="text-align: left;">f12-f17</td>
<td style="text-align: left;">fa2-fa7</td>
<td style="text-align: left;">Function arguments</td>
</tr>
<tr class="odd">
<td style="text-align: left;">f18-f27</td>
<td style="text-align: left;">fs2-fs11</td>
<td style="text-align: left;">Saved registers (callee-saved)</td>
</tr>
<tr class="even">
<td style="text-align: left;">f28-f31</td>
<td style="text-align: left;">ft8-ft11</td>
<td style="text-align: left;">Temporary registers (caller-saved)</td>
</tr>
</tbody>
</table>
<p><strong>Key point:</strong> Register <code>f10</code> (also known as <code>fa0</code>) is used for passing the first floating-point argument to functions and for returning floating-point results.</p>
<h6 id="risc-v-architecture-layout-with-floating-point-unit"><strong>1.1.2 RISC-V Architecture Layout with Floating-Point Unit</strong></h6>
<p>The RISC-V processor architecture includes a separate floating-point unit alongside the integer unit:</p>
<p><img src="11_10.png" style="width:80.0%"></p>
<p>The floating-point registers connect to a dedicated bus for handling floating-point operations, separate from the integer register file. This allows the processor to execute floating-point and integer operations in parallel in more advanced implementations.</p>
<h6 id="floating-point-arithmetic-instructions"><strong>1.1.3 Floating-Point Arithmetic Instructions</strong></h6>
<p>RISC-V provides arithmetic operations for both single-precision (<code>.s</code> suffix) and double-precision (<code>.d</code> suffix) floating-point numbers:</p>
<p><img src="11_1.png" style="width:80.0%"></p>
<p><strong>Single-Precision Operations:</strong></p>
<ul>
<li><strong><code>fadd.s fd, fs1, fs2</code></strong>: Floating-point addition — <span class="math inline">\(fd = fs1 + fs2\)</span></li>
<li><strong><code>fsub.s fd, fs1, fs2</code></strong>: Floating-point subtraction — <span class="math inline">\(fd = fs1 - fs2\)</span></li>
<li><strong><code>fmul.s fd, fs1, fs2</code></strong>: Floating-point multiplication — <span class="math inline">\(fd = fs1 \times fs2\)</span></li>
<li><strong><code>fdiv.s fd, fs1, fs2</code></strong>: Floating-point division — <span class="math inline">\(fd = fs1 / fs2\)</span></li>
<li><strong><code>fsqrt.s fd, fs1</code></strong>: Square root — <span class="math inline">\(fd = \sqrt{fs1}\)</span></li>
</ul>
<p><strong>Double-Precision Operations:</strong></p>
<ul>
<li><strong><code>fadd.d fd, fs1, fs2</code></strong>: Double-precision addition — <span class="math inline">\(fd = fs1 + fs2\)</span></li>
<li><strong><code>fsub.d fd, fs1, fs2</code></strong>: Double-precision subtraction — <span class="math inline">\(fd = fs1 - fs2\)</span></li>
<li><strong><code>fmul.d fd, fs1, fs2</code></strong>: Double-precision multiplication — <span class="math inline">\(fd = fs1 \times fs2\)</span></li>
<li><strong><code>fdiv.d fd, fs1, fs2</code></strong>: Double-precision division — <span class="math inline">\(fd = fs1 / fs2\)</span></li>
<li><strong><code>fsqrt.d fd, fs1</code></strong>: Double-precision square root — <span class="math inline">\(fd = \sqrt{fs1}\)</span></li>
</ul>
<h6 id="floating-point-comparison-instructions"><strong>1.1.4 Floating-Point Comparison Instructions</strong></h6>
<p>Comparison instructions write their result to an <strong>integer register</strong> (not a floating-point register), setting it to 1 if the condition is true, or 0 if false:</p>
<p><strong>Single-Precision Comparisons:</strong></p>
<ul>
<li><strong><code>feq.s rd, fs1, fs2</code></strong>: Set if equal — <span class="math inline">\(rd = 1\)</span> if <span class="math inline">\(fs1 == fs2\)</span>, else <span class="math inline">\(rd = 0\)</span></li>
<li><strong><code>flt.s rd, fs1, fs2</code></strong>: Set if less than — <span class="math inline">\(rd = 1\)</span> if <span class="math inline">\(fs1 &lt; fs2\)</span>, else <span class="math inline">\(rd = 0\)</span></li>
<li><strong><code>fle.s rd, fs1, fs2</code></strong>: Set if less or equal — <span class="math inline">\(rd = 1\)</span> if <span class="math inline">\(fs1 \le fs2\)</span>, else <span class="math inline">\(rd = 0\)</span></li>
</ul>
<p><strong>Double-Precision Comparisons:</strong></p>
<ul>
<li><strong><code>feq.d rd, fs1, fs2</code></strong>: Double-precision equality check</li>
<li><strong><code>flt.d rd, fs1, fs2</code></strong>: Double-precision less than</li>
<li><strong><code>fle.d rd, fs1, fs2</code></strong>: Double-precision less or equal</li>
</ul>
<h6 id="floating-point-data-transfer-instructions"><strong>1.1.5 Floating-Point Data Transfer Instructions</strong></h6>
<p>To move data between memory and floating-point registers:</p>
<ul>
<li><strong><code>flw fd, offset(rs)</code></strong>: Load single-precision float from memory — <span class="math inline">\(fd = \text{Memory}[rs + offset]\)</span></li>
<li><strong><code>fld fd, offset(rs)</code></strong>: Load double-precision float from memory — <span class="math inline">\(fd = \text{Memory}[rs + offset]\)</span></li>
<li><strong><code>fsw fs, offset(rs)</code></strong>: Store single-precision float to memory — <span class="math inline">\(\text{Memory}[rs + offset] = fs\)</span></li>
<li><strong><code>fsd fs, offset(rs)</code></strong>: Store double-precision float to memory — <span class="math inline">\(\text{Memory}[rs + offset] = fs\)</span></li>
</ul>
<h6 id="floating-point-move-instructions"><strong>1.1.6 Floating-Point Move Instructions</strong></h6>
<p>To copy values between floating-point registers:</p>
<ul>
<li><strong><code>fmv.s fd, fs</code></strong>: Copy single-precision value from <code>fs</code> to <code>fd</code></li>
<li><strong><code>fmv.d fd, fs</code></strong>: Copy double-precision value from <code>fs</code> to <code>fd</code></li>
</ul>
<h6 id="system-calls-for-floating-point-io"><strong>1.1.7 System Calls for Floating-Point I/O</strong></h6>
<p>RISC-V system calls provide input/output for floating-point values:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Code (a7)</th>
<th style="text-align: left;">Service</th>
<th style="text-align: left;">Arguments/Returns</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Print float</td>
<td style="text-align: left;"><code>fa0</code> contains float value to print</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Print double</td>
<td style="text-align: left;"><code>fa0</code> contains double value to print</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Read float</td>
<td style="text-align: left;">Reads float, stores in <code>fa0</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">Read double</td>
<td style="text-align: left;">Reads double, stores in <code>fa0</code></td>
</tr>
</tbody>
</table>
<p><strong>Important:</strong> Note that floating-point I/O uses register <code>fa0</code> (which is <code>f10</code>), not the integer register <code>a0</code>.</p>
<h5 id="high-level-program-translation-into-machine-code"><strong>1.2 High-Level Program Translation into Machine Code</strong></h5>
<p>Understanding how high-level code becomes executable machine code is fundamental to computer architecture. This process involves multiple transformation stages, each serving a specific purpose.</p>
<h6 id="the-translation-pipeline"><strong>1.2.1 The Translation Pipeline</strong></h6>
<p>The complete translation from a high-level program (like C/C++) to executable machine code involves four main stages:</p>
<p><img src="11_9.png" style="width:80.0%"></p>
<ol type="1">
<li><strong>High-Level Program</strong> (e.g., C code) →</li>
<li><strong>Compiler</strong> → <strong>Assembly Language Program</strong> →</li>
<li><strong>Assembler</strong> → <strong>Machine Language Module</strong> (Object file) →</li>
<li><strong>Linker</strong> → <strong>Executable Program</strong> →</li>
<li><strong>Loader</strong> → <strong>Program in Memory</strong></li>
</ol>
<h6 id="the-compiler"><strong>1.2.2 The Compiler</strong></h6>
<p>The <strong>compiler</strong> transforms high-level source code into assembly language. This is where most optimization happens.</p>
<p><strong>Key responsibilities:</strong></p>
<ul>
<li>Translate high-level constructs (loops, conditionals, functions) into assembly</li>
<li>Apply hardware-specific optimizations</li>
<li>Manage register allocation</li>
<li>Generate efficient code based on optimization level settings (e.g., <code>-O0</code>, <code>-O2</code>, <code>-O3</code>)</li>
</ul>
<p>Example transformation:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode c"><code class="sourceCode c"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">// High-Level C Code</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="dt">float</span> f2c<span class="op">(</span><span class="dt">float</span> fahr<span class="op">)</span> <span class="op">{</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">((</span><span class="fl">5.0</span><span class="bu">f</span><span class="op">/</span><span class="fl">9.0</span><span class="bu">f</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span>fahr <span class="op">-</span> <span class="fl">32.0</span><span class="bu">f</span><span class="op">));</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code></pre></div>
<p>Becomes assembly:</p>
<pre class="assembly"><code>f2c:
    flw f0, const5, t0    # f0 = 5.0f
    flw f1, const9, t0    # f1 = 9.0f
    fdiv.s f0, f0, f1     # f0 = 5.0f/9.0f
    flw f1, const32, t0   # f1 = 32.0f
    fsub.s f10, f10, f1   # f10 = fahr - 32.0f
    fmul.s f10, f0, f10   # f10 = (5.0f/9.0f) * (fahr - 32.0f)
    ret</code></pre>
<h6 id="the-assembler"><strong>1.2.3 The Assembler</strong></h6>
<p>The <strong>assembler</strong> translates assembly language into machine language (binary object files).</p>
<p><strong>Key responsibilities:</strong></p>
<ul>
<li>Convert mnemonics to binary opcodes</li>
<li>Resolve local labels to addresses</li>
<li>Generate relocation information for the linker</li>
<li>Create symbol tables</li>
</ul>
<p>The assembler produces <strong>object files</strong> (.o files) containing:</p>
<ul>
<li>Machine code (binary instructions)</li>
<li>Data sections</li>
<li>Symbol table (for linking)</li>
<li>Relocation information</li>
</ul>
<h6 id="the-linker"><strong>1.2.4 The Linker</strong></h6>
<p>The <strong>linker</strong> combines multiple object files and external libraries into a single executable.</p>
<p><strong>Key responsibilities:</strong></p>
<ul>
<li>Resolve external references (functions/variables defined in other files)</li>
<li>Combine code and data sections from multiple object files</li>
<li>Link with external libraries (standard library, math library, etc.)</li>
<li>Assign final memory addresses</li>
</ul>
<h6 id="the-loader"><strong>1.2.5 The Loader</strong></h6>
<p>The <strong>loader</strong> is part of the operating system that loads the executable into memory for execution.</p>
<p><strong>Key responsibilities:</strong></p>
<ul>
<li>Allocate memory for the program</li>
<li>Load code and data segments</li>
<li>Set up the stack and heap</li>
<li>Initialize the Program Counter to the program’s entry point</li>
</ul>
<h6 id="hardware-dependency"><strong>1.2.6 Hardware Dependency</strong></h6>
<p>The translation stages differ in their hardware dependency:</p>
<ul>
<li><strong>Hardware-Independent:</strong> High-level source code (portable across platforms)</li>
<li><strong>Hardware-Dependent:</strong> Assembly, object code, and executables (specific to RISC-V, x86, ARM, etc.)</li>
</ul>
<p>This separation is why the same C program can be compiled for different processor architectures.</p>
<h5 id="risc-v-instruction-encoding"><strong>1.3 RISC-V Instruction Encoding</strong></h5>
<p>Every RISC-V instruction is encoded as exactly <strong>32 bits</strong>. Different instruction types use different bit field layouts to encode their operands.</p>
<p><img src="11_8.png" style="width:80.0%"></p>
<h6 id="main-instruction-formats"><strong>1.3.1 Main Instruction Formats</strong></h6>
<p>RISC-V uses six primary instruction formats:</p>
<p><strong>R-type (Register):</strong> For operations using only registers</p>
<p><img src="11_4.png" style="width:80.0%"></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">funct7 (7)</th>
<th style="text-align: left;">rs2 (5)</th>
<th style="text-align: left;">rs1 (5)</th>
<th style="text-align: left;">funct3 (3)</th>
<th style="text-align: left;">rd (5)</th>
<th style="text-align: left;">opcode (7)</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<ul>
<li>Used for: <code>add</code>, <code>sub</code>, <code>and</code>, <code>or</code>, <code>sll</code>, <code>srl</code>, etc.</li>
<li>All operands are registers</li>
</ul>
<p><strong>I-type (Immediate):</strong> For operations with immediate values and loads</p>
<p><img src="11_5.png" style="width:80.0%"></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">imm[11:0] (12)</th>
<th style="text-align: left;">rs1 (5)</th>
<th style="text-align: left;">funct3 (3)</th>
<th style="text-align: left;">rd (5)</th>
<th style="text-align: left;">opcode (7)</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<ul>
<li>Used for: <code>addi</code>, <code>andi</code>, <code>ori</code>, <code>ld</code>, <code>lw</code>, <code>jalr</code>, etc.</li>
<li>12-bit signed immediate value</li>
</ul>
<p><strong>S-type (Store):</strong> For store instructions</p>
<p><img src="11_6.png" style="width:80.0%"></p>
<table class="caption-top">
<colgroup>
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">imm[11:5] (7)</th>
<th style="text-align: left;">rs2 (5)</th>
<th style="text-align: left;">rs1 (5)</th>
<th style="text-align: left;">funct3 (3)</th>
<th style="text-align: left;">imm[4:0] (5)</th>
<th style="text-align: left;">opcode (7)</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<ul>
<li>Used for: <code>sw</code>, <code>sd</code>, <code>sb</code>, etc.</li>
<li>Immediate is split across two fields</li>
</ul>
<p><strong>B-type (Branch):</strong> For conditional branches</p>
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 22%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">imm[12|10:5] (7)</th>
<th style="text-align: left;">rs2 (5)</th>
<th style="text-align: left;">rs1 (5)</th>
<th style="text-align: left;">funct3 (3)</th>
<th style="text-align: left;">imm[4:1|11] (5)</th>
<th style="text-align: left;">opcode (7)</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<ul>
<li>Used for: <code>beq</code>, <code>bne</code>, <code>blt</code>, <code>bge</code>, etc.</li>
<li>Immediate encodes branch offset (shifted)</li>
</ul>
<p><strong>U-type (Upper immediate):</strong> For large immediates</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">imm[31:12] (20)</th>
<th style="text-align: left;">rd (5)</th>
<th style="text-align: left;">opcode (7)</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<ul>
<li>Used for: <code>lui</code>, <code>auipc</code></li>
<li>20-bit immediate placed in upper bits</li>
</ul>
<p><strong>J-type (Jump):</strong> For unconditional jumps</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">imm[20|10:1|11|19:12] (20)</th>
<th style="text-align: left;">rd (5)</th>
<th style="text-align: left;">opcode (7)</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<ul>
<li>Used for: <code>jal</code></li>
<li>20-bit immediate for jump offset</li>
</ul>
<p><img src="11_11.png" style="width:80.0%"></p>
<h6 id="example-translating-c-to-binary"><strong>1.3.2 Example: Translating C to Binary</strong></h6>
<p>Let’s trace the translation of <code>A[30] = h + A[30] + 1</code> where <code>h</code> is in register <code>x21</code> and the base address of array <code>A</code> is in <code>x18</code>.</p>
<p><strong>Step 1: Assign registers</strong></p>
<ul>
<li><code>h</code> → <code>x21</code></li>
<li>Base address of <code>A</code> → <code>x18</code></li>
<li>Temporary → <code>x5</code></li>
</ul>
<p><strong>Step 2: Write assembly</strong></p>
<pre class="assembly"><code>ld x5, 240(x18)    # Load A[30] (offset = 30 × 8 = 240 bytes for doubleword)
add x5, x21, x5    # x5 = h + A[30]
addi x5, x5, 1     # x5 = h + A[30] + 1
sd x5, 240(x18)    # Store result back to A[30]</code></pre>
<p><strong>Step 3: Identify instruction types</strong></p>
<ul>
<li><code>ld</code> → I-type</li>
<li><code>add</code> → R-type</li>
<li><code>addi</code> → I-type</li>
<li><code>sd</code> → S-type</li>
</ul>
<p><strong>Step 4: Encode to binary (example for <code>ld x5, 240(x18)</code>)</strong></p>
<ul>
<li>Opcode for <code>ld</code>: 0000011 (3 in decimal)</li>
<li>rd: 00101 (5 in decimal)</li>
<li>funct3 for doubleword: 011</li>
<li>rs1: 10010 (18 in decimal)</li>
<li>immediate: 000011110000 (240 in binary)</li>
</ul>
<p>Final binary: <code>000011110000 10010 011 00101 0000011</code></p>
<p><img src="11_13.png" style="width:80.0%"></p>
<h5 id="single-cycle-processor-implementation"><strong>1.4 Single-Cycle Processor Implementation</strong></h5>
<p>A <strong>single-cycle processor</strong> executes each instruction in exactly one clock cycle. While simple to understand, this design has limitations that motivate more advanced implementations like pipelining.</p>
<h6 id="recap-risc-v-architecture"><strong>1.4.1 Recap: RISC-V Architecture</strong></h6>
<p><img src="11_2.png" style="width:80.0%"></p>
<p><strong>Key characteristics:</strong></p>
<ul>
<li><strong>Architecture type:</strong> RISC (Reduced Instruction Set Computer)</li>
<li><strong>Memory type:</strong> Load-Store (only load/store instructions access memory)</li>
<li><strong>Standard:</strong> Open Architecture</li>
<li><strong>Address space:</strong> 32 or 64 bits</li>
<li><strong>Instruction size:</strong> Fixed 32 bits</li>
<li><strong>Registers:</strong> 32 general-purpose (x0-x31) + 32 floating-point (f0-f31)</li>
<li><strong>Special register:</strong> PC (Program Counter)</li>
</ul>
<h6 id="the-program-counter-pc"><strong>1.4.2 The Program Counter (PC)</strong></h6>
<p>The <strong>Program Counter</strong> is a special-purpose register that holds the address of the <strong>next instruction</strong> to be executed. Understanding the PC is crucial for understanding how programs flow.</p>
<p><strong>Key facts about PC:</strong></p>
<ul>
<li>Contains a memory address pointing to the next instruction</li>
<li>Automatically incremented by 4 after each instruction (since all RISC-V instructions are 4 bytes)</li>
<li>Modified by branch and jump instructions to change program flow</li>
</ul>
<h6 id="harvard-vs.-von-neumann-architecture"><strong>1.4.3 Harvard vs.&nbsp;Von Neumann Architecture</strong></h6>
<p>Two fundamental memory architectures exist:</p>
<p><img src="11_3.png" style="width:80.0%"></p>
<p><strong>Harvard Architecture:</strong></p>
<ul>
<li>Separate memory spaces for instructions and data</li>
<li>Instruction memory is read-only during execution</li>
<li>Data memory allows both read and write</li>
<li>Allows simultaneous instruction fetch and data access</li>
</ul>
<p><strong>Von Neumann Architecture:</strong></p>
<ul>
<li>Single unified memory for both instructions and data</li>
<li>Simpler design but can create memory access bottleneck</li>
<li>Instructions and data share the same bus</li>
</ul>
<p>The single-cycle processor diagrams typically show separate instruction and data memories (Harvard style) for clarity.</p>
<h6 id="instruction-execution-stages"><strong>1.4.4 Instruction Execution Stages</strong></h6>
<p>Every instruction goes through a sequence of stages. In a single-cycle processor, all stages complete in one clock cycle:</p>
<p><img src="11_12.png" style="width:80.0%"></p>
<p><strong>1. Instruction Fetch (IF):</strong></p>
<ul>
<li>PC sends address to Instruction Memory</li>
<li>Instruction Memory returns the 32-bit instruction</li>
<li>PC is incremented by 4 in parallel</li>
</ul>
<p><strong>2. Instruction Decode (ID):</strong></p>
<ul>
<li>Instruction bits are distributed to appropriate components</li>
<li>Register file reads source registers (rs1, rs2)</li>
<li>Control Unit decodes opcode and generates control signals</li>
<li>Immediate value is extracted and sign-extended</li>
</ul>
<p><strong>3. Execution (EXE):</strong></p>
<ul>
<li>ALU performs the operation specified by the instruction</li>
<li>For R-type: operates on two register values</li>
<li>For I-type: operates on register value and immediate</li>
<li>MUX selects between register and immediate for second ALU input</li>
</ul>
<p><strong>4. Memory Access (MA):</strong></p>
<ul>
<li>Only used by load/store instructions</li>
<li><code>lw</code>/<code>ld</code>: Read data from Data Memory</li>
<li><code>sw</code>/<code>sd</code>: Write data to Data Memory</li>
<li>Other instructions bypass this stage</li>
</ul>
<p><strong>5. Write Back (WB):</strong></p>
<ul>
<li>Result written back to destination register in Register File</li>
<li>Source can be ALU result or value loaded from memory</li>
<li>MUX selects the appropriate source</li>
</ul>
<h6 id="control-unit"><strong>1.4.5 Control Unit</strong></h6>
<p>The <strong>Control Unit (CU)</strong> decodes the opcode and generates control signals that configure the datapath:</p>
<ul>
<li><strong>ALU control:</strong> What operation the ALU should perform</li>
<li><strong>ALUSrc:</strong> Select register value or immediate for ALU input</li>
<li><strong>MemRead/MemWrite:</strong> Enable reading/writing Data Memory</li>
<li><strong>RegWrite:</strong> Enable writing to Register File</li>
<li><strong>MemtoReg:</strong> Select ALU result or memory value for write-back</li>
<li><strong>Branch:</strong> Indicates a branch instruction</li>
</ul>
<h6 id="branch-instruction-implementation"><strong>1.4.6 Branch Instruction Implementation</strong></h6>
<p>Branch instructions require special handling:</p>
<p><img src="11_12.png" style="width:80.0%"></p>
<p><strong>Branch address calculation:</strong></p>
<ul>
<li>Immediate value is extracted and shifted (branch offsets are multiples of 2)</li>
<li>Branch target = PC + (immediate × 2)</li>
</ul>
<p><strong>Branch condition evaluation:</strong></p>
<ul>
<li>ALU computes rs1 - rs2</li>
<li>“Zero” output indicates if rs1 equals rs2</li>
<li>AND gate combines “Branch” control signal with condition result</li>
</ul>
<p><strong>PC update:</strong></p>
<ul>
<li>MUX selects between PC+4 (sequential) and branch target</li>
<li>Selection controlled by branch condition result</li>
</ul>
<h6 id="memory-access-instructions"><strong>1.4.7 Memory Access Instructions</strong></h6>
<p>Load and store instructions access the Data Memory:</p>
<p><strong>Store Word (<code>sw</code>):</strong></p>
<ol type="1">
<li>ALU calculates address: rs1 + offset</li>
<li>Value from rs2 goes to Data Memory write port</li>
<li>MemWrite signal enables the write</li>
</ol>
<p><strong>Load Word (<code>lw</code>):</strong></p>
<ol type="1">
<li>ALU calculates address: rs1 + offset</li>
<li>MemRead signal enables reading from Data Memory</li>
<li>MUX selects memory value (instead of ALU result) for write-back</li>
<li>Value written to destination register</li>
</ol>
<h6 id="complete-single-cycle-datapath"><strong>1.4.8 Complete Single-Cycle Datapath</strong></h6>
<p><img src="11_12.png" style="width:80.0%"></p>
<p>The complete datapath includes:</p>
<ul>
<li><strong>PC:</strong> Holds address of current instruction</li>
<li><strong>Instruction Memory:</strong> Stores program instructions</li>
<li><strong>Register File:</strong> 32 integer registers with 2 read ports and 1 write port</li>
<li><strong>ALU:</strong> Performs arithmetic and logical operations</li>
<li><strong>Data Memory:</strong> Stores program data</li>
<li><strong>Control Unit:</strong> Generates control signals</li>
<li><strong>Multiplexers:</strong> Select between alternative data paths</li>
<li><strong>Adders:</strong> Compute PC+4 and branch targets</li>
</ul>
<h6 id="clocking-and-synchronization"><strong>1.4.9 Clocking and Synchronization</strong></h6>
<p>All state elements (PC, Register File, Memories) are synchronized by the <strong>clock signal</strong>:</p>
<ul>
<li><strong>Rising edge:</strong> State elements capture new values</li>
<li><strong>Clock period:</strong> Must be long enough for slowest instruction to complete</li>
<li><strong>Reset signal:</strong> Initializes PC to starting address</li>
</ul>
<p>The single-cycle design’s limitation: clock period is determined by the slowest instruction (typically load), making faster instructions wait unnecessarily.</p>
<h5 id="introduction-to-pipelining"><strong>1.5 Introduction to Pipelining</strong></h5>
<p><strong>Pipelining</strong> is a fundamental technique that improves processor throughput by overlapping instruction execution.</p>
<h6 id="the-pipelining-concept"><strong>1.5.1 The Pipelining Concept</strong></h6>
<p><img src="11_7.png" style="width:80.0%"></p>
<p><strong>Analogy:</strong> Think of an assembly line in a factory. While one car is being painted, another is being assembled, and a third is having its engine installed. No car finishes faster, but more cars are completed per unit time.</p>
<p><strong>In a processor:</strong></p>
<ul>
<li>Each instruction still takes multiple stages (IF, ID, EXE, MEM, WB)</li>
<li>But different instructions occupy different stages simultaneously</li>
<li>When Instruction 1 is in ID stage, Instruction 2 can be in IF stage</li>
<li>Ideally, throughput increases by factor of pipeline depth</li>
</ul>
<p><strong>Benefits:</strong></p>
<ul>
<li>Higher instruction throughput (more instructions per second)</li>
<li>Better utilization of hardware components</li>
</ul>
<p><strong>Challenges:</strong></p>
<ul>
<li><strong>Data hazards:</strong> Instruction needs data from previous instruction not yet available</li>
<li><strong>Control hazards:</strong> Branch instructions disrupt the pipeline flow</li>
<li><strong>Structural hazards:</strong> Hardware resource conflicts</li>
</ul>
<p>Pipelining doesn’t reduce latency (time for one instruction) but dramatically increases throughput (instructions per second).</p>
<h4 id="definitions"><strong>2. Definitions</strong></h4>
<ul>
<li><strong>Floating-Point Number</strong>: A number representation that can express very large or very small values using a sign, mantissa (significand), and exponent, following the IEEE 754 standard.</li>
<li><strong>Single-Precision</strong>: A 32-bit floating-point format providing approximately 7 decimal digits of precision.</li>
<li><strong>Double-Precision</strong>: A 64-bit floating-point format providing approximately 15-16 decimal digits of precision.</li>
<li><strong>Floating-Point Register</strong>: One of 32 dedicated registers (f0-f31) in RISC-V used exclusively for floating-point operations.</li>
<li><strong>Compiler</strong>: A program that translates high-level source code (like C) into assembly language, applying optimizations for the target hardware.</li>
<li><strong>Assembler</strong>: A program that translates assembly language mnemonics into binary machine code (object files).</li>
<li><strong>Linker</strong>: A program that combines multiple object files and libraries into a single executable program, resolving external references.</li>
<li><strong>Loader</strong>: An operating system component that loads an executable program into memory and prepares it for execution.</li>
<li><strong>Object File</strong>: The binary output of an assembler containing machine code, data, symbol tables, and relocation information.</li>
<li><strong>Opcode</strong>: The portion of a machine instruction that specifies the operation to be performed.</li>
<li><strong>Instruction Format</strong>: The layout of bit fields within a machine instruction (e.g., R-type, I-type, S-type).</li>
<li><strong>R-type Instruction</strong>: A RISC-V instruction format where all operands are registers, used for arithmetic and logical operations.</li>
<li><strong>I-type Instruction</strong>: A RISC-V instruction format with a 12-bit immediate value, used for immediate operations and loads.</li>
<li><strong>S-type Instruction</strong>: A RISC-V instruction format used for store operations, with the immediate value split across two fields.</li>
<li><strong>Program Counter (PC)</strong>: A special register containing the memory address of the next instruction to be executed.</li>
<li><strong>Single-Cycle Processor</strong>: A processor design where each instruction completes in exactly one clock cycle.</li>
<li><strong>Datapath</strong>: The collection of hardware components (registers, ALU, memory, etc.) through which data flows during instruction execution.</li>
<li><strong>Control Unit (CU)</strong>: The processor component that decodes instructions and generates control signals to coordinate the datapath.</li>
<li><strong>ALU (Arithmetic Logic Unit)</strong>: The processor component that performs arithmetic and logical operations.</li>
<li><strong>Instruction Fetch (IF)</strong>: The stage where the processor reads an instruction from memory using the PC address.</li>
<li><strong>Instruction Decode (ID)</strong>: The stage where the instruction is interpreted and operands are read from registers.</li>
<li><strong>Execution (EXE)</strong>: The stage where the ALU performs the operation specified by the instruction.</li>
<li><strong>Memory Access (MA)</strong>: The stage where load/store instructions read from or write to data memory.</li>
<li><strong>Write Back (WB)</strong>: The stage where the result is written to the destination register.</li>
<li><strong>Harvard Architecture</strong>: A computer architecture with separate memory spaces for instructions and data.</li>
<li><strong>Von Neumann Architecture</strong>: A computer architecture with a single unified memory for both instructions and data.</li>
<li><strong>Multiplexer (MUX)</strong>: A circuit that selects one of several input signals based on a control signal and forwards it to the output.</li>
<li><strong>Pipelining</strong>: A technique where multiple instructions are overlapped in execution, with each instruction in a different stage simultaneously.</li>
<li><strong>Throughput</strong>: The number of instructions completed per unit time.</li>
<li><strong>Latency</strong>: The time required to complete a single instruction from start to finish.</li>
</ul>
<h4 id="examples"><strong>3. Examples</strong></h4>
<h5 id="fahrenheit-to-celsius-conversion-lab-13-example-1"><strong>3.1. Fahrenheit to Celsius Conversion</strong> (Lab 13, Example 1)</h5>
<p>Write a RISC-V program using floating-point instructions to convert temperature from Fahrenheit to Celsius using the formula: <span class="math display">\[°C = (°F - 32.0) \times \frac{5.0}{9.0}\]</span></p>
<details>
<summary>
Click to see the solution
</summary>
<p><strong>Key Concept:</strong> Use floating-point arithmetic instructions to perform the conversion. Constants must be stored in memory and loaded into floating-point registers.</p>
<p><strong>The function:</strong></p>
<pre class="assembly"><code>.data:
const5:  .float 5.0      # Allocate float constant 5.0
const9:  .float 9.0      # Allocate float constant 9.0
const32: .float 32.0     # Allocate float constant 32.0

.text
f2c:                     # Function to convert Fahrenheit to Celsius
    flw f0, const5, t0   # f0 = 5.0f (t0 used as temp for address)
    flw f1, const9, t0   # f1 = 9.0f
    fdiv.s f0, f0, f1    # f0 = 5.0f / 9.0f
    flw f1, const32, t0  # f1 = 32.0f
    fsub.s f10, f10, f1  # f10 = fahr - 32.0f (input in f10)
    fmul.s f10, f0, f10  # f10 = (5.0f/9.0f) * (fahr - 32.0f)
    ret                  # Return (result in f10)</code></pre>
<p><strong>Complete program with main:</strong></p>
<pre class="assembly"><code>.data:
const5:  .float 5.0
const9:  .float 9.0
const32: .float 32.0

.text
main:
    li a7, 6             # System call code to read a float
    ecall                # Execute system call (input stored in fa0)
    fmv.s f10, fa0       # Move input to f10 (Note: f10 IS fa0, so this is redundant!)
    call f2c             # Call conversion function
    li a7, 2             # System call code to print a float
    ecall                # Print result (fa0 = f10 already contains result)
    li a7, 10            # System call code to exit
    ecall                # Exit program

f2c:
    flw f0, const5, t0
    flw f1, const9, t0
    fdiv.s f0, f0, f1
    flw f1, const32, t0
    fsub.s f10, f10, f1
    fmul.s f10, f0, f10
    ret</code></pre>
<p><strong>Discussion Question:</strong> Why is <code>fmv.s f10, fa0</code> redundant?</p>
<p><strong>Answer:</strong> Because <code>f10</code> and <code>fa0</code> are the same register! The ABI name <code>fa0</code> is just an alias for register <code>f10</code>. So copying from <code>fa0</code> to <code>f10</code> does nothing.</p>
<p><strong>Step-by-step explanation:</strong></p>
<ol type="1">
<li><strong>Read input:</strong> System call 6 reads a float from user into <code>fa0</code> (which is <code>f10</code>)</li>
<li><strong>Call function:</strong> <code>f2c</code> expects argument in <code>f10</code>, which already contains the input</li>
<li><strong>Inside f2c:</strong>
<ul>
<li>Load constants 5.0, 9.0, and 32.0 from memory</li>
<li>Compute <code>5.0 / 9.0</code> and store in <code>f0</code></li>
<li>Subtract 32.0 from input temperature</li>
<li>Multiply by <code>5.0/9.0</code> to get Celsius</li>
</ul></li>
<li><strong>Print result:</strong> System call 2 prints the float in <code>fa0</code> (which is the result in <code>f10</code>)</li>
</ol>
<p><strong>Answer:</strong> For input 212°F, the program outputs 100.0 (the boiling point of water in Celsius).</p>
</details>
<h5 id="sphere-surface-area-and-volume-lab-13-task-1"><strong>3.2. Sphere Surface Area and Volume</strong> (Lab 13, Task 1)</h5>
<p>Write a RISC-V program to compute the surface area and volume of a sphere using the formulas: <span class="math display">\[\text{surfaceArea} = 4.0 \times \pi \times r^2\]</span> <span class="math display">\[\text{volume} = \frac{4.0}{3.0} \times \pi \times r^3\]</span></p>
<p>Hint: Assume <span class="math inline">\(\pi = 3.14159\)</span></p>
<details>
<summary>
Click to see the solution
</summary>
<p><strong>Key Concept:</strong> Use floating-point multiplication to compute powers (<span class="math inline">\(r^2 = r \times r\)</span>, <span class="math inline">\(r^3 = r \times r \times r\)</span>) and combine with constants.</p>
<pre class="assembly"><code>.data
pi:      .float 3.14159
four:    .float 4.0
three:   .float 3.0
sa_msg:  .asciiz "Surface Area: "
vol_msg: .asciiz "\nVolume: "
prompt:  .asciiz "Enter radius: "

.text
main:
    # Print prompt
    li a7, 4
    la a0, prompt
    ecall
    
    # Read radius from user
    li a7, 6
    ecall
    fmv.s f10, fa0           # f10 = radius
    
    # Load constants
    flw f0, pi, t0           # f0 = pi
    flw f1, four, t0         # f1 = 4.0
    flw f2, three, t0        # f2 = 3.0
    
    # Calculate r^2
    fmul.s f3, f10, f10      # f3 = r * r = r^2
    
    # Calculate r^3
    fmul.s f4, f3, f10       # f4 = r^2 * r = r^3
    
    # Calculate surface area: 4.0 * pi * r^2
    fmul.s f5, f1, f0        # f5 = 4.0 * pi
    fmul.s f5, f5, f3        # f5 = 4.0 * pi * r^2 (surface area)
    
    # Calculate volume: (4.0/3.0) * pi * r^3
    fdiv.s f6, f1, f2        # f6 = 4.0 / 3.0
    fmul.s f6, f6, f0        # f6 = (4.0/3.0) * pi
    fmul.s f6, f6, f4        # f6 = (4.0/3.0) * pi * r^3 (volume)
    
    # Print surface area
    li a7, 4
    la a0, sa_msg
    ecall
    
    li a7, 2
    fmv.s fa0, f5            # Move surface area to fa0 for printing
    ecall
    
    # Print volume
    li a7, 4
    la a0, vol_msg
    ecall
    
    li a7, 2
    fmv.s fa0, f6            # Move volume to fa0 for printing
    ecall
    
    # Exit
    li a7, 10
    ecall</code></pre>
<p><strong>Step-by-step:</strong></p>
<ol type="1">
<li><strong>Read radius</strong> into <code>f10</code></li>
<li><strong>Load constants</strong>: <span class="math inline">\(\pi\)</span>, 4.0, and 3.0</li>
<li><strong>Compute <span class="math inline">\(r^2\)</span></strong>: Multiply radius by itself</li>
<li><strong>Compute <span class="math inline">\(r^3\)</span></strong>: Multiply <span class="math inline">\(r^2\)</span> by radius</li>
<li><strong>Surface area</strong>: <span class="math inline">\(4.0 \times \pi \times r^2\)</span></li>
<li><strong>Volume</strong>: <span class="math inline">\((4.0 / 3.0) \times \pi \times r^3\)</span></li>
<li><strong>Print results</strong> using system calls</li>
</ol>
<p><strong>Answer:</strong> For radius = 5.0:</p>
<ul>
<li>Surface Area ≈ 314.159</li>
<li>Volume ≈ 523.599</li>
</ul>
</details>
<h5 id="calculate-function-fx-lab-13-optional-task"><strong>3.3. Calculate Function f(x)</strong> (Lab 13, Optional Task)</h5>
<p>Write a program to calculate the following expression: <span class="math display">\[f(x) = \frac{e^2}{\pi} \cdot x\]</span></p>
<p>Hint: Assume <span class="math inline">\(\pi = 3.14159\)</span> and <span class="math inline">\(e = 2.71828\)</span></p>
<details>
<summary>
Click to see the solution
</summary>
<p><strong>Key Concept:</strong> Pre-compute <span class="math inline">\(e^2\)</span> as a constant or compute it at runtime, then divide by <span class="math inline">\(\pi\)</span> and multiply by <span class="math inline">\(x\)</span>.</p>
<pre class="assembly"><code>.data
pi:      .float 3.14159
e:       .float 2.71828
prompt:  .asciiz "Enter x: "
result:  .asciiz "f(x) = "

.text
main:
    # Print prompt
    li a7, 4
    la a0, prompt
    ecall
    
    # Read x from user
    li a7, 6
    ecall
    fmv.s f10, fa0           # f10 = x
    
    # Load constants
    flw f0, e, t0            # f0 = e
    flw f1, pi, t0           # f1 = pi
    
    # Calculate e^2
    fmul.s f2, f0, f0        # f2 = e * e = e^2
    
    # Calculate e^2 / pi
    fdiv.s f3, f2, f1        # f3 = e^2 / pi
    
    # Calculate f(x) = (e^2 / pi) * x
    fmul.s f4, f3, f10       # f4 = (e^2 / pi) * x
    
    # Print result message
    li a7, 4
    la a0, result
    ecall
    
    # Print result value
    li a7, 2
    fmv.s fa0, f4
    ecall
    
    # Exit
    li a7, 10
    ecall</code></pre>
<p><strong>Step-by-step:</strong></p>
<ol type="1">
<li><strong>Read input</strong> <span class="math inline">\(x\)</span> from user</li>
<li><strong>Load constants</strong> <span class="math inline">\(e\)</span> and <span class="math inline">\(\pi\)</span></li>
<li><strong>Compute <span class="math inline">\(e^2\)</span></strong>: <code>fmul.s f2, f0, f0</code></li>
<li><strong>Compute <span class="math inline">\(e^2 / \pi\)</span></strong>: <code>fdiv.s f3, f2, f1</code></li>
<li><strong>Compute result</strong>: Multiply by <span class="math inline">\(x\)</span></li>
</ol>
<p><strong>Answer:</strong> For <span class="math inline">\(x = 1.0\)</span>:</p>
<ul>
<li><span class="math inline">\(e^2 \approx 7.389\)</span></li>
<li><span class="math inline">\(e^2 / \pi \approx 2.351\)</span></li>
<li><span class="math inline">\(f(1.0) \approx 2.351\)</span></li>
</ul>
</details>
<h5 id="translate-c-expression-to-risc-v-lecture-13-example"><strong>3.4. Translate C Expression to RISC-V</strong> (Lecture 13, Example)</h5>
<p>Translate the C expression <code>A[30] = h + A[30] + 1</code> into RISC-V assembly and then into binary machine code.</p>
<p>Assume:</p>
<ul>
<li>Variable <code>h</code> is assigned to register <code>x21</code></li>
<li>Base address of array <code>A</code> is in register <code>x18</code></li>
<li>Array <code>A</code> contains 64-bit doublewords</li>
</ul>
<details>
<summary>
Click to see the solution
</summary>
<p><strong>Key Concept:</strong> Break down the expression into basic operations: load from memory, add values, store back to memory.</p>
<p><strong>Step 1: Write the assembly code</strong></p>
<pre class="assembly"><code>ld x5, 240(x18)    # Load A[30] into x5 (offset = 30 × 8 = 240)
add x5, x21, x5    # x5 = h + A[30]
addi x5, x5, 1     # x5 = h + A[30] + 1
sd x5, 240(x18)    # Store result back to A[30]</code></pre>
<p><strong>Step 2: Identify instruction types</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 48%">
<col style="width: 22%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Instruction</th>
<th style="text-align: left;">Type</th>
<th style="text-align: left;">Format</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>ld x5, 240(x18)</code></td>
<td style="text-align: left;">I-type</td>
<td style="text-align: left;">immediate | rs1 | funct3 | rd | opcode</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>add x5, x21, x5</code></td>
<td style="text-align: left;">R-type</td>
<td style="text-align: left;">funct7 | rs2 | rs1 | funct3 | rd | opcode</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>addi x5, x5, 1</code></td>
<td style="text-align: left;">I-type</td>
<td style="text-align: left;">immediate | rs1 | funct3 | rd | opcode</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>sd x5, 240(x18)</code></td>
<td style="text-align: left;">S-type</td>
<td style="text-align: left;">imm[11:5] | rs2 | rs1 | funct3 | imm[4:0] | opcode</td>
</tr>
</tbody>
</table>
<p><strong>Step 3: Encode <code>ld x5, 240(x18)</code> to binary</strong></p>
<ul>
<li>Opcode for <code>ld</code>: 0000011 (3)</li>
<li>rd = x5: 00101 (5)</li>
<li>funct3 for doubleword: 011 (3)</li>
<li>rs1 = x18: 10010 (18)</li>
<li>immediate = 240: 000011110000</li>
</ul>
<p>Binary: <code>000011110000 10010 011 00101 0000011</code></p>
<p><strong>Step 4: Encode <code>add x5, x21, x5</code> to binary</strong></p>
<ul>
<li>Opcode for R-type: 0110011 (51)</li>
<li>rd = x5: 00101</li>
<li>funct3 for add: 000</li>
<li>rs1 = x21: 10101 (21)</li>
<li>rs2 = x5: 00101 (5)</li>
<li>funct7 for add: 0000000</li>
</ul>
<p>Binary: <code>0000000 00101 10101 000 00101 0110011</code></p>
<p><strong>Step 5: Encode <code>addi x5, x5, 1</code> to binary</strong></p>
<ul>
<li>Opcode for I-type: 0010011 (19)</li>
<li>rd = x5: 00101</li>
<li>funct3 for addi: 000</li>
<li>rs1 = x5: 00101</li>
<li>immediate = 1: 000000000001</li>
</ul>
<p>Binary: <code>000000000001 00101 000 00101 0010011</code></p>
<p><strong>Step 6: Encode <code>sd x5, 240(x18)</code> to binary</strong></p>
<ul>
<li>Opcode for S-type: 0100011 (35)</li>
<li>funct3 for doubleword: 011</li>
<li>rs1 = x18: 10010</li>
<li>rs2 = x5: 00101</li>
<li>immediate = 240 split: imm[11:5] = 0000111, imm[4:0] = 10000</li>
</ul>
<p>Binary: <code>0000111 00101 10010 011 10000 0100011</code></p>
<p><strong>Answer:</strong> The complete binary encoding:</p>
<pre><code>ld x5, 240(x18):   000011110000 10010 011 00101 0000011
add x5, x21, x5:   0000000 00101 10101 000 00101 0110011
addi x5, x5, 1:    000000000001 00101 000 00101 0010011
sd x5, 240(x18):   0000111 00101 10010 011 10000 0100011</code></pre>
</details>
<h5 id="identify-instruction-stages-lecture-13-exercise"><strong>3.5. Identify Instruction Stages</strong> (Lecture 13, Exercise)</h5>
<p>For each of the following instructions, identify which execution stages are used:</p>
<ol type="a">
<li><code>add x5, x6, x7</code></li>
<li><code>lw x5, 0(x6)</code></li>
<li><code>sw x5, 0(x6)</code></li>
<li><code>beq x5, x6, label</code></li>
</ol>
<details>
<summary>
Click to see the solution
</summary>
<p><strong>Key Concept:</strong> Different instructions use different subsets of the five stages (IF, ID, EXE, MA, WB).</p>
<p><strong>(a) <code>add x5, x6, x7</code></strong> (R-type arithmetic)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Stage</th>
<th style="text-align: left;">Used?</th>
<th style="text-align: left;">Activity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IF</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Fetch instruction from memory</td>
</tr>
<tr class="even">
<td style="text-align: left;">ID</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Read x6 and x7 from register file</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EXE</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">ALU computes x6 + x7</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA</td>
<td style="text-align: left;">✗</td>
<td style="text-align: left;">No memory access needed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WB</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Write result to x5</td>
</tr>
</tbody>
</table>
<p><strong>(b) <code>lw x5, 0(x6)</code></strong> (Load word)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Stage</th>
<th style="text-align: left;">Used?</th>
<th style="text-align: left;">Activity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IF</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Fetch instruction</td>
</tr>
<tr class="even">
<td style="text-align: left;">ID</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Read x6 (base address)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EXE</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">ALU computes address: x6 + 0</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Read data from memory at computed address</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WB</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Write loaded value to x5</td>
</tr>
</tbody>
</table>
<p><strong>(c) <code>sw x5, 0(x6)</code></strong> (Store word)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Stage</th>
<th style="text-align: left;">Used?</th>
<th style="text-align: left;">Activity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IF</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Fetch instruction</td>
</tr>
<tr class="even">
<td style="text-align: left;">ID</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Read x5 (value) and x6 (address)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EXE</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">ALU computes address: x6 + 0</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Write x5 value to memory</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WB</td>
<td style="text-align: left;">✗</td>
<td style="text-align: left;">No register to write</td>
</tr>
</tbody>
</table>
<p><strong>(d) <code>beq x5, x6, label</code></strong> (Branch)</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Stage</th>
<th style="text-align: left;">Used?</th>
<th style="text-align: left;">Activity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">IF</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Fetch instruction</td>
</tr>
<tr class="even">
<td style="text-align: left;">ID</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">Read x5 and x6; decode branch target</td>
</tr>
<tr class="odd">
<td style="text-align: left;">EXE</td>
<td style="text-align: left;">✓</td>
<td style="text-align: left;">ALU compares x5 and x6 (subtraction)</td>
</tr>
<tr class="even">
<td style="text-align: left;">MA</td>
<td style="text-align: left;">✗</td>
<td style="text-align: left;">No memory access</td>
</tr>
<tr class="odd">
<td style="text-align: left;">WB</td>
<td style="text-align: left;">✗</td>
<td style="text-align: left;">No register to write</td>
</tr>
</tbody>
</table>
<p><strong>Answer:</strong></p>
<ul>
<li><code>add</code>: IF, ID, EXE, WB</li>
<li><code>lw</code>: IF, ID, EXE, MA, WB (uses all stages)</li>
<li><code>sw</code>: IF, ID, EXE, MA</li>
<li><code>beq</code>: IF, ID, EXE</li>
</ul>
</details>
<h5 id="trace-pipeline-execution-lecture-13-example"><strong>3.6. Trace Pipeline Execution</strong> (Lecture 13, Example)</h5>
<p>Show how the following sequence of instructions would execute in a 5-stage pipeline over time:</p>
<pre class="assembly"><code>add x1, x2, x3
sub x4, x5, x6
and x7, x8, x9
or x10, x11, x12</code></pre>
<details>
<summary>
Click to see the solution
</summary>
<p><strong>Key Concept:</strong> In a pipeline, each instruction progresses through stages one at a time, while new instructions enter behind it.</p>
<p><strong>Pipeline execution diagram:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Clock Cycle</th>
<th style="text-align: left;">1</th>
<th style="text-align: left;">2</th>
<th style="text-align: left;">3</th>
<th style="text-align: left;">4</th>
<th style="text-align: left;">5</th>
<th style="text-align: left;">6</th>
<th style="text-align: left;">7</th>
<th style="text-align: left;">8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>add</code></td>
<td style="text-align: left;">IF</td>
<td style="text-align: left;">ID</td>
<td style="text-align: left;">EX</td>
<td style="text-align: left;">MA</td>
<td style="text-align: left;">WB</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>sub</code></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">IF</td>
<td style="text-align: left;">ID</td>
<td style="text-align: left;">EX</td>
<td style="text-align: left;">MA</td>
<td style="text-align: left;">WB</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>and</code></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">IF</td>
<td style="text-align: left;">ID</td>
<td style="text-align: left;">EX</td>
<td style="text-align: left;">MA</td>
<td style="text-align: left;">WB</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>or</code></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">IF</td>
<td style="text-align: left;">ID</td>
<td style="text-align: left;">EX</td>
<td style="text-align: left;">MA</td>
<td style="text-align: left;">WB</td>
</tr>
</tbody>
</table>
<p><strong>Explanation by clock cycle:</strong></p>
<ul>
<li><strong>Cycle 1:</strong> <code>add</code> enters IF stage</li>
<li><strong>Cycle 2:</strong> <code>add</code> moves to ID; <code>sub</code> enters IF</li>
<li><strong>Cycle 3:</strong> <code>add</code> in EX; <code>sub</code> in ID; <code>and</code> enters IF</li>
<li><strong>Cycle 4:</strong> <code>add</code> in MA; <code>sub</code> in EX; <code>and</code> in ID; <code>or</code> enters IF</li>
<li><strong>Cycle 5:</strong> <code>add</code> completes (WB); <code>sub</code> in MA; <code>and</code> in EX; <code>or</code> in ID</li>
<li><strong>Cycle 6:</strong> <code>sub</code> completes; <code>and</code> in MA; <code>or</code> in EX</li>
<li><strong>Cycle 7:</strong> <code>and</code> completes; <code>or</code> in MA</li>
<li><strong>Cycle 8:</strong> <code>or</code> completes</li>
</ul>
<p><strong>Throughput analysis:</strong></p>
<ul>
<li>Without pipelining: 4 instructions × 5 cycles = 20 cycles</li>
<li>With pipelining: 8 cycles (4 cycles to fill + 4 instructions)</li>
<li>Speedup: 20/8 = 2.5x (approaches 5x for longer sequences)</li>
</ul>
<p><strong>Answer:</strong> All 4 instructions complete in 8 clock cycles. Once the pipeline is full (cycle 4), one instruction completes every cycle.</p>
</details>
<h5 id="single-cycle-vs-pipelined-performance-lecture-13-problem"><strong>3.7. Single-Cycle vs Pipelined Performance</strong> (Lecture 13, Problem)</h5>
<p>A single-cycle processor has the following stage delays:</p>
<ul>
<li>IF: 200 ps</li>
<li>ID: 100 ps</li>
<li>EX: 200 ps</li>
<li>MA: 200 ps</li>
<li>WB: 100 ps</li>
</ul>
<p>Calculate:</p>
<ol type="a">
<li>The clock period for a single-cycle implementation</li>
<li>The clock period for a pipelined implementation</li>
<li>The speedup for executing 100 instructions</li>
</ol>
<details>
<summary>
Click to see the solution
</summary>
<p><strong>Key Concept:</strong> Single-cycle must wait for slowest instruction; pipelined clock is limited by slowest stage.</p>
<p><strong>(a) Single-cycle clock period:</strong></p>
<p>The clock must be long enough for any instruction to complete all stages: <span class="math display">\[T_{single} = IF + ID + EX + MA + WB = 200 + 100 + 200 + 200 + 100 = 800 \text{ ps}\]</span></p>
<p><strong>(b) Pipelined clock period:</strong></p>
<p>The clock is limited by the slowest stage: <span class="math display">\[T_{pipelined} = \max(IF, ID, EX, MA, WB) = \max(200, 100, 200, 200, 100) = 200 \text{ ps}\]</span></p>
<p><strong>(c) Speedup for 100 instructions:</strong></p>
<p><strong>Single-cycle time:</strong> <span class="math display">\[\text{Time}_{single} = 100 \times 800 \text{ ps} = 80,000 \text{ ps}\]</span></p>
<p><strong>Pipelined time:</strong> First instruction takes 5 cycles, then one instruction completes each cycle: <span class="math display">\[\text{Time}_{pipelined} = (5 + 99) \times 200 \text{ ps} = 104 \times 200 = 20,800 \text{ ps}\]</span></p>
<p><strong>Speedup:</strong> <span class="math display">\[\text{Speedup} = \frac{80,000}{20,800} \approx 3.85\]</span></p>
<p><strong>Answer:</strong></p>
<ul>
<li>Single-cycle period: 800 ps</li>
<li>Pipelined period: 200 ps</li>
<li>Speedup: ~3.85x (approaches 4x = 800/200 for large instruction counts)</li>
</ul>
</details>


<style>
	.article-buttons {
		margin-top: 1rem;
	}

	.mark-read {
		padding: 6px 12px;
		border: 1px solid #ccc;
		border-radius: 4px;
		background: #f8f9fa;
		color: #212529;
		font-family: sans-serif;
		cursor: pointer;
		transition: background-color .2s, border-color .2s, color .2s;
		font-size: .9rem;
		line-height: 1.5;
	}

	.mark-read:hover {
		background: #e9ecef;
		border-color: #bdbdbd;
	}

	.mark-read.active {
		background: #4285F4;
		color: #fff;
		border-color: #4285F4;
	}

	.read-title {
		text-decoration: line-through;
		opacity: .7;
	}

	.sidebar-link.read-title {
		text-decoration: line-through;
		opacity: .7;
	}

	.mark-solved {
		padding: 3px 8px;
		border: 1px solid #ccc;
		border-radius: 4px;
		background: #f8f9fa;
		color: #212529;
		font-family: sans-serif;
		cursor: pointer;
		transition: background-color .2s, border-color .2s, color .2s;
		font-size: .8rem;
		line-height: 1.5;
		margin-left: 8px;
		vertical-align: middle;
	}

	.mark-solved:hover {
		background: #e9ecef;
		border-color: #bdbdbd;
	}

	.mark-solved.active {
		background: #34a853;
		color: #fff;
		border-color: #34a853;
	}

	.solved-title {
		text-decoration: line-through;
		opacity: .6;
	}
</style>

<div class="article-buttons">
	<button class="mark-read" data-article-id="">Mark as Read</button>
</div>

<script>
	document.addEventListener('DOMContentLoaded', () => {
		const basePath = '/inno_notes/';
		const curPath = window.location.pathname.replace(/index\.html$/, '').replace(basePath, '');
		const isHome = curPath === '/' || curPath === '' || curPath.includes('index');
		if (isHome) {
			document.querySelector('.article-buttons')?.remove();
		}

		if (!isHome) {
			const currentUrl = window.location.href;
			const btn = document.querySelector('.mark-read');
			const title = document.querySelector('h1');
			const sidebarLinks = document.querySelectorAll('.sidebar-item-text.sidebar-link[data-original-href]');

			const getRead = () => localStorage.getItem(`read_${currentUrl}`);
			const setRead = (v) => v ? localStorage.setItem(`read_${currentUrl}`, 'true')
				: localStorage.removeItem(`read_${currentUrl}`);

			const updateUI = (isRead) => {
				btn.classList.toggle('active', isRead);
				btn.textContent = isRead ? 'Read' : 'Mark as Read';
				title?.classList.toggle('read-title', isRead);
				sidebarLinks.forEach(l => {
					const h = l.getAttribute('data-original-href') || l.getAttribute('href') || '';
					if (h === currentUrl) l.classList.toggle('read-title', isRead);
				});
			};

			updateUI(!!getRead());

			btn?.addEventListener('click', () => {
				const was = !!getRead();
				setRead(!was);
				updateUI(!was);
			});

			sidebarLinks.forEach(l => {
				const h = l.getAttribute('data-original-href') || l.getAttribute('href') || '';
				if (localStorage.getItem(`read_${h}`)) l.classList.add('read-title');
			});
		}

		// Mark as Solved buttons for examples (sections 3.N / 4.N)
		if (!isHome) {
			const pageKey = window.location.pathname;
			document.querySelectorAll('h5').forEach(h5 => {
				const text = h5.textContent || '';
				if (!/^\s*[34]\.\d+[\.\s]/.test(text)) return;

				const solvedKey = `solved_${pageKey}_${text.trim()}`;
				const btn = document.createElement('button');
				btn.className = 'mark-solved';
				btn.textContent = '✓ Solved';

				// Wrap text nodes in a span so strikethrough doesn't affect other children (e.g. anchor icon)
				let textSpan = h5.querySelector('.problem-title-text');
				if (!textSpan) {
					textSpan = document.createElement('span');
					textSpan.className = 'problem-title-text';
					const nodes = [...h5.childNodes].filter(n => n.nodeType === Node.TEXT_NODE || n.nodeName === 'STRONG' || n.nodeName === 'EM');
					nodes.forEach(n => textSpan.appendChild(n.cloneNode(true)));
					nodes.forEach(n => n.parentNode?.removeChild(n));
					h5.prepend(textSpan);
				}

				const applyState = (solved) => {
					btn.classList.toggle('active', solved);
					textSpan.classList.toggle('solved-title', solved);
				};

				applyState(!!localStorage.getItem(solvedKey));

				btn.addEventListener('click', (e) => {
					e.stopPropagation();
					const was = !!localStorage.getItem(solvedKey);
					was ? localStorage.removeItem(solvedKey) : localStorage.setItem(solvedKey, 'true');
					applyState(!was);
				});

				h5.appendChild(btn);
			});
		}

		const sidebar = document.querySelector('#quarto-sidebar');
		if (!sidebar) return;

		const sections = sidebar.querySelectorAll('li.sidebar-item-section');
		sections.forEach(section => {
			const toggle = section.querySelector('.sidebar-item-toggle');
			const targetId = toggle?.getAttribute('data-bs-target');
			const target = targetId ? document.querySelector(targetId) : null;
			if (!toggle || !target) return;

			const storageKey = `sidebar_section_${targetId}`;

			const saved = localStorage.getItem(storageKey);
			if (saved === 'open') {
				target.classList.add('show');
				toggle.setAttribute('aria-expanded', 'true');
				toggle.querySelector('i')?.classList.replace('bi-chevron-right', 'bi-chevron-down');
			} else {
				// collapse by default if not explicitly opened
				target.classList.remove('show');
				toggle.setAttribute('aria-expanded', 'false');
				toggle.querySelector('i')?.classList.replace('bi-chevron-down', 'bi-chevron-right');
			}

			target.addEventListener('show.bs.collapse', () => {
				localStorage.setItem(storageKey, 'open');
				toggle.setAttribute('aria-expanded', 'true');
				toggle.querySelector('i')?.classList.replace('bi-chevron-right', 'bi-chevron-down');
			});

			target.addEventListener('hide.bs.collapse', () => {
				localStorage.setItem(storageKey, 'closed');
				toggle.setAttribute('aria-expanded', 'false');
				toggle.querySelector('i')?.classList.replace('bi-chevron-down', 'bi-chevron-right');
			});
		});

		const scrollKey = 'sidebar_scroll_top';
		const savedScroll = localStorage.getItem(scrollKey);
		if (savedScroll && !isNaN(parseInt(savedScroll, 10))) {
			sidebar.scrollTop = parseInt(savedScroll, 10);
		}
		sidebar.addEventListener('scroll', () => {
			localStorage.setItem(scrollKey, sidebar.scrollTop);
		});
	});
</script>




</body></html>