#!/usr/bin/env python3
"""Regenerate metric-matched fallback @font-face block in styles/styles.css.

Why: with font-display:swap the first paint uses a fallback font whose
metrics differ from the webfont -> text/tables visibly rescale when the
webfont arrives. A fallback face with size-adjust + ascent/descent/
line-gap overrides tuned to the REAL binaries makes the swap metrically
invisible (same technique as Next.js/fontaine).

size-adjust is tuned on a cleaned corpus of the site's own rendered text
(markdown/math/code syntax stripped), so the scalar minimizes real width
error instead of an arbitrary alphabet average. Vertical overrides come
straight from each binary's hhea table.

Usage: python3 scripts/tune-font-fallbacks.py [--check]
  --check: exit non-zero if styles.css block differs (CI gate).
Requires: fonttools (pip install "fonttools==4.61.1").
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONTS = ROOT / "styles" / "fonts"
CSS = ROOT / "styles" / "styles.css"

BEGIN = "/* === metric-matched fallbacks (generated by scripts/tune-font-fallbacks.py — do not hand-edit) === */"
END = "/* === end metric-matched fallbacks === */"

# (css family, webfont file, style, local fallback srcs, reference file)
FACES = [
    ("SF Pro Text Fallback", "SF-Pro-Text-Regular.woff2", "normal",
     ['local("Arial")', 'local("Helvetica Neue")', 'local("Helvetica")'], "arial"),
    ("SF Pro Text Fallback", "SF-Pro-Text-RegularItalic.woff2", "italic",
     ['local("Arial Italic")', 'local("Arial")'], "arial"),
    ("SF Pro Display Fallback", "SF-Pro-Display-Regular.woff2", "normal",
     ['local("Arial")', 'local("Helvetica Neue")', 'local("Helvetica")'], "arial"),
    ("SF Pro Display Fallback", "SF-Pro-Display-RegularItalic.woff2", "italic",
     ['local("Arial Italic")', 'local("Arial")'], "arial"),
    ("Archivo Fallback", "Archivo-Regular.woff2", "normal",
     ['local("Arial")', 'local("Helvetica Neue")', 'local("Helvetica")'], "arial"),
    ("Archivo Fallback", "Archivo-Italic.woff2", "italic",
     ['local("Arial Italic")', 'local("Arial")'], "arial"),
    ("SF Mono Fallback", "SF-Mono-Regular.woff2", "normal",
     ['local("Courier New")', 'local("Menlo")'], "courier"),
    ("SF Mono Fallback", "SF-Mono-RegularItalic.woff2", "italic",
     ['local("Courier New")', 'local("Menlo")'], "courier"),
]

ARIAL = "/System/Library/Fonts/Supplemental/Arial.ttf"
ARIAL_ITALIC = "/System/Library/Fonts/Supplemental/Arial Italic.ttf"
COURIER = "/System/Library/Fonts/Supplemental/Courier New.ttf"

DROP = set("*_$`#<>|~^")


def clean_line(ln):
    s = ln.strip()
    if not s or s.startswith("|") or s.startswith("<") or set(s) <= set("-*_= "):
        return ""
    if s.startswith(">"):
        s = s[1:]
    t = s.lstrip("#").lstrip()
    if t[:2] == "- ":
        t = t[2:]
    i = 0
    while i < len(t) and t[i].isdigit():
        i += 1
    if i and t[i:i + 2] == ". ":
        t = t[i + 2:]
    parts, inmath, buf = [], False, []
    for ch in t:
        if ch == "$":
            if inmath:
                parts.append("".join(buf))
                buf = []
            inmath = not inmath
        elif not inmath:
            buf.append(ch)
    parts.append("".join(buf))
    t = "".join(parts)
    parts, incode, buf = [], False, []
    for ch in t:
        if ch == "`":
            incode = not incode
        elif not incode:
            buf.append(ch)
    t = "".join(buf)
    t = t.replace("](", " ").replace("[", "").replace("]", "").replace("(", "").replace(")", "")
    return "".join(ch for ch in t if ch not in DROP)


def build_corpus():
    from collections import Counter
    freq: Counter = Counter()
    for f in sorted(ROOT.rglob("*.qmd")):
        if "_site" in f.parts or "_freeze" in f.parts:
            continue
        t = f.read_text(encoding="utf-8")
        if t.startswith("---"):
            _, _, t = t.split("---", 2)
        out, incode = [], False
        for ln in t.splitlines():
            if ln.strip().startswith("```"):
                incode = not incode
                continue
            if not incode:
                c = clean_line(ln)
                if c:
                    out.append(c)
        for ch in chr(10).join(out):
            freq[ch] += 1
        if sum(freq.values()) > 300000:
            break
    return freq


def load(path):
    from fontTools.ttLib import TTFont
    return TTFont(path)


def corpus_ratio(web_path, ref_path, freq):
    web = load(web_path)
    ref = load(ref_path)
    wu, ru = web["head"].unitsPerEm, ref["head"].unitsPerEm
    wh, rh = web["hmtx"], ref["hmtx"]
    wc, rc = web.getBestCmap(), ref.getBestCmap()
    sw = sr = 0.0
    for ch, k in freq.items():
        cp = ord(ch)
        if cp in wc and cp in rc:
            sw += wh[wc[cp]][0] / wu * k
            sr += rh[rc[cp]][0] / ru * k
    return sw / sr * 100.0


def vertical(web_path):
    web = load(web_path)
    upm = web["head"].unitsPerEm
    h = web["hhea"]
    return h.ascent / upm * 100.0, -h.descent / upm * 100.0, h.lineGap / upm * 100.0


def build_block():
    freq = build_corpus()
    out = [BEGIN]
    for family, woff, style, srcs, ref in FACES:
        ref_path = COURIER if ref == "courier" else ARIAL
        asc, desc, lg = vertical(FONTS / woff)
        size = corpus_ratio(FONTS / woff, ref_path, freq)
        out.append("@font-face {")
        out.append('	font-family: "' + family + '";')
        out.append("	src: " + ", ".join(srcs) + ";")
        out.append("	font-style: " + style + ";")
        out.append("	font-weight: 100 900;")
        out.append("	font-display: swap;")
        out.append("	size-adjust: {:.2f}%;".format(size))
        out.append("	ascent-override: {:.2f}%;".format(asc))
        out.append("	descent-override: {:.2f}%;".format(desc))
        out.append("	line-gap-override: {:.2f}%;".format(lg))
        out.append("}")
        out.append("")
        print("{:24s} {:6s} size={:.2f}% asc={:.2f}% desc={:.2f}% lg={:.2f}%".format(
            family, style, size, asc, desc, lg))
    out.append(END)
    return "\n".join(out)


def main():
    check = "--check" in sys.argv
    block = build_block()
    text = CSS.read_text(encoding="utf-8")
    if BEGIN in text:
        pre, rest = text.split(BEGIN, 1)
        _, post = rest.split(END, 1)
        new = pre + block + post
    else:
        anchor = ":root {"
        pre, post = text.split(anchor, 1)
        new = pre + block + "\n" + anchor + post
    if check:
        sys.exit(0 if new == text else 1)
    if new != text:
        CSS.write_text(new, encoding="utf-8")
        print("styles.css fallback block updated")
    else:
        print("styles.css fallback block already current")


if __name__ == "__main__":
    main()
