name: Deploy Quarto Website

on:
  push:
    branches: [main]  # or 'master', depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup Pandoc (optional, if needed by your project)
        run: sudo apt-get install -y pandoc

      - name: Install dependencies (if using R or Python)
        run: |
          # Install Python dependencies if you use Python in your .qmd files
          # pip install -r requirements.txt

          # OR install R dependencies (if using R)
          # sudo apt-get install -y r-base
          # Rscript -e 'install.packages(c("quarto"))'

      - name: Render Quarto Project
        run: quarto render

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
